//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface ActionSheetView : UIView
{
    CDUnknownBlockType _clickBlock;
    UIView *_sheetView;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) UIView *sheetView; // @synthesize sheetView=_sheetView;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void).cxx_destruct;
- (id)appRootViewController;
- (id)imageWithColor:(id)arg1;
- (void)sheetBtnClick:(id)arg1;
- (void)coverClick;
- (void)show;
- (void)setupBtnWithTitles;
- (id)initWithCancleTitle:(id)arg1 otherTitleArr:(id)arg2;

@end

