//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "WXApiDelegate-Protocol.h"

@class CLLocationManager, CTCallCenter, NSString, SFGatherConfig, SFRootViewController, UILocalNotification, UIWindow;

@interface AppDelegate : UIResponder <CLLocationManagerDelegate, WXApiDelegate, UIApplicationDelegate>
{
    _Bool _isBToCLogin;
    _Bool _isAlert;
    unsigned int _soundID;
    UIWindow *_window;
    CLLocationManager *_manager;
    UILocalNotification *_localNotification;
    CTCallCenter *_callCenter;
    SFGatherConfig *_config;
    SFRootViewController *_rootViewController;
}

+ (id)shareUtil;
@property(retain, nonatomic) SFRootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) SFGatherConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) CTCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(nonatomic) unsigned int soundID; // @synthesize soundID=_soundID;
@property(retain, nonatomic) UILocalNotification *localNotification; // @synthesize localNotification=_localNotification;
@property(nonatomic) _Bool isAlert; // @synthesize isAlert=_isAlert;
@property(retain, nonatomic) CLLocationManager *manager; // @synthesize manager=_manager;
@property(nonatomic) _Bool isBToCLogin; // @synthesize isBToCLogin=_isBToCLogin;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)login_or_exit:(_Bool)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)sfuploadAllLogInfoFromServer;
- (void)isFirstRunApp;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)clearAllUserDefaultsData;
- (void)updateMethod:(id)arg1;
- (void)checkAppUpdate;
- (void)closeSoundEffect;
- (void)playSoundEffect:(id)arg1;
- (void)pusNotification:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)initLocationManager;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)deleteObjectsToDatabaseGpsPath;
- (void)deleteObjectsToDatabaseHistory;
- (void)configSFGather;
- (void)initSFPayUnitedManager;
- (void)configHttpsCer;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (_Bool)application:(id)arg1 shouldAllowExtensionPointIdentifier:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

