//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIAlertViewDelegate-Protocol.h"

@class NSString, UIButton, UIImageView;

@interface BrowseView : UIView <UIAlertViewDelegate>
{
    UIImageView *_browseImageView;
    UIButton *_deleteBtn;
    UIImageView *_currentImageView;
    CDUnknownBlockType _deleteImage;
    struct CGRect _oldFrame;
    struct CGRect _largeFrame;
}

@property(nonatomic) struct CGRect largeFrame; // @synthesize largeFrame=_largeFrame;
@property(nonatomic) struct CGRect oldFrame; // @synthesize oldFrame=_oldFrame;
@property(copy, nonatomic) CDUnknownBlockType deleteImage; // @synthesize deleteImage=_deleteImage;
@property(retain, nonatomic) UIImageView *currentImageView; // @synthesize currentImageView=_currentImageView;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIImageView *browseImageView; // @synthesize browseImageView=_browseImageView;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)deleteDidClicked:(id)arg1;
- (void)panView:(id)arg1;
- (void)pinchAction:(id)arg1;
- (void)tapAction:(id)arg1;
- (void)showBrowseView;
- (id)appRootViewController;
- (void)createBrowseViews;
- (id)initWithImage:(id)arg1 deleteImage:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

