//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GPSModel : NSObject
{
    NSString *_taskId;
    NSString *_childTaskId;
    NSString *_deptCode;
    NSString *_serial;
    NSString *_customDeptCode;
    NSString *_vehicleNumber;
    NSString *_coustomVehicleNumber;
}

@property(retain, nonatomic) NSString *coustomVehicleNumber; // @synthesize coustomVehicleNumber=_coustomVehicleNumber;
@property(retain, nonatomic) NSString *vehicleNumber; // @synthesize vehicleNumber=_vehicleNumber;
@property(retain, nonatomic) NSString *customDeptCode; // @synthesize customDeptCode=_customDeptCode;
@property(retain, nonatomic) NSString *serial; // @synthesize serial=_serial;
@property(retain, nonatomic) NSString *deptCode; // @synthesize deptCode=_deptCode;
@property(retain, nonatomic) NSString *childTaskId; // @synthesize childTaskId=_childTaskId;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;

@end

