//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, SFPlaceHolderTextView, UIButton, UIImageView, UILabel;
@protocol LineOverlayFootViewDelegate;

@interface LineOverlayFootView : UIView <UITextViewDelegate>
{
    _Bool _isFeedback;
    _Bool _isLineFeedback;
    id <LineOverlayFootViewDelegate> _delegate;
    long long _coincideType;
    long long _reasonType;
    NSString *_remark;
    long long _viewType;
    UIImageView *_topBgView;
    UILabel *_completeLab;
    UILabel *_planLineLab;
    UILabel *_actualLineLab;
    UILabel *_lineStateLab;
    UIView *_planView;
    UIView *_actualView;
    UIView *_lineView;
    UIView *_textBgView;
    SFPlaceHolderTextView *_myTextView;
    UIImageView *_bottomBgView;
    UIButton *_titleBtn;
    UIButton *_leftBtn;
    UIButton *_rightBtn;
    UIButton *_confirmBtn;
    UILabel *_bottomLab;
    UILabel *_abnormalLab;
    UIButton *_moreBtn;
    double _footHeight;
    UIImageView *_feedbackBgView;
    UIButton *_feedbackBtn;
    UIButton *_returnBtn;
}

@property(retain, nonatomic) UIButton *returnBtn; // @synthesize returnBtn=_returnBtn;
@property(retain, nonatomic) UIButton *feedbackBtn; // @synthesize feedbackBtn=_feedbackBtn;
@property(retain, nonatomic) UIImageView *feedbackBgView; // @synthesize feedbackBgView=_feedbackBgView;
@property(nonatomic) double footHeight; // @synthesize footHeight=_footHeight;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) UILabel *abnormalLab; // @synthesize abnormalLab=_abnormalLab;
@property(retain, nonatomic) UILabel *bottomLab; // @synthesize bottomLab=_bottomLab;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(retain, nonatomic) UIButton *titleBtn; // @synthesize titleBtn=_titleBtn;
@property(retain, nonatomic) UIImageView *bottomBgView; // @synthesize bottomBgView=_bottomBgView;
@property(retain, nonatomic) SFPlaceHolderTextView *myTextView; // @synthesize myTextView=_myTextView;
@property(retain, nonatomic) UIView *textBgView; // @synthesize textBgView=_textBgView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *actualView; // @synthesize actualView=_actualView;
@property(retain, nonatomic) UIView *planView; // @synthesize planView=_planView;
@property(retain, nonatomic) UILabel *lineStateLab; // @synthesize lineStateLab=_lineStateLab;
@property(retain, nonatomic) UILabel *actualLineLab; // @synthesize actualLineLab=_actualLineLab;
@property(retain, nonatomic) UILabel *planLineLab; // @synthesize planLineLab=_planLineLab;
@property(retain, nonatomic) UILabel *completeLab; // @synthesize completeLab=_completeLab;
@property(retain, nonatomic) UIImageView *topBgView; // @synthesize topBgView=_topBgView;
@property(nonatomic) _Bool isLineFeedback; // @synthesize isLineFeedback=_isLineFeedback;
@property(nonatomic) _Bool isFeedback; // @synthesize isFeedback=_isFeedback;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) long long reasonType; // @synthesize reasonType=_reasonType;
@property(nonatomic) long long coincideType; // @synthesize coincideType=_coincideType;
@property(nonatomic) __weak id <LineOverlayFootViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)checkInfo;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)btnAction:(id)arg1;
- (void)updateFootViewIsFold:(_Bool)arg1;
- (void)updateText;
- (void)addConstraintsIsNeedbackCoincide;
- (void)addConstraintsNotNeedbackCoincideUnknowAndMisfit;
- (void)addConstraintsCoincideAbnormal;
- (void)addConstraintsNotNeedbackCoincideFit;
- (void)addConstraintsType:(long long)arg1;
- (void)addBottomViewConstraints;
- (void)addTopViewConstraints;
- (void)addFeedbackView;
- (id)initWithFrame:(struct CGRect)arg1 coincideType:(long long)arg2 reasonType:(long long)arg3 isFeedback:(_Bool)arg4 isLineFeedback:(_Bool)arg5 remark:(id)arg6 viewType:(long long)arg7;
- (id)initWithFrame:(struct CGRect)arg1 stateType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

