//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAOverlayPathRenderer.h"

@class MAArc;

@interface MAArcRenderer : MAOverlayPathRenderer
{
}

- (id)initWithArc:(id)arg1;
- (void)doRenderContent2;
- (void)doRenderContent;
- (void)glRender;
- (void)setFillColor:(id)arg1;
@property(readonly, nonatomic) MAArc *arc;

@end

