//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIColor;

@interface PgyBottomBarView : UIView
{
    UIButton *_selectColorButton;
    UIButton *_textButton;
    UIButton *_deleteButton;
    UIView *_colorIndicatorView;
    UIColor *_themeColor;
}

@property(retain, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor;
@property(retain, nonatomic) UIView *colorIndicatorView; // @synthesize colorIndicatorView=_colorIndicatorView;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *textButton; // @synthesize textButton=_textButton;
@property(retain, nonatomic) UIButton *selectColorButton; // @synthesize selectColorButton=_selectColorButton;
- (void).cxx_destruct;
- (void)show;
- (void)hide;
- (id)stringToUIImage:(id)arg1;
- (void)setup;
- (id)initWithThemeColor:(id)arg1;

@end

