//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PgyDevice : NSObject
{
    NSString *_deviceId;
    NSString *_deviceModel;
    NSString *_deviceName;
    NSString *_systemVersion;
    NSString *_resolution;
    NSString *_jailBroken;
    NSString *_freeSapce;
    NSString *_freeRam;
    NSString *_portrait;
    NSString *_network;
    NSString *_battery;
}

+ (id)currentDevice;
@property(retain, nonatomic) NSString *battery; // @synthesize battery=_battery;
@property(retain, nonatomic) NSString *network; // @synthesize network=_network;
@property(retain, nonatomic) NSString *portrait; // @synthesize portrait=_portrait;
@property(retain, nonatomic) NSString *freeRam; // @synthesize freeRam=_freeRam;
@property(retain, nonatomic) NSString *freeSapce; // @synthesize freeSapce=_freeSapce;
@property(retain, nonatomic) NSString *jailBroken; // @synthesize jailBroken=_jailBroken;
@property(retain, nonatomic) NSString *resolution; // @synthesize resolution=_resolution;
@property(retain, nonatomic) NSString *systemVersion; // @synthesize systemVersion=_systemVersion;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
@property(retain, nonatomic) NSString *deviceModel; // @synthesize deviceModel=_deviceModel;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
- (void).cxx_destruct;
- (id)currentDeviceName;
- (_Bool)isJailbroken;
- (id)freeDiskSpaceInBytes;
- (id)freeMemory;
- (id)currentCarrierName;
- (id)currentWiFiSSID;

@end

