//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface PgyMicrophoneView : UIView
{
    float microphoneBottom;
    float microphoneRight;
    UILabel *maxLengthLabel;
    UILabel *countDownLabel;
    _Bool maxLengthLabelAdded;
}

- (void).cxx_destruct;
- (void)setVolumView:(long long)arg1;
- (void)dispCountDown:(long long)arg1;
- (void)addMaxLegnthLabel;
- (void)addMicrophoneLayer;
- (id)init;

@end

