//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UIColor;

@interface PgySelectColorView : UIView
{
    NSMutableArray *_buttonArray;
    UIColor *_currentColor;
    NSArray *_buttonColorArray;
    id _delegate;
    UIColor *_themeColor;
}

@property(retain, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor;
@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *buttonColorArray; // @synthesize buttonColorArray=_buttonColorArray;
@property(retain, nonatomic) UIColor *currentColor; // @synthesize currentColor=_currentColor;
@property(retain, nonatomic) NSMutableArray *buttonArray; // @synthesize buttonArray=_buttonArray;
- (void).cxx_destruct;
- (void)show;
- (void)hide;
- (id)stringToUIImage:(id)arg1;
- (void)addSelectedIconForButton:(id)arg1;
- (void)colorButtonClicked:(id)arg1;
- (void)setup;
- (id)initWithThemeColor:(id)arg1;

@end

