//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseModel.h"

@class NSString;

@interface ProofChoiceModel : BaseModel
{
    _Bool _canNotClick;
    NSString *_title;
    NSString *_detial;
}

@property(nonatomic) _Bool canNotClick; // @synthesize canNotClick=_canNotClick;
@property(copy, nonatomic) NSString *detial; // @synthesize detial=_detial;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

