//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAudioPlayer, CTCallCenter;

@interface PushMessageManager : NSObject
{
    _Bool _isLogin;
    CDUnknownBlockType _receiveMessageBlock;
    CTCallCenter *_callCenter;
    AVAudioPlayer *_avAudioPlayer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) AVAudioPlayer *avAudioPlayer; // @synthesize avAudioPlayer=_avAudioPlayer;
@property(retain, nonatomic) CTCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(copy, nonatomic) CDUnknownBlockType receiveMessageBlock; // @synthesize receiveMessageBlock=_receiveMessageBlock;
- (void).cxx_destruct;
- (void)pushType:(id)arg1 message:(id)arg2 title:(id)arg3;
- (void)testPushMessage;
- (void)speech:(id)arg1;
- (void)speech;
- (void)pushLocalNotification:(id)arg1 objDic:(id)arg2;
- (void)didReceiveNetworkingPushConnect:(id)arg1;
- (void)didReceivePushMessage:(id)arg1;
- (void)puchConfigsLoginOrExit:(_Bool)arg1 hostsArr:(id)arg2 appId:(unsigned long long)arg3 pushAlias:(id)arg4;
- (void)configsLoginOrExit:(_Bool)arg1 hostsArr:(id)arg2 appId:(unsigned long long)arg3 pushAlias:(id)arg4 receiveMessageBlock:(CDUnknownBlockType)arg5;
- (void)configsApplication:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)configsApplication:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

@end

