//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SF_JSONModel.h"

@class NSString;
@protocol Optional;

@interface SDKPayOrderModel : SF_JSONModel
{
    NSString *_businessNo;
    NSString *_tradeScene;
    NSString<Optional> *_orderType;
    NSString<Optional> *_channelType;
    NSString *_loginMode;
    NSString<Optional> *_casLoginUrl;
}

@property(retain, nonatomic) NSString<Optional> *casLoginUrl; // @synthesize casLoginUrl=_casLoginUrl;
@property(retain, nonatomic) NSString *loginMode; // @synthesize loginMode=_loginMode;
@property(retain, nonatomic) NSString<Optional> *channelType; // @synthesize channelType=_channelType;
@property(retain, nonatomic) NSString<Optional> *orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *tradeScene; // @synthesize tradeScene=_tradeScene;
@property(retain, nonatomic) NSString *businessNo; // @synthesize businessNo=_businessNo;
- (void).cxx_destruct;

@end

