//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDKAPIBaseModel.h"

#import "SDKResponseProtocol-Protocol.h"

@class NSString;
@protocol Optional;

@interface SDKResponseBaseModel : SDKAPIBaseModel <SDKResponseProtocol>
{
    NSString *_responseTime;
    NSString<Optional> *_data;
    NSString *_rltCode;
    NSString<Optional> *_rltMsg;
}

@property(retain, nonatomic) NSString<Optional> *rltMsg; // @synthesize rltMsg=_rltMsg;
@property(retain, nonatomic) NSString *rltCode; // @synthesize rltCode=_rltCode;
@property(retain, nonatomic) NSString<Optional> *data; // @synthesize data=_data;
@property(retain, nonatomic) NSString *responseTime; // @synthesize responseTime=_responseTime;
- (void).cxx_destruct;

// Remaining properties
@property(retain, nonatomic) NSString *charset;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *serviceName;
@property(retain, nonatomic) NSString *sign;
@property(readonly) Class superclass;

@end

