//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDKAPIBaseModel.h"

#import "SDKRequestProtocol-Protocol.h"

@class NSString;

@interface SDKRequestBaseModel : SDKAPIBaseModel <SDKRequestProtocol>
{
    NSString *_signType;
    NSString *_requestTime;
    NSString *_serviceVersion;
    NSString *_sdkVersion;
}

@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain, nonatomic) NSString *serviceVersion; // @synthesize serviceVersion=_serviceVersion;
@property(retain, nonatomic) NSString *requestTime; // @synthesize requestTime=_requestTime;
@property(retain, nonatomic) NSString *signType; // @synthesize signType=_signType;
- (void).cxx_destruct;

// Remaining properties
@property(retain, nonatomic) NSString *charset;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *serviceName;
@property(retain, nonatomic) NSString *sign;
@property(readonly) Class superclass;

@end

