//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFAbnormTypeViewControllerDelegate-Protocol.h"
#import "SFImageCollectionViewCellDelegate-Protocol.h"
#import "SFRecordDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSMutableArray, NSString, NSTimer, SFPlaceHolderTextView, SFRecord, UIButton, UICollectionView, UIImageView, UILabel, UIView;
@protocol SFAbnormalHandelVCDelegate;

@interface SFAbnormalHandelVC : UIViewController <UITextViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, SFImageCollectionViewCellDelegate, SFAbnormTypeViewControllerDelegate, SFRecordDelegate>
{
    UICollectionView *_collectionView;
    NSMutableArray *_selectedPhotos;
    NSMutableArray *_unUpPhotos;
    NSMutableArray *_imageStrArr;
    NSMutableArray *_photoPath;
    NSString *_audioUrl;
    double _itemWH;
    double _margin;
    UILabel *imageTitle;
    int _recordType;
    NSString *_taskId;
    NSString *_deptCode;
    NSString *_bizType;
    NSString *_contentId;
    id <SFAbnormalHandelVCDelegate> _delegate;
    UILabel *_maxPlaceholder;
    SFPlaceHolderTextView *_abnormTextView;
    UILabel *_typeLabel;
    UILabel *_locationLabel;
    UIView *_abnormTypeView;
    UIView *_inputVoiceView;
    UIImageView *_voiceImageView;
    UIButton *_tapeBtn;
    UIView *_line;
    UIButton *_uploadAbnormBtn;
    long long _type;
    SFRecord *_record;
    NSString *_recordPath;
    NSString *_fileName;
    UIView *_layerView;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIView *layerView; // @synthesize layerView=_layerView;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSString *recordPath; // @synthesize recordPath=_recordPath;
@property(retain, nonatomic) SFRecord *record; // @synthesize record=_record;
@property(nonatomic) int recordType; // @synthesize recordType=_recordType;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIButton *uploadAbnormBtn; // @synthesize uploadAbnormBtn=_uploadAbnormBtn;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIButton *tapeBtn; // @synthesize tapeBtn=_tapeBtn;
@property(retain, nonatomic) UIImageView *voiceImageView; // @synthesize voiceImageView=_voiceImageView;
@property(retain, nonatomic) UIView *inputVoiceView; // @synthesize inputVoiceView=_inputVoiceView;
@property(retain, nonatomic) UIView *abnormTypeView; // @synthesize abnormTypeView=_abnormTypeView;
@property(retain, nonatomic) UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) SFPlaceHolderTextView *abnormTextView; // @synthesize abnormTextView=_abnormTextView;
@property(retain, nonatomic) UILabel *maxPlaceholder; // @synthesize maxPlaceholder=_maxPlaceholder;
@property(nonatomic) __weak id <SFAbnormalHandelVCDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSString *deptCode; // @synthesize deptCode=_deptCode;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)sf_didRecordWithrecordPath:(id)arg1 fileName:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)deleteImageWithImage:(id)arg1;
- (void)showImageWithArray:(id)arg1 index:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)recordViewAnimation;
- (void)tapeBtnAction:(id)arg1;
- (void)upAbnormFromServer;
- (void)uploadRecord;
- (void)uploadImage;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)abnormTypeName:(id)arg1 typeCode:(long long)arg2;
- (void)abnormTypeTap;
- (void)uploadAbnormBtnAction:(id)arg1;
- (void)initViews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

