//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSArray, NSString;
@protocol SFSwitchElecLockModel;

@interface SFAbnormRouteModel : JSONModel
{
    NSString *_address;
    NSString *_desContent;
    NSString *_driverTaskId;
    NSString *_operateTime;
    NSString *_serverPath;
    NSString *_type;
    NSString *_typeStr;
    NSString *_audioPath;
    NSString *_uuid;
    NSString *_recoveryTime;
    NSArray<SFSwitchElecLockModel> *_switchElecLockLog;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSArray<SFSwitchElecLockModel> *switchElecLockLog; // @synthesize switchElecLockLog=_switchElecLockLog;
@property(retain, nonatomic) NSString *recoveryTime; // @synthesize recoveryTime=_recoveryTime;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSString *audioPath; // @synthesize audioPath=_audioPath;
@property(retain, nonatomic) NSString *typeStr; // @synthesize typeStr=_typeStr;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *serverPath; // @synthesize serverPath=_serverPath;
@property(retain, nonatomic) NSString *operateTime; // @synthesize operateTime=_operateTime;
@property(retain, nonatomic) NSString *driverTaskId; // @synthesize driverTaskId=_driverTaskId;
@property(retain, nonatomic) NSString *desContent; // @synthesize desContent=_desContent;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
- (void).cxx_destruct;

@end

