//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFAdvertModel : JSONModel
{
    _Bool _needParams;
    _Bool _needShare;
    _Bool _needLogin;
    _Bool _shareUrlAppendUserInfo;
    _Bool _needAlert;
    _Bool _isAdvertFirst;
    NSString *_imgUrl;
    NSString *_detailUrl;
    NSString *_shareUrl;
    NSString *_title;
    NSString *_shareMsg;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(nonatomic) _Bool isAdvertFirst; // @synthesize isAdvertFirst=_isAdvertFirst;
@property(nonatomic) _Bool needAlert; // @synthesize needAlert=_needAlert;
@property(retain, nonatomic) NSString *shareMsg; // @synthesize shareMsg=_shareMsg;
@property(nonatomic) _Bool shareUrlAppendUserInfo; // @synthesize shareUrlAppendUserInfo=_shareUrlAppendUserInfo;
@property(nonatomic) _Bool needLogin; // @synthesize needLogin=_needLogin;
@property(nonatomic) _Bool needShare; // @synthesize needShare=_needShare;
@property(nonatomic) _Bool needParams; // @synthesize needParams=_needParams;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) NSString *detailUrl; // @synthesize detailUrl=_detailUrl;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;

@end

