//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, SFAlertWindow, SFBaseViewController, UIWindow;

@interface SFAlert : NSObject
{
    UIWindow *_mainWindow;
    SFAlertWindow *_SFWindow;
    NSMutableArray *_queueArray;
    SFBaseViewController *_viewController;
}

+ (void)closeWithCompletionBlock:(CDUnknownBlockType)arg1;
+ (void)clearQueue;
+ (void)continueQueueDisplay;
+ (void)configMainWindow:(id)arg1;
+ (id)getAlertWindow;
+ (id)actionsheet;
+ (id)alert;
+ (id)shareManager;
@property(retain, nonatomic) SFBaseViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSMutableArray *queueArray; // @synthesize queueArray=_queueArray;
@property(retain, nonatomic) SFAlertWindow *SFWindow; // @synthesize SFWindow=_SFWindow;
@property(retain, nonatomic) UIWindow *mainWindow; // @synthesize mainWindow=_mainWindow;
- (void).cxx_destruct;

@end

