//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseTableVC.h"

@interface SFBaseRefreshVC : SFBaseTableVC
{
    long long _pageIndex;
}

@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void)didReceiveMemoryWarning;
- (void)loadMoreData;
- (void)loadNewData;
- (void)viewDidLoad;

@end

