//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface SFBidDetailFeelItem : NSObject
{
    long long _feeTypeDetail;
    long long _settleType;
    long long _settleDays;
    UIImage *_img;
    NSString *_title;
    double _price;
    NSString *_remark;
    double _lastChange;
    double _change;
    long long _itemType;
}

@property(nonatomic) long long itemType; // @synthesize itemType=_itemType;
@property(nonatomic) double change; // @synthesize change=_change;
@property(nonatomic) double lastChange; // @synthesize lastChange=_lastChange;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) double price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *img; // @synthesize img=_img;
@property(nonatomic) long long settleDays; // @synthesize settleDays=_settleDays;
@property(nonatomic) long long settleType; // @synthesize settleType=_settleType;
@property(nonatomic) long long feeTypeDetail; // @synthesize feeTypeDetail=_feeTypeDetail;
- (void).cxx_destruct;
- (id)initWithType:(long long)arg1 BidDetailFeelItemType:(long long)arg2;

@end

