//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface SFBrowseView : UIView
{
    UIImageView *_browseImageView;
    UIImageView *_currentImageView;
    struct CGRect _oldFrame;
}

@property(nonatomic) struct CGRect oldFrame; // @synthesize oldFrame=_oldFrame;
@property(retain, nonatomic) UIImageView *currentImageView; // @synthesize currentImageView=_currentImageView;
@property(retain, nonatomic) UIImageView *browseImageView; // @synthesize browseImageView=_browseImageView;
- (void).cxx_destruct;
- (void)tapAction:(id)arg1;
- (void)showBrowseView;
- (id)appRootViewController;
- (void)createBrowseViews;
- (id)initWithImage:(id)arg1;

@end

