//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface SFCarCheckAbnormalCell : UITableViewCell
{
    UIView *_bgView;
    UILabel *_titleLab;
    UILabel *_remarkLab;
    UIImageView *_lineView;
    UIView *_upCircularBead;
    UIView *_downCircularBead;
}

+ (double)getHeightWith:(id)arg1;
@property(retain, nonatomic) UIView *downCircularBead; // @synthesize downCircularBead=_downCircularBead;
@property(retain, nonatomic) UIView *upCircularBead; // @synthesize upCircularBead=_upCircularBead;
@property(retain, nonatomic) UIImageView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *remarkLab; // @synthesize remarkLab=_remarkLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)confinfomationDataArr:(id)arg1 indexPath:(id)arg2;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

