//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseCell.h"

@class NSIndexPath, UIImageView, UILabel, UITextField;
@protocol SFCarOutCheckCell2Delegate;

@interface SFCarOutCheckCell2 : SFBaseCell
{
    id <SFCarOutCheckCell2Delegate> _delegate;
    UITextField *_hourTextField;
    UITextField *_minTextField;
    UILabel *_hourLab;
    UILabel *_minLab;
    NSIndexPath *_indexPath;
    UIImageView *_bgView;
    UILabel *_titleLab;
}

+ (double)cellHeight;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) UILabel *minLab; // @synthesize minLab=_minLab;
@property(retain, nonatomic) UILabel *hourLab; // @synthesize hourLab=_hourLab;
@property(retain, nonatomic) UITextField *minTextField; // @synthesize minTextField=_minTextField;
@property(retain, nonatomic) UITextField *hourTextField; // @synthesize hourTextField=_hourTextField;
@property(retain, nonatomic) id <SFCarOutCheckCell2Delegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)textFieldDidChanged:(id)arg1;
- (void)confinfomation:(id)arg1 indexPath:(id)arg2 dataArr:(id)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

