//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray;

@interface SFCalendarCollectionViewFlowLayout : UICollectionViewFlowLayout
{
    NSArray *_sectionRows;
    long long _itemWidth;
    double _height;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) long long itemWidth; // @synthesize itemWidth=_itemWidth;
@property(retain, nonatomic) NSArray *sectionRows; // @synthesize sectionRows=_sectionRows;
- (void).cxx_destruct;
- (void)prepareLayout;
- (struct CGSize)collectionViewContentSize;
- (void)setSectionInset:(struct UIEdgeInsets)arg1;
- (void)caculateContentSizeHeight;

@end

