//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFQRCodeViewControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, SFDriverRouteModel, UIButton, UITextField, UIView;
@protocol SFChangeShiftsViewControllerDelegate;

@interface SFChangeShiftsViewController : UIViewController <UITextFieldDelegate, SFQRCodeViewControllerDelegate>
{
    SFDriverRouteModel *_customTaskModel;
    SFDriverRouteModel *_driverRouteModel;
    id <SFChangeShiftsViewControllerDelegate> _delegate;
    UITextField *_currentVehicleMiles;
    UITextField *_changeDriver;
    UIView *_changeDriverView;
    UITextField *_changeVehicleMiles;
    UIView *_changeVehicleMilesView;
    UIButton *_entryBtn;
    UIView *_changeInfoBgView;
    struct CGRect _textFrame;
}

@property(retain, nonatomic) UIView *changeInfoBgView; // @synthesize changeInfoBgView=_changeInfoBgView;
@property(nonatomic) struct CGRect textFrame; // @synthesize textFrame=_textFrame;
@property(retain, nonatomic) UIButton *entryBtn; // @synthesize entryBtn=_entryBtn;
@property(retain, nonatomic) UIView *changeVehicleMilesView; // @synthesize changeVehicleMilesView=_changeVehicleMilesView;
@property(retain, nonatomic) UITextField *changeVehicleMiles; // @synthesize changeVehicleMiles=_changeVehicleMiles;
@property(retain, nonatomic) UIView *changeDriverView; // @synthesize changeDriverView=_changeDriverView;
@property(retain, nonatomic) UITextField *changeDriver; // @synthesize changeDriver=_changeDriver;
@property(retain, nonatomic) UITextField *currentVehicleMiles; // @synthesize currentVehicleMiles=_currentVehicleMiles;
@property(nonatomic) __weak id <SFChangeShiftsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SFDriverRouteModel *driverRouteModel; // @synthesize driverRouteModel=_driverRouteModel;
@property(retain, nonatomic) SFDriverRouteModel *customTaskModel; // @synthesize customTaskModel=_customTaskModel;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)changeShiftsFromServer;
- (void)enterBtnAction;
- (void)didOutputMetadataObject:(id)arg1;
- (void)driverBtnAction;
- (void)changeShiftsInfo:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)getInfoBackView;
- (void)tapAction;
- (void)initViews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

