//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSArray, NSString;
@protocol Optional, SFCheckRecordItemModel;

@interface SFCheckRecordModel : JSONModel
{
    _Bool _isNormal;
    NSString<Optional> *_checkId;
    NSString<Optional> *_vehicleCode;
    NSString<Optional> *_userCode;
    NSString<Optional> *_checkType;
    NSString<Optional> *_checkTime;
    NSString<Optional> *_timeSpan;
    NSString<Optional> *_taskId;
    NSString<Optional> *_barcode;
    NSString<Optional> *_coolMachineWorkTime;
    NSString<Optional> *_relativeId;
    NSString<Optional> *_operatteTime;
    NSString<Optional> *_isSfTask;
    NSArray<SFCheckRecordItemModel> *_checkItemList;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSArray<SFCheckRecordItemModel> *checkItemList; // @synthesize checkItemList=_checkItemList;
@property(copy, nonatomic) NSString<Optional> *isSfTask; // @synthesize isSfTask=_isSfTask;
@property(nonatomic) _Bool isNormal; // @synthesize isNormal=_isNormal;
@property(copy, nonatomic) NSString<Optional> *operatteTime; // @synthesize operatteTime=_operatteTime;
@property(copy, nonatomic) NSString<Optional> *relativeId; // @synthesize relativeId=_relativeId;
@property(copy, nonatomic) NSString<Optional> *coolMachineWorkTime; // @synthesize coolMachineWorkTime=_coolMachineWorkTime;
@property(copy, nonatomic) NSString<Optional> *barcode; // @synthesize barcode=_barcode;
@property(copy, nonatomic) NSString<Optional> *taskId; // @synthesize taskId=_taskId;
@property(copy, nonatomic) NSString<Optional> *timeSpan; // @synthesize timeSpan=_timeSpan;
@property(copy, nonatomic) NSString<Optional> *checkTime; // @synthesize checkTime=_checkTime;
@property(copy, nonatomic) NSString<Optional> *checkType; // @synthesize checkType=_checkType;
@property(copy, nonatomic) NSString<Optional> *userCode; // @synthesize userCode=_userCode;
@property(copy, nonatomic) NSString<Optional> *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(copy, nonatomic) NSString<Optional> *checkId; // @synthesize checkId=_checkId;
- (void).cxx_destruct;

@end

