//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFChangeCarModel : JSONModel
{
    NSString *_changeAreaCode;
    NSString *_changeCarSign;
    NSString *_changeDesc;
    NSString *_changeMiles;
    NSString *_changeReason;
    NSString *_changeVehicle;
    NSString *_currentMiles;
    NSString *_currentRoadFee;
    NSString *_isNormalChange;
    NSString *_changeCheckStatus;
    NSString *_operateTime;
    NSString *_changeAddress;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *changeAddress; // @synthesize changeAddress=_changeAddress;
@property(retain, nonatomic) NSString *operateTime; // @synthesize operateTime=_operateTime;
@property(retain, nonatomic) NSString *changeCheckStatus; // @synthesize changeCheckStatus=_changeCheckStatus;
@property(retain, nonatomic) NSString *isNormalChange; // @synthesize isNormalChange=_isNormalChange;
@property(retain, nonatomic) NSString *currentRoadFee; // @synthesize currentRoadFee=_currentRoadFee;
@property(retain, nonatomic) NSString *currentMiles; // @synthesize currentMiles=_currentMiles;
@property(retain, nonatomic) NSString *changeVehicle; // @synthesize changeVehicle=_changeVehicle;
@property(retain, nonatomic) NSString *changeReason; // @synthesize changeReason=_changeReason;
@property(retain, nonatomic) NSString *changeMiles; // @synthesize changeMiles=_changeMiles;
@property(retain, nonatomic) NSString *changeDesc; // @synthesize changeDesc=_changeDesc;
@property(retain, nonatomic) NSString *changeCarSign; // @synthesize changeCarSign=_changeCarSign;
@property(retain, nonatomic) NSString *changeAreaCode; // @synthesize changeAreaCode=_changeAreaCode;
- (void).cxx_destruct;

@end

