//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SFChooseRegionModel : NSObject
{
    NSString *_regionTitle;
    NSString *_regionId;
    NSString *_regionStr;
    NSString *_prefixStr;
    long long _maxLength;
}

@property(nonatomic) long long maxLength; // @synthesize maxLength=_maxLength;
@property(copy, nonatomic) NSString *prefixStr; // @synthesize prefixStr=_prefixStr;
@property(copy, nonatomic) NSString *regionStr; // @synthesize regionStr=_regionStr;
@property(copy, nonatomic) NSString *regionId; // @synthesize regionId=_regionId;
@property(copy, nonatomic) NSString *regionTitle; // @synthesize regionTitle=_regionTitle;
- (void).cxx_destruct;
- (id)initWithRegionregionTitle:(id)arg1 regionId:(id)arg2 regionStr:(id)arg3 prefixStr:(id)arg4 maxLength:(long long)arg5;

@end

