//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface SFChangeCarAuditView : UIView
{
    NSString *_str;
    int _change;
    NSString *_carNum;
    NSString *_locationStr;
}

@property(retain, nonatomic) NSString *locationStr; // @synthesize locationStr=_locationStr;
@property(retain, nonatomic) NSString *carNum; // @synthesize carNum=_carNum;
@property(nonatomic) int change; // @synthesize change=_change;
- (void).cxx_destruct;
- (id)appRootViewController;
- (void)locationBtnAction;
- (void)addLocationBtn:(id)arg1;
- (void)setupUI:(struct CGSize)arg1;
- (struct CGSize)calculateOfStrHeight:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andChangeType:(int)arg2 carNum:(id)arg3;

@end

