//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFChangeShiftsModel : JSONModel
{
    NSString *_changeMiles;
    NSString *_currentEmpCode;
    NSString *_oldEmpCode;
    NSString *_operateTime;
    NSString *_taskId;
    NSString *_taskSerial;
    NSString *_driverName;
    NSString *_coplitName;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *coplitName; // @synthesize coplitName=_coplitName;
@property(retain, nonatomic) NSString *driverName; // @synthesize driverName=_driverName;
@property(retain, nonatomic) NSString *taskSerial; // @synthesize taskSerial=_taskSerial;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
@property(retain, nonatomic) NSString *operateTime; // @synthesize operateTime=_operateTime;
@property(retain, nonatomic) NSString *oldEmpCode; // @synthesize oldEmpCode=_oldEmpCode;
@property(retain, nonatomic) NSString *currentEmpCode; // @synthesize currentEmpCode=_currentEmpCode;
@property(retain, nonatomic) NSString *changeMiles; // @synthesize changeMiles=_changeMiles;
- (void).cxx_destruct;

@end

