//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIImage, UIImageView, UIView;
@protocol ClipViewControllerDelegate;

@interface SFClipViewController : UIViewController <UIGestureRecognizerDelegate>
{
    UIImageView *_imageView;
    UIImage *_image;
    UIView *_overView;
    struct CGAffineTransform _oldTransform;
    int _clipType;
    double _scaleRation;
    double _radius;
    id <ClipViewControllerDelegate> _delegate;
    struct CGRect _circularFrame;
    struct CGRect _OriginalFrame;
    struct CGRect _currentFrame;
}

@property(retain, nonatomic) id <ClipViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int clipType; // @synthesize clipType=_clipType;
@property(nonatomic) struct CGRect currentFrame; // @synthesize currentFrame=_currentFrame;
@property(nonatomic) struct CGRect OriginalFrame; // @synthesize OriginalFrame=_OriginalFrame;
@property(nonatomic) struct CGRect circularFrame; // @synthesize circularFrame=_circularFrame;
@property(nonatomic) double radius; // @synthesize radius=_radius;
@property(nonatomic) double scaleRation; // @synthesize scaleRation=_scaleRation;
- (void).cxx_destruct;
- (void)nextBtnAction:(id)arg1;
- (void)initView;
- (id)CircularClipImage:(id)arg1;
- (id)getSmallImage;
- (id)fixOrientation:(id)arg1;
- (void)completeBtnAction:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)handlePinGesture:(id)arg1;
- (void)addAllGesture;
- (void)MakeImageViewFrameAdaptClipFrame;
- (void)drawClipPath:(int)arg1;
- (void)CreatUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

