//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;
@protocol Optional;

@interface SFContactModel : JSONModel
{
    NSString<Optional> *_username;
    NSString<Optional> *_mobilephone;
}

@property(retain, nonatomic) NSString<Optional> *mobilephone; // @synthesize mobilephone=_mobilephone;
@property(retain, nonatomic) NSString<Optional> *username; // @synthesize username=_username;
- (void).cxx_destruct;

@end

