//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SFContactObject : NSObject
{
    NSString *_addressType;
    NSString *_address;
    NSString *_contactName;
    NSString *_cellPhone;
    NSString *_phone;
}

@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSString *cellPhone; // @synthesize cellPhone=_cellPhone;
@property(retain, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *addressType; // @synthesize addressType=_addressType;
- (void).cxx_destruct;
- (double)getAddressHeight;

@end

