//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SFCountdownTimer : NSObject
{
    _Bool _cancel;
    NSObject<OS_dispatch_source> *_gtimer;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (double)nowTime;
+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *gtimer; // @synthesize gtimer=_gtimer;
@property(nonatomic) _Bool cancel; // @synthesize cancel=_cancel;
- (void).cxx_destruct;
- (void)activityCountDownWithSec:(double)arg1 remainSec:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)numberOfSecond:(long long)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)oneSecondCallBack:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)timerWithTimeInterval:(double)arg1 selBlock:(CDUnknownBlockType)arg2;
- (void)countDownNormalWithSec:(double)arg1 remainSec:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)countDownWithSec:(double)arg1 remainSec:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;

@end

