//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFCustomTaskActualModel : JSONModel
{
    NSString *_taskLogId;
    NSString *_serial;
    NSString *_address;
    NSString *_createdDateTime;
    NSString *_taskOperateType;
    NSString *_cityName;
    NSString *_latitude;
    NSString *_longitude;
    NSString *_logSerial;
    NSString *_scannedCode;
    NSString *_taskType;
    NSString *_username;
    NSString *_miles;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *miles; // @synthesize miles=_miles;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *taskType; // @synthesize taskType=_taskType;
@property(retain, nonatomic) NSString *scannedCode; // @synthesize scannedCode=_scannedCode;
@property(retain, nonatomic) NSString *logSerial; // @synthesize logSerial=_logSerial;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(retain, nonatomic) NSString *taskOperateType; // @synthesize taskOperateType=_taskOperateType;
@property(retain, nonatomic) NSString *createdDateTime; // @synthesize createdDateTime=_createdDateTime;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *serial; // @synthesize serial=_serial;
@property(retain, nonatomic) NSString *taskLogId; // @synthesize taskLogId=_taskLogId;
- (void).cxx_destruct;

@end

