//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFQRCodeViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSString, UIRefreshControl, UIView, WKWebView;

@interface SFCustomWebViewController : UIViewController <WKUIDelegate, WKNavigationDelegate, WKScriptMessageHandler, UINavigationControllerDelegate, SFQRCodeViewControllerDelegate>
{
    _Bool _canDownRefresh;
    NSString *_urlString;
    NSString *_jsString;
    WKWebView *_wkWebView;
    UIRefreshControl *_refreshControl;
    UIView *_statusView;
}

@property(retain, nonatomic) UIView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) WKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
@property(nonatomic) _Bool canDownRefresh; // @synthesize canDownRefresh=_canDownRefresh;
@property(copy, nonatomic) NSString *jsString; // @synthesize jsString=_jsString;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
- (void).cxx_destruct;
- (void)dealloc;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)saveMaintenanceTaskVehicle:(id)arg1;
- (void)didOutputMetadataObject:(id)arg1;
- (void)scanVehilceNumber;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)webViewDidClose:(id)arg1;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)wkWebViewReload;
- (void)loadRequest;
- (void)loadHtmlRequest;
- (void)setupUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

