//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SFCustomizeTaskModel, UIButton, UIImageView, UILabel;
@protocol SFCustomTaskViewCellDelegate;

@interface SFCustomTaskViewCell : UITableViewCell
{
    UILabel *_taskType;
    UIButton *_editorBtn;
    UIButton *_deleteBtn;
    UILabel *_startTimeAndDeptCode;
    UILabel *_startAddress;
    UILabel *_endTimeAndDeptCode;
    UILabel *_endAddress;
    UIImageView *_stampImageView;
    SFCustomizeTaskModel *_customModel;
    id <SFCustomTaskViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <SFCustomTaskViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)editorBtnAction:(id)arg1;
- (void)deleteAction:(id)arg1;
- (void)setLabelTextWithLabel:(id)arg1 text:(id)arg2;
- (void)confingWithCustomTaskModel:(id)arg1;
- (id)getCornerLabel;
- (void)stepUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

