//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFCustomizeTaskModel : JSONModel
{
    _Bool _isCopilot;
    NSString *_templateId;
    NSString *_miles;
    NSString *_taskType;
    NSString *_taskTypeStr;
    NSString *_originCode;
    NSString *_originAddress;
    double _originAddressHeight;
    NSString *_destinationCode;
    NSString *_destinationAddress;
    double _destinationAddressHeight;
    NSString *_serial;
    NSString *_hours;
    NSString *_minutes;
    NSString *_createdDateTime;
    NSString *_latitude;
    NSString *_longitude;
    NSString *_userName;
    NSString *_runningTime;
    NSString *_taskRemakes;
    NSString *_billNumber;
    NSString *_deptCode;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *deptCode; // @synthesize deptCode=_deptCode;
@property(retain, nonatomic) NSString *billNumber; // @synthesize billNumber=_billNumber;
@property(retain, nonatomic) NSString *taskRemakes; // @synthesize taskRemakes=_taskRemakes;
@property(retain, nonatomic) NSString *runningTime; // @synthesize runningTime=_runningTime;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *createdDateTime; // @synthesize createdDateTime=_createdDateTime;
@property(retain, nonatomic) NSString *minutes; // @synthesize minutes=_minutes;
@property(retain, nonatomic) NSString *hours; // @synthesize hours=_hours;
@property(retain, nonatomic) NSString *serial; // @synthesize serial=_serial;
@property(nonatomic) double destinationAddressHeight; // @synthesize destinationAddressHeight=_destinationAddressHeight;
@property(retain, nonatomic) NSString *destinationAddress; // @synthesize destinationAddress=_destinationAddress;
@property(retain, nonatomic) NSString *destinationCode; // @synthesize destinationCode=_destinationCode;
@property(nonatomic) double originAddressHeight; // @synthesize originAddressHeight=_originAddressHeight;
@property(retain, nonatomic) NSString *originAddress; // @synthesize originAddress=_originAddress;
@property(retain, nonatomic) NSString *originCode; // @synthesize originCode=_originCode;
@property(nonatomic) _Bool isCopilot; // @synthesize isCopilot=_isCopilot;
@property(retain, nonatomic) NSString *taskTypeStr; // @synthesize taskTypeStr=_taskTypeStr;
@property(retain, nonatomic) NSString *taskType; // @synthesize taskType=_taskType;
@property(retain, nonatomic) NSString *miles; // @synthesize miles=_miles;
@property(retain, nonatomic) NSString *templateId; // @synthesize templateId=_templateId;
- (void).cxx_destruct;

@end

