//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, NSTimer, UILabel;

@interface SFCustomDriverTaskViewCell : UITableViewCell
{
    UILabel *_customTaskLabel;
    UILabel *_taskType;
    UILabel *_status;
    UILabel *_startTimeAndDeptCode;
    UILabel *_startAddress;
    UILabel *_endTimeAndDeptCode;
    UILabel *_endAddress;
    NSTimer *_timer;
    NSString *_startTime;
}

- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setLabelTextWithLabel:(id)arg1 text:(id)arg2;
- (void)confingWithPendingTaskModel:(id)arg1;
- (id)getCornerLabel;
- (void)stepUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;

@end

