//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabase, FMDatabaseQueue;

@interface SFDataBase : NSObject
{
    FMDatabase *db;
    FMDatabaseQueue *dbQueue;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (void)dropAndCreateT_app_messageFile;
- (void)upgradeTableT_app_message;
- (void)insertDefaultDataOn_t_app_version:(long long)arg1;
- (void)createTable_t_app_version;
- (void)upgradeTable:(long long)arg1 ToVersion:(long long)arg2;
- (_Bool)updateT_app_version:(long long)arg1;
- (void)checkDatabaseVersion:(id)arg1;
- (_Bool)createIndex_t_app_trajectory_index;
- (_Bool)createT_app_trajectoryFile;
- (_Bool)createT_app_uploadedFile;
- (_Bool)createT_app_messageFile;
- (_Bool)createDatabase:(id)arg1;
- (void)initialized;
- (long long)getBuildTime;
- (id)dataFilePath;
- (id)init;
- (id)db;
- (id)queue;

@end

