//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseRefreshVC.h"

@class SFMyFeedbackModel;

@interface SFDisposingVC : SFBaseRefreshVC
{
    SFMyFeedbackModel *_model;
}

@property(retain, nonatomic) SFMyFeedbackModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)reloadDataTableView;
- (void)queryFeedbackListData:(long long)arg1;
- (void)loadNewData;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)createUI;
- (void)viewDidLoad;

@end

