//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseCell.h"

@class UIImageView, UILabel;

@interface SFDischargePortCell : SFBaseCell
{
    UIImageView *_portIcon;
    UILabel *_desLab;
}

+ (double)cellHeight;
@property(retain, nonatomic) UILabel *desLab; // @synthesize desLab=_desLab;
@property(retain, nonatomic) UIImageView *portIcon; // @synthesize portIcon=_portIcon;
- (void).cxx_destruct;
- (void)cellLoadData:(id)arg1;
- (void)stepUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

