//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSIndexPath, SFDragCellTableView;

@protocol SFDragCellTableViewDelegate <UITableViewDelegate>
- (void)tableView:(SFDragCellTableView *)arg1 newArrayDataForDataSource:(NSArray *)arg2;

@optional
- (void)cellDidEndMovingInTableView:(SFDragCellTableView *)arg1;
- (void)cellIsMovingInTableView:(SFDragCellTableView *)arg1;
- (void)tableView:(SFDragCellTableView *)arg1 cellReadyToMoveAtIndexPath:(NSIndexPath *)arg2;
@end

