//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@class CADisplayLink, NSIndexPath, UIView;
@protocol SFDragCellTableViewDataSource, SFDragCellTableViewDelegate;

@interface SFDragCellTableView : UITableView
{
    int _autoScrollDirection;
    UIView *_snapshot;
    NSIndexPath *_originalIndexPath;
    NSIndexPath *_relocatedIndexPath;
    CADisplayLink *_autoScrollTimer;
    struct CGPoint _fingerLocation;
}

@property(nonatomic) int autoScrollDirection; // @synthesize autoScrollDirection=_autoScrollDirection;
@property(nonatomic) struct CGPoint fingerLocation; // @synthesize fingerLocation=_fingerLocation;
@property(retain, nonatomic) CADisplayLink *autoScrollTimer; // @synthesize autoScrollTimer=_autoScrollTimer;
@property(retain, nonatomic) NSIndexPath *relocatedIndexPath; // @synthesize relocatedIndexPath=_relocatedIndexPath;
@property(retain, nonatomic) NSIndexPath *originalIndexPath; // @synthesize originalIndexPath=_originalIndexPath;
@property(nonatomic) __weak UIView *snapshot; // @synthesize snapshot=_snapshot;
- (void).cxx_destruct;
- (void)startAutoScroll;
- (_Bool)checkIfSnapshotMeetsEdge;
- (void)moveObjectInMutableArray:(id)arg1 fromIndex:(long long)arg2 toIndex:(long long)arg3;
- (id)customSnapshotFromView:(id)arg1;
- (void)didEndDraging;
- (void)cellRelocatedToNewIndexPath:(id)arg1;
- (void)cellSelectedAtIndexPath:(id)arg1;
- (_Bool)nestedArrayCheck:(id)arg1;
- (void)updateDataSource;
- (void)stopAutoScrollTimer;
- (void)startAutoScrollTimer;
- (void)longPressGestureRecognized:(id)arg1;
- (id)init;

// Remaining properties
@property(nonatomic) id <SFDragCellTableViewDataSource> dataSource; // @dynamic dataSource;
@property(nonatomic) id <SFDragCellTableViewDelegate> delegate; // @dynamic delegate;

@end

