//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseVC.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFMineHeadView, SFTempDriverInfoModel, UITableView;

@interface SFDriverMineViewController : SFBaseVC <UITableViewDelegate, UITableViewDataSource, UINavigationControllerDelegate>
{
    SFMineHeadView *_headView;
    UITableView *_tableView;
    NSMutableArray *_dataArr;
    SFTempDriverInfoModel *_model;
}

@property(retain, nonatomic) SFTempDriverInfoModel *model; // @synthesize model=_model;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SFMineHeadView *headView; // @synthesize headView=_headView;
- (void).cxx_destruct;
- (void)updateDriverInfoStatus;
- (void)checkInfoWithHasModel:(CDUnknownBlockType)arg1 emptyModel:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getDataSources;
- (void)pushDifferentApplyBusinessVC;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)creatUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

