//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseCell.h"

@class UIButton, UIImageView, UILabel;

@interface SFEmptyCell : SFBaseCell
{
    UIImageView *icon;
    UILabel *_contentLabel;
    UIButton *_emptyBt;
}

+ (double)buttonCellHeight;
+ (double)cellHeight;
@property(retain, nonatomic) UIButton *emptyBt; // @synthesize emptyBt=_emptyBt;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (void)contentNumberOfLines;
- (void)setAdjustOrginY:(double)arg1;
- (id)initImageName:(id)arg1 content:(id)arg2 buttonStr:(id)arg3 target:(id)arg4 action:(SEL)arg5;
- (id)initImageName:(id)arg1 content:(id)arg2;

@end

