//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFChooseRegionViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UITextField;

@interface SFEnterTelViewController : UIViewController <UITextFieldDelegate, SFChooseRegionViewDelegate>
{
    int _type;
    NSString *_identification;
    UIButton *_nextBtn;
    UITextField *_telTextF;
    UILabel *_regionTypeLab;
    UIButton *_selectRegionBtn;
    long long _regionType;
}

@property(nonatomic) long long regionType; // @synthesize regionType=_regionType;
@property(retain, nonatomic) UIButton *selectRegionBtn; // @synthesize selectRegionBtn=_selectRegionBtn;
@property(retain, nonatomic) UILabel *regionTypeLab; // @synthesize regionTypeLab=_regionTypeLab;
@property(retain, nonatomic) UITextField *telTextF; // @synthesize telTextF=_telTextF;
@property(retain, nonatomic) UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(copy, nonatomic) NSString *identification; // @synthesize identification=_identification;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)enterWithRegion:(id)arg1;
- (void)selectRegionBtnClick:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)textFiedTextDidChanged:(id)arg1;
- (void)pushNextPage:(int)arg1;
- (void)nextButtonClick;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)queryDriverTypeFromServer;
- (void)createUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

