//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFLocationServiceDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITextField;

@interface SFEnterThirdInfoVController : UIViewController <SFLocationServiceDelegate>
{
    NSMutableArray *_allImageArr;
    UILabel *_selectLabel;
    UITextField *_detailTex;
    NSMutableArray *_imageStrArr;
    NSMutableArray *_cityArr;
    NSString *_cityCode;
}

@property(retain, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(retain, nonatomic) NSMutableArray *cityArr; // @synthesize cityArr=_cityArr;
@property(retain, nonatomic) NSMutableArray *imageStrArr; // @synthesize imageStrArr=_imageStrArr;
@property(retain, nonatomic) UITextField *detailTex; // @synthesize detailTex=_detailTex;
@property(retain, nonatomic) UILabel *selectLabel; // @synthesize selectLabel=_selectLabel;
@property(retain, nonatomic) NSMutableArray *allImageArr; // @synthesize allImageArr=_allImageArr;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)sendInfomationRequest:(id)arg1;
- (void)uploadImage;
- (void)getCityDataWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)ph_didFailToLocateUserWithError:(id)arg1;
- (void)sf_didUpdateUserLocation:(id)arg1;
- (void)initLocationService;
- (void)myAdress;
- (void)createSelectCityUI;
- (void)mycityAction;
- (void)sendInfo;
- (void)createUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

