//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, UIImageView, UIScrollView;

@interface SFEnterSecondInfoVController : UIViewController
{
    NSMutableArray *_imageArr;
    UIScrollView *_bgScrollView;
    UIImageView *_driverCardOfFront;
    UIImageView *_driverCardOfContrary;
    UIImageView *_travelCardOfFront;
    UIImageView *_travelCardOfContrary;
    UIImageView *_healthCardOfFront;
    UIImageView *_healthCardOfContrary;
    NSMutableArray *_driverImageArr;
    NSMutableArray *_travelImageArr;
    NSMutableArray *_healthImageArr;
}

@property(retain, nonatomic) NSMutableArray *healthImageArr; // @synthesize healthImageArr=_healthImageArr;
@property(retain, nonatomic) NSMutableArray *travelImageArr; // @synthesize travelImageArr=_travelImageArr;
@property(retain, nonatomic) NSMutableArray *driverImageArr; // @synthesize driverImageArr=_driverImageArr;
@property(retain, nonatomic) UIImageView *healthCardOfContrary; // @synthesize healthCardOfContrary=_healthCardOfContrary;
@property(retain, nonatomic) UIImageView *healthCardOfFront; // @synthesize healthCardOfFront=_healthCardOfFront;
@property(retain, nonatomic) UIImageView *travelCardOfContrary; // @synthesize travelCardOfContrary=_travelCardOfContrary;
@property(retain, nonatomic) UIImageView *travelCardOfFront; // @synthesize travelCardOfFront=_travelCardOfFront;
@property(retain, nonatomic) UIImageView *driverCardOfContrary; // @synthesize driverCardOfContrary=_driverCardOfContrary;
@property(retain, nonatomic) UIImageView *driverCardOfFront; // @synthesize driverCardOfFront=_driverCardOfFront;
@property(retain, nonatomic) UIScrollView *bgScrollView; // @synthesize bgScrollView=_bgScrollView;
@property(retain, nonatomic) NSMutableArray *imageArr; // @synthesize imageArr=_imageArr;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)healthCardContraryAction:(id)arg1;
- (void)deleteFImage:(id)arg1;
- (void)healthCardFrontAction:(id)arg1;
- (void)deleteEImage:(id)arg1;
- (void)travelCardContraryBction:(id)arg1;
- (void)deleteDImage:(id)arg1;
- (void)travelCardContraryAction:(id)arg1;
- (void)deleteCImage:(id)arg1;
- (void)driverCardContraryAction:(id)arg1;
- (void)deleteBImage:(id)arg1;
- (void)driverCardFrontAction:(id)arg1;
- (void)deleteAImage:(id)arg1;
- (void)nextThirdPage;
- (void)createUI;
- (void)viewDidLoad;

@end

