//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFChooseProvinceControllerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UICollectionView, UILabel, UITextField;
@protocol SFEnterVehicleCodeControllerDelegate;

@interface SFEnterVehicleCodeController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, UITextFieldDelegate, SFChooseProvinceControllerDelegate>
{
    _Bool _isOther;
    int _startTaskType;
    id <SFEnterVehicleCodeControllerDelegate> _delegate;
    NSString *_currentVehicleNumber;
    UILabel *_provinceLabel;
    UITextField *_vehicleNum;
    UILabel *_currentVehicle;
    UIButton *_enterBtn;
    UICollectionView *_myCollectionView;
    NSMutableArray *_dataSource;
}

@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UICollectionView *myCollectionView; // @synthesize myCollectionView=_myCollectionView;
@property(retain, nonatomic) UIButton *enterBtn; // @synthesize enterBtn=_enterBtn;
@property(retain, nonatomic) UILabel *currentVehicle; // @synthesize currentVehicle=_currentVehicle;
@property(retain, nonatomic) UITextField *vehicleNum; // @synthesize vehicleNum=_vehicleNum;
@property(retain, nonatomic) UILabel *provinceLabel; // @synthesize provinceLabel=_provinceLabel;
@property(nonatomic) _Bool isOther; // @synthesize isOther=_isOther;
@property(nonatomic) int startTaskType; // @synthesize startTaskType=_startTaskType;
@property(retain, nonatomic) NSString *currentVehicleNumber; // @synthesize currentVehicleNumber=_currentVehicleNumber;
@property(nonatomic) __weak id <SFEnterVehicleCodeControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)setVehicleNumWithVehicleCode:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)vehicleNumChange:(id)arg1;
- (void)enterOtherVehicleNumber:(id)arg1;
- (void)enterBtnAction:(id)arg1;
- (void)currentVehicleTapAction;
- (void)chooseProvince:(id)arg1;
- (void)provinceTapAction;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)tapAction;
- (id)getTitleViewWithTitle:(id)arg1 textColor:(id)arg2 font:(id)arg3;
- (void)initViews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

