//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UITextField;

@interface SFEnterIDCardController : UIViewController <UITextFieldDelegate>
{
    int _type;
    NSString *_validateCode;
    NSString *_password;
    NSString *_mobilePhone;
    UIButton *_nextBtn;
    UITextField *_idCardTextF;
}

@property(retain, nonatomic) UITextField *idCardTextF; // @synthesize idCardTextF=_idCardTextF;
@property(retain, nonatomic) UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *validateCode; // @synthesize validateCode=_validateCode;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)checkInfo;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)textFieldDidChanged:(id)arg1;
- (void)nextButtonClick:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)userinforealNameApproveWithRequestComplete:(CDUnknownBlockType)arg1;
- (void)registryForEnterprise;
- (void)addTitleUI;
- (void)createUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

