//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFDriverRouteModel, UIButton, UILabel, UITableView;
@protocol SFExecutingViewDelegate;

@interface SFExecutingView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UILabel *_isStop;
    UILabel *_driver;
    UILabel *_vehicleNum;
    UILabel *_taskIdLabel;
    UILabel *_deptCodeLabel;
    UILabel *_taskIdTitle;
    UILabel *_deptCodeTitle;
    id <SFExecutingViewDelegate> _delegate;
    UIButton *_detailTaskBtn;
    SFDriverRouteModel *_driverRouteModel;
    NSMutableArray *_planRouteArray;
    NSMutableArray *_realtiyRouteArray;
    NSMutableArray *_dataSourceArray;
    UITableView *_myTableView;
}

@property(retain, nonatomic) UITableView *myTableView; // @synthesize myTableView=_myTableView;
@property(retain, nonatomic) NSMutableArray *dataSourceArray; // @synthesize dataSourceArray=_dataSourceArray;
@property(retain, nonatomic) NSMutableArray *realtiyRouteArray; // @synthesize realtiyRouteArray=_realtiyRouteArray;
@property(retain, nonatomic) NSMutableArray *planRouteArray; // @synthesize planRouteArray=_planRouteArray;
@property(retain, nonatomic) SFDriverRouteModel *driverRouteModel; // @synthesize driverRouteModel=_driverRouteModel;
@property(retain, nonatomic) UIButton *detailTaskBtn; // @synthesize detailTaskBtn=_detailTaskBtn;
@property(nonatomic) __weak id <SFExecutingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)detailTaskBtnAction:(id)arg1;
- (id)getCornerLabel;
- (void)setLabelTextWithLabel:(id)arg1 text:(id)arg2;
- (id)getTimeConsuming:(id)arg1 endTime:(id)arg2;
- (void)setViewsWithCustomTaskModel:(id)arg1;
- (void)setViewsWithTaskModel:(id)arg1;
- (void)confingWithPendingTaskModel:(id)arg1;
- (void)stepUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

