//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSString, SFRegionModel, UILabel, UIViewController;

@interface SFFeedbackHeaderView : UIView
{
    UIViewController *_superVC;
    NSMutableArray *_imageArrData;
    NSString *_contentData;
    UILabel *_contentLab;
    SFRegionModel *_model;
}

@property(retain, nonatomic) SFRegionModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(copy, nonatomic) NSString *contentData; // @synthesize contentData=_contentData;
@property(retain, nonatomic) NSMutableArray *imageArrData; // @synthesize imageArrData=_imageArrData;
@property(nonatomic) __weak UIViewController *superVC; // @synthesize superVC=_superVC;
- (void).cxx_destruct;
- (void)showImageWithArray:(id)arg1 index:(long long)arg2;
- (void)imageTapAction:(id)arg1;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1 andTitle:(id)arg2 imageArr:(id)arg3 regionModel:(id)arg4;

@end

