//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface SFGpsPathModel : NSObject
{
    NSString *_gpsPathID;
    NSString *_validPathList;
    NSString *_dbTm;
    NSString *_insertTime;
    NSMutableArray *_validPathArray;
}

+ (void)saveObjectsToDatabaseAsync:(id)arg1 withComplection:(CDUnknownBlockType)arg2;
+ (id)fetchAllObjectFromDatabase;
+ (id)fetchObjectFromDatabaseWithGpsPathID:(id)arg1;
@property(retain, nonatomic) NSMutableArray *validPathArray; // @synthesize validPathArray=_validPathArray;
@property(retain, nonatomic) NSString *insertTime; // @synthesize insertTime=_insertTime;
@property(retain, nonatomic) NSString *dbTm; // @synthesize dbTm=_dbTm;
@property(retain, nonatomic) NSString *validPathList; // @synthesize validPathList=_validPathList;
@property(retain, nonatomic) NSString *gpsPathID; // @synthesize gpsPathID=_gpsPathID;
- (void).cxx_destruct;
- (_Bool)deleteFromDatabase;
- (_Bool)saveOrInsertToDatabase;
- (id)init;

@end

