//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SFBidDetailPackageLineView, SFImgTitleView, SFToCBidModel, SFToCBidRemarkView, SFToCProgressView, UIButton, UIImageView, UILabel, UIView;

@interface SFGroupDetailCell : UITableViewCell
{
    _Bool _showMore;
    CDUnknownBlockType _block;
    CDUnknownBlockType _shareActionBlock;
    UIView *_bgView;
    UIImageView *_packageImgView;
    UILabel *_packageImgLabel;
    SFImgTitleView *_dateView;
    UIButton *_shareBut;
    SFBidDetailPackageLineView *_packageLineView;
    UIButton *_packageBut;
    SFToCProgressView *_progressView;
    SFToCBidRemarkView *_remarkView;
    SFToCBidModel *_model;
}

@property(nonatomic) _Bool showMore; // @synthesize showMore=_showMore;
@property(retain, nonatomic) SFToCBidModel *model; // @synthesize model=_model;
@property(retain, nonatomic) SFToCBidRemarkView *remarkView; // @synthesize remarkView=_remarkView;
@property(retain, nonatomic) SFToCProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIButton *packageBut; // @synthesize packageBut=_packageBut;
@property(retain, nonatomic) SFBidDetailPackageLineView *packageLineView; // @synthesize packageLineView=_packageLineView;
@property(retain, nonatomic) UIButton *shareBut; // @synthesize shareBut=_shareBut;
@property(retain, nonatomic) SFImgTitleView *dateView; // @synthesize dateView=_dateView;
@property(retain, nonatomic) UILabel *packageImgLabel; // @synthesize packageImgLabel=_packageImgLabel;
@property(retain, nonatomic) UIImageView *packageImgView; // @synthesize packageImgView=_packageImgView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType shareActionBlock; // @synthesize shareActionBlock=_shareActionBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)shareAction;
- (void)updateShowMoreStatus;
- (void)setBidModel:(id)arg1 showMore:(_Bool)arg2;
- (void)layoutSubviews;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

