//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSUserDefaults;

@interface SFHelper : NSObject
{
    _Bool _isVoicePlay;
    _Bool _isBackgroundVoicePlay;
    _Bool _isMapNavigation;
    _Bool _isGPSVoicePlay;
    _Bool _isAWayVoicePlay;
    _Bool _isGPSAbnormalVoicePlay;
    NSUserDefaults *_userDefaults;
    NSString *_lasttimeKey;
}

+ (id)sf_kCheckNil:(id)arg1;
+ (id)getNowDateFromatAnDate:(id)arg1;
+ (long long)sfMonthsFromDate:(id)arg1 toDate:(id)arg2;
+ (long long)monthFromDate:(id)arg1 toDate:(id)arg2;
+ (id)timeTransform:(id)arg1 format:(id)arg2;
+ (id)getNowTimeTimestampIsSecond:(_Bool)arg1;
+ (void)ControlBeizerRect:(struct CGRect)arg1 Control:(id)arg2 corner:(unsigned long long)arg3 cornerRadii:(struct CGSize)arg4;
+ (void)viewBeizerRect:(struct CGRect)arg1 view:(id)arg2 corner:(unsigned long long)arg3 cornerRadii:(struct CGSize)arg4;
+ (id)sharedInstance;
@property(copy, nonatomic) NSString *lasttimeKey; // @synthesize lasttimeKey=_lasttimeKey;
@property(nonatomic) _Bool isGPSAbnormalVoicePlay; // @synthesize isGPSAbnormalVoicePlay=_isGPSAbnormalVoicePlay;
@property(nonatomic) _Bool isAWayVoicePlay; // @synthesize isAWayVoicePlay=_isAWayVoicePlay;
@property(nonatomic) _Bool isGPSVoicePlay; // @synthesize isGPSVoicePlay=_isGPSVoicePlay;
@property(nonatomic) _Bool isMapNavigation; // @synthesize isMapNavigation=_isMapNavigation;
@property(nonatomic) _Bool isBackgroundVoicePlay; // @synthesize isBackgroundVoicePlay=_isBackgroundVoicePlay;
@property(nonatomic) _Bool isVoicePlay; // @synthesize isVoicePlay=_isVoicePlay;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void).cxx_destruct;
- (void)saveModifyPasswordDate:(id)arg1;
- (_Bool)needRequestModifyPassword;
- (id)StringTODate:(id)arg1;
- (long long)timeIntervalFromNum:(id)arg1 toNum:(id)arg2;
- (id)interceptTimeStampFromStr:(id)arg1 formatString:(id)arg2;
- (_Bool)isFriday;
- (id)sortDescriptorWithKey:(id)arg1 array:(id)arg2 isASE:(_Bool)arg3;
- (void)initialize;
- (id)init;

@end

