//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableDictionary, NSNumber, NSString;

@interface SFInforModel : JSONModel
{
    NSString *_userName;
    NSString *_userID;
    NSString *_bizId;
    NSString *_type;
    NSString *_deptCode;
    NSString *_message;
    NSString *_transactionNumber;
    NSString *_createTime;
    NSNumber *_messageType;
    NSNumber *_isRead;
    NSNumber *_driver;
    NSString *_title;
    NSString *_subtitle;
    NSNumber *_messageIDKey;
    NSNumber *_needConfirmKey;
    NSString *_url;
    NSString *_vehicleNumber;
    NSString *_bookId;
    NSMutableDictionary *_dataDict;
    NSString *_uuid;
    NSString *_longitude;
    NSString *_latitude;
    NSNumber *_cellHeight;
    NSString *_messageTime;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(copy, nonatomic) NSString *messageTime; // @synthesize messageTime=_messageTime;
@property(retain, nonatomic) NSNumber *cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSMutableDictionary *dataDict; // @synthesize dataDict=_dataDict;
@property(copy, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
@property(copy, nonatomic) NSString *vehicleNumber; // @synthesize vehicleNumber=_vehicleNumber;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSNumber *needConfirmKey; // @synthesize needConfirmKey=_needConfirmKey;
@property(retain, nonatomic) NSNumber *messageIDKey; // @synthesize messageIDKey=_messageIDKey;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *driver; // @synthesize driver=_driver;
@property(retain, nonatomic) NSNumber *isRead; // @synthesize isRead=_isRead;
@property(retain, nonatomic) NSNumber *messageType; // @synthesize messageType=_messageType;
@property(copy, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *transactionNumber; // @synthesize transactionNumber=_transactionNumber;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *deptCode; // @synthesize deptCode=_deptCode;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *bizId; // @synthesize bizId=_bizId;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

