//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SFLinePointView, SFToCLineModel, UIImageView, UILabel, UIView;

@interface SFJoinGropSelectCell : UITableViewCell
{
    SFToCLineModel *_lineModel;
    UIView *_bgView;
    SFLinePointView *_lineView;
    UILabel *_priceLabel;
    UIImageView *_imageV;
}

@property(retain, nonatomic) UIImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) SFLinePointView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SFToCLineModel *lineModel; // @synthesize lineModel=_lineModel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)setLineModel:(id)arg1 selectedSubPackNo:(id)arg2;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

