//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface SFJoinSummaryView : UIView
{
    UILabel *_vehicleCostTitle;
    UILabel *_vehicleCostValue;
    UILabel *_profileTitle;
    UILabel *_profileValue;
    UILabel *_sumTitle;
    UILabel *_sumValue;
}

@property(retain, nonatomic) UILabel *sumValue; // @synthesize sumValue=_sumValue;
@property(retain, nonatomic) UILabel *sumTitle; // @synthesize sumTitle=_sumTitle;
@property(retain, nonatomic) UILabel *profileValue; // @synthesize profileValue=_profileValue;
@property(retain, nonatomic) UILabel *profileTitle; // @synthesize profileTitle=_profileTitle;
@property(retain, nonatomic) UILabel *vehicleCostValue; // @synthesize vehicleCostValue=_vehicleCostValue;
@property(retain, nonatomic) UILabel *vehicleCostTitle; // @synthesize vehicleCostTitle=_vehicleCostTitle;
- (void).cxx_destruct;
- (void)setVehicleCost:(long long)arg1 profile:(long long)arg2;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

