//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AMapLocationManagerDelegate-Protocol.h"

@class AMapLocationManager, GPSModel, NSMutableArray, NSString, NSTimer, SFPlanRouteModel;
@protocol SFLocationServiceDelegate;

@interface SFLocationService : NSObject <AMapLocationManagerDelegate>
{
    _Bool _isstartCaging;
    _Bool _isInGpsScope;
    id <SFLocationServiceDelegate> _delegate;
    GPSModel *_gpsModel;
    NSString *_vehicleNumber;
    NSString *_customVehicleNumber;
    SFPlanRouteModel *_currentRouteModel;
    CDUnknownBlockType _completionBlock;
    AMapLocationManager *_locationManager;
    NSTimer *_timer;
    NSMutableArray *_taskModelArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *taskModelArray; // @synthesize taskModelArray=_taskModelArray;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) AMapLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) _Bool isInGpsScope; // @synthesize isInGpsScope=_isInGpsScope;
@property(retain, nonatomic) SFPlanRouteModel *currentRouteModel; // @synthesize currentRouteModel=_currentRouteModel;
@property(retain, nonatomic) NSString *customVehicleNumber; // @synthesize customVehicleNumber=_customVehicleNumber;
@property(retain, nonatomic) NSString *vehicleNumber; // @synthesize vehicleNumber=_vehicleNumber;
@property(retain, nonatomic) GPSModel *gpsModel; // @synthesize gpsModel=_gpsModel;
@property(nonatomic) _Bool isstartCaging; // @synthesize isstartCaging=_isstartCaging;
@property(nonatomic) __weak id <SFLocationServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)__responseToSel:(SEL)arg1;
- (void)__performToSel:(SEL)arg1 withObject:(id)arg2;
- (void)initCompleteBlock;
- (void)uploadCustomizeGps:(id)arg1;
- (void)uploadEntryLeaveEleFenceGps:(id)arg1 distance:(double)arg2 fenceType:(long long)arg3;
- (void)speech:(id)arg1;
- (double)checkGpsIsScopeWithGps:(id)arg1 routeModel:(id)arg2;
- (void)gatherScopeVoice:(id)arg1 taskModel:(id)arg2;
- (void)uploadGps:(id)arg1;
- (void)startLocationService;
- (void)stopCagingCustomTrack;
- (void)stopCagingTrack;
- (void)startCagingTrackWithCustomVehicle:(id)arg1;
- (void)startCagingTrack:(id)arg1;
- (void)reGeocodeAction;
- (void)cleanUpAction;
- (void)configLocationManager;
- (void)initTaskModelArrayWithPlanModelArray:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

