//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SFLocationServiceDelegate-Protocol.h"

@class NSString, SFUserLocation;

@interface SFLocationManager : NSObject <SFLocationServiceDelegate>
{
    CDUnknownBlockType _locationManagerBlock;
    SFUserLocation *_blockLocation;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SFUserLocation *blockLocation; // @synthesize blockLocation=_blockLocation;
@property(copy, nonatomic) CDUnknownBlockType locationManagerBlock; // @synthesize locationManagerBlock=_locationManagerBlock;
- (void).cxx_destruct;
- (void)ph_didFailToLocateUserWithError:(id)arg1;
- (void)sf_didUpdateUserLocation:(id)arg1;
- (void)startLocationLocationManagerBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

