//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFChooseRegionViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, UISegmentedControl, UITextField;
@protocol SFLoginViewControllerDelegate;

@interface SFLoginViewController : UIViewController <UITextFieldDelegate, UINavigationControllerDelegate, SFChooseRegionViewDelegate>
{
    _Bool _isPassword;
    id <SFLoginViewControllerDelegate> _delegate;
    UISegmentedControl *_segmentedControl;
    UIImageView *_iconV;
    UITextField *_accountTextField;
    UITextField *_passwordTextField;
    UILabel *_accoutTitleLab;
    UIButton *_reviseButton;
    UIButton *_loginButton;
    UIButton *_regButton;
    UIButton *_selectRegionBtn;
    long long _regionType;
}

@property(nonatomic) long long regionType; // @synthesize regionType=_regionType;
@property(retain, nonatomic) UIButton *selectRegionBtn; // @synthesize selectRegionBtn=_selectRegionBtn;
@property(retain, nonatomic) UIButton *regButton; // @synthesize regButton=_regButton;
@property(retain, nonatomic) UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(retain, nonatomic) UIButton *reviseButton; // @synthesize reviseButton=_reviseButton;
@property(nonatomic) _Bool isPassword; // @synthesize isPassword=_isPassword;
@property(retain, nonatomic) UILabel *accoutTitleLab; // @synthesize accoutTitleLab=_accoutTitleLab;
@property(retain, nonatomic) UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) UITextField *accountTextField; // @synthesize accountTextField=_accountTextField;
@property(retain, nonatomic) UIImageView *iconV; // @synthesize iconV=_iconV;
@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(nonatomic) __weak id <SFLoginViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)enterWithRegion:(id)arg1;
- (void)selectRegionBtnClick:(id)arg1;
- (void)reviseButtonClick:(id)arg1;
- (void)regButtonClick:(id)arg1;
- (void)passRightAction:(id)arg1;
- (void)existIdCardSuccess;
- (void)responseToLoginSuccess;
- (void)loginSuccess;
- (void)loginButtonClick;
- (void)tapAction;
- (void)setTextFieldNormalWithLastSegmentIndex;
- (void)setTextFieldNormal;
- (void)segmentValueChanged:(id)arg1;
- (void)initView;
- (void)autoLogin:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

