//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFBaseRefreshVC.h"

#import "SFDatePickerViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UILabel, UIView;

@interface SFMileageViewController : SFBaseRefreshVC <SFDatePickerViewDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    UIView *_topBackView;
    _Bool _isOpen;
    UIButton *_titleBtn;
    UILabel *_mileageLabel;
    NSMutableArray *_dataSourceArray;
    NSString *_currentDate;
    long long _page;
}

@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) NSString *currentDate; // @synthesize currentDate=_currentDate;
@property(retain, nonatomic) NSMutableArray *dataSourceArray; // @synthesize dataSourceArray=_dataSourceArray;
@property(retain, nonatomic) UILabel *mileageLabel; // @synthesize mileageLabel=_mileageLabel;
@property(retain, nonatomic) UIButton *titleBtn; // @synthesize titleBtn=_titleBtn;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)enterWithYear:(id)arg1 month:(id)arg2 day:(id)arg3 hour:(id)arg4 minute:(id)arg5;
- (void)timeSelectAction:(id)arg1;
- (void)tapAction;
- (void)fetchUserDataFromServer;
- (void)fetchUserCountFromServer;
- (void)loadMoreData;
- (void)loadNewData;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleSwipes:(id)arg1;
- (void)addTopBackViewTakeUp;
- (void)addTopBackViewOpen;
- (void)updateTopBackViewWtihIsOpen:(_Bool)arg1;
- (void)initViews;
- (void)setNavBarButtonItem;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

