//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SDWebImageDownloadToken, SFTempDriverInfoModel, TPKeyboardAvoidingScrollView, UIButton, UIImage, UIImageView, UILabel, UITextField;

@interface SFModifyDriverLicenseViewController : UIViewController <UITextFieldDelegate>
{
    SFTempDriverInfoModel *_model;
    TPKeyboardAvoidingScrollView *_contentScrollView;
    UIImageView *_driverLicensePhotoView;
    UILabel *_driverLicensePhotoTipLabel;
    UIImage *_driverLicensePhoto;
    NSString *_driverLicensePhotoUploadPath;
    UITextField *_driverLicenseModeFiled;
    UITextField *_driverLicenseNumField;
    UITextField *_driverLicensefileNumFiled;
    UITextField *_driverLicenseStartDayField;
    UITextField *_driverLicenseEndDayField;
    UIButton *_saveBut;
    SDWebImageDownloadToken *_downloadToken;
}

@property(retain, nonatomic) SDWebImageDownloadToken *downloadToken; // @synthesize downloadToken=_downloadToken;
@property(retain, nonatomic) UIButton *saveBut; // @synthesize saveBut=_saveBut;
@property(retain, nonatomic) UITextField *driverLicenseEndDayField; // @synthesize driverLicenseEndDayField=_driverLicenseEndDayField;
@property(retain, nonatomic) UITextField *driverLicenseStartDayField; // @synthesize driverLicenseStartDayField=_driverLicenseStartDayField;
@property(retain, nonatomic) UITextField *driverLicensefileNumFiled; // @synthesize driverLicensefileNumFiled=_driverLicensefileNumFiled;
@property(retain, nonatomic) UITextField *driverLicenseNumField; // @synthesize driverLicenseNumField=_driverLicenseNumField;
@property(retain, nonatomic) UITextField *driverLicenseModeFiled; // @synthesize driverLicenseModeFiled=_driverLicenseModeFiled;
@property(retain, nonatomic) NSString *driverLicensePhotoUploadPath; // @synthesize driverLicensePhotoUploadPath=_driverLicensePhotoUploadPath;
@property(retain, nonatomic) UIImage *driverLicensePhoto; // @synthesize driverLicensePhoto=_driverLicensePhoto;
@property(retain, nonatomic) UILabel *driverLicensePhotoTipLabel; // @synthesize driverLicensePhotoTipLabel=_driverLicensePhotoTipLabel;
@property(retain, nonatomic) UIImageView *driverLicensePhotoView; // @synthesize driverLicensePhotoView=_driverLicensePhotoView;
@property(retain, nonatomic) TPKeyboardAvoidingScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) SFTempDriverInfoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)convertDateFormat:(id)arg1;
- (void)saveAction:(id)arg1;
- (void)updateSaveButStatus;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)saveButInit;
- (void)getDirverLicensePhoto;
- (id)seperateLine;
- (id)titleLabel:(id)arg1;
- (void)driverLicenseViewInit;
- (void)contentScrollViewInit;
- (void)commonInit;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

