//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSString;

@interface SFMoreSheetView : UIView <UIGestureRecognizerDelegate>
{
    UIView *_sheetView;
    NSArray *_dataSource;
    CDUnknownBlockType _block;
    struct CGRect _currFrame;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UIView *sheetView; // @synthesize sheetView=_sheetView;
@property(nonatomic) struct CGRect currFrame; // @synthesize currFrame=_currFrame;
- (void).cxx_destruct;
- (void)dealloc;
- (void)sheetBtnAction:(id)arg1;
- (void)close;
- (id)appRootViewController;
- (void)show;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithDataArray:(id)arg1 sheetBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

