//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SDWebImageDownloadToken, SFTempDriverInfoModel, TPKeyboardAvoidingScrollView, UIButton, UIImage, UIImageView, UILabel, UITextField;

@interface SFModifyIdCardViewController : UIViewController <UITextFieldDelegate>
{
    SFTempDriverInfoModel *_model;
    TPKeyboardAvoidingScrollView *_contentScrollView;
    UIImageView *_idCardPhotoView;
    UILabel *_idCardPhotoTipLabel;
    UIImage *_idCardPhoto;
    NSString *_idCardPhotoUploadPath;
    UITextField *_driverNameFiled;
    UITextField *_idCardFiled;
    UITextField *_genderField;
    UITextField *_birthdayField;
    UIButton *_saveBut;
    SDWebImageDownloadToken *_downloadToken;
}

@property(retain, nonatomic) SDWebImageDownloadToken *downloadToken; // @synthesize downloadToken=_downloadToken;
@property(retain, nonatomic) UIButton *saveBut; // @synthesize saveBut=_saveBut;
@property(retain, nonatomic) UITextField *birthdayField; // @synthesize birthdayField=_birthdayField;
@property(retain, nonatomic) UITextField *genderField; // @synthesize genderField=_genderField;
@property(retain, nonatomic) UITextField *idCardFiled; // @synthesize idCardFiled=_idCardFiled;
@property(retain, nonatomic) UITextField *driverNameFiled; // @synthesize driverNameFiled=_driverNameFiled;
@property(retain, nonatomic) NSString *idCardPhotoUploadPath; // @synthesize idCardPhotoUploadPath=_idCardPhotoUploadPath;
@property(retain, nonatomic) UIImage *idCardPhoto; // @synthesize idCardPhoto=_idCardPhoto;
@property(retain, nonatomic) UILabel *idCardPhotoTipLabel; // @synthesize idCardPhotoTipLabel=_idCardPhotoTipLabel;
@property(retain, nonatomic) UIImageView *idCardPhotoView; // @synthesize idCardPhotoView=_idCardPhotoView;
@property(retain, nonatomic) TPKeyboardAvoidingScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) SFTempDriverInfoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)saveAction:(id)arg1;
- (void)updateSaveButStatus;
- (void)saveButInit;
- (void)getIDCardPhoto;
- (id)seperateLine;
- (id)titleLabel:(id)arg1;
- (void)idCardViewInit;
- (void)contentScrollViewInit;
- (void)commonInit;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

