//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSNumber, NSString;
@protocol Optional;

@interface SFMyFeedbackModel : JSONModel
{
    NSNumber<Optional> *_ttId;
    NSString<Optional> *_title;
    NSString<Optional> *_content;
    NSString<Optional> *_feedbackTime;
    NSString<Optional> *_photoPath;
    NSString<Optional> *_status;
    NSString<Optional> *_itsmContent;
    NSString<Optional> *_modifyTm;
    NSNumber<Optional> *_isComplete;
    NSString<Optional> *_userDeptCode;
    NSString<Optional> *_userDeptName;
    NSNumber<Optional> *_cellHeight;
    NSNumber<Optional> *_headViewHeight;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber<Optional> *headViewHeight; // @synthesize headViewHeight=_headViewHeight;
@property(retain, nonatomic) NSNumber<Optional> *cellHeight; // @synthesize cellHeight=_cellHeight;
@property(retain, nonatomic) NSString<Optional> *userDeptName; // @synthesize userDeptName=_userDeptName;
@property(retain, nonatomic) NSString<Optional> *userDeptCode; // @synthesize userDeptCode=_userDeptCode;
@property(retain, nonatomic) NSNumber<Optional> *isComplete; // @synthesize isComplete=_isComplete;
@property(retain, nonatomic) NSString<Optional> *modifyTm; // @synthesize modifyTm=_modifyTm;
@property(retain, nonatomic) NSString<Optional> *itsmContent; // @synthesize itsmContent=_itsmContent;
@property(retain, nonatomic) NSString<Optional> *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString<Optional> *photoPath; // @synthesize photoPath=_photoPath;
@property(retain, nonatomic) NSString<Optional> *feedbackTime; // @synthesize feedbackTime=_feedbackTime;
@property(retain, nonatomic) NSString<Optional> *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber<Optional> *ttId; // @synthesize ttId=_ttId;
- (void).cxx_destruct;

@end

