//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFNewNavigationControllerDelegate-Protocol.h"
#import "SFUploadImageCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFPlaceHolderTextView, SFRegionModel, TPKeyboardAvoidingScrollView, UIButton, UICollectionView, UIImage, UILabel, UITextField, UIToolbar, UIView;

@interface SFNeedFeedbackVC : UIViewController <UITextViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, UINavigationControllerDelegate, UIImagePickerControllerDelegate, SFUploadImageCellDelegate, SFNewNavigationControllerDelegate>
{
    UICollectionView *_collectionView;
    NSMutableArray *_selectedPhotos;
    NSMutableArray *_unUpPhotos;
    NSMutableArray *_imageUrlArray;
    NSMutableArray *_fileIdArr;
    double _itemWH;
    double _margin;
    double _labHeigh;
    _Bool _onlyTakePhoto;
    _Bool _isMust;
    CDUnknownBlockType _completeFeedbackBlock;
    UIImage *_screenShotImg;
    NSString *_contentStr;
    long long _photoNum;
    TPKeyboardAvoidingScrollView *_contentScrollView;
    UIView *_headView;
    UIView *_regionView;
    UIView *_uploadView;
    UIView *_remarkView;
    UIView *_phoneView;
    SFPlaceHolderTextView *_sfTextView;
    UITextField *_regionField;
    UITextField *_phoneField;
    UILabel *_maxPlaceholder;
    UIButton *_confirmBtn;
    UIToolbar *_toolBar;
    SFRegionModel *_model;
}

@property(retain, nonatomic) SFRegionModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UILabel *maxPlaceholder; // @synthesize maxPlaceholder=_maxPlaceholder;
@property(retain, nonatomic) UITextField *phoneField; // @synthesize phoneField=_phoneField;
@property(retain, nonatomic) UITextField *regionField; // @synthesize regionField=_regionField;
@property(retain, nonatomic) SFPlaceHolderTextView *sfTextView; // @synthesize sfTextView=_sfTextView;
@property(retain, nonatomic) UIView *phoneView; // @synthesize phoneView=_phoneView;
@property(retain, nonatomic) UIView *remarkView; // @synthesize remarkView=_remarkView;
@property(retain, nonatomic) UIView *uploadView; // @synthesize uploadView=_uploadView;
@property(retain, nonatomic) UIView *regionView; // @synthesize regionView=_regionView;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) TPKeyboardAvoidingScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) _Bool isMust; // @synthesize isMust=_isMust;
@property(nonatomic) _Bool onlyTakePhoto; // @synthesize onlyTakePhoto=_onlyTakePhoto;
@property(nonatomic) long long photoNum; // @synthesize photoNum=_photoNum;
@property(retain, nonatomic) NSString *contentStr; // @synthesize contentStr=_contentStr;
@property(retain, nonatomic) UIImage *screenShotImg; // @synthesize screenShotImg=_screenShotImg;
@property(copy, nonatomic) CDUnknownBlockType completeFeedbackBlock; // @synthesize completeFeedbackBlock=_completeFeedbackBlock;
- (void).cxx_destruct;
- (void)viewWillDisappearAction;
- (void)viewWillAppearAction;
- (void)didReceiveMemoryWarning;
- (id)getTitleString;
- (void)checkInfo;
- (void)reloadDataCollectionView;
- (void)showSuccessWithStatus;
- (void)submitDataRequest;
- (void)uploadImage;
- (void)confirmBtn:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)openCamera;
- (void)deleteImageWithIndexPath:(id)arg1;
- (void)showImageWithArray:(id)arg1 index:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)selectRegionAction;
- (void)initConfirmBtn;
- (void)initPhoneView;
- (void)initUploadView;
- (void)initrRemarkView;
- (void)initRegionView;
- (void)initContentScrollView;
- (void)initViews;
- (void)viewDidLoad;
- (void)done;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

