//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;
@protocol SFNoDataViewDelegate;

@interface SFNoDataView : UIView
{
    UIImageView *_imageView;
    id <SFNoDataViewDelegate> _delegate;
    UILabel *_messageLabel;
}

@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak id <SFNoDataViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)renovateBtnAction:(id)arg1;
- (void)stepUI;
- (id)initNoDataViewWithFrame:(struct CGRect)arg1 imageName:(id)arg2 message:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

