//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class FLAnimatedImageView, NSString, SFLoadingView, SFPhoto, SFPhotoScrollView;
@protocol SFWebImageProtocol;

@interface SFPhotoView : UIView <UIScrollViewDelegate>
{
    _Bool _isLayoutSubViews;
    SFPhoto *_photo;
    SFPhotoScrollView *_scrollView;
    FLAnimatedImageView *_imageView;
    SFLoadingView *_loadingView;
    id <SFWebImageProtocol> _imageProtocol;
}

@property(retain, nonatomic) id <SFWebImageProtocol> imageProtocol; // @synthesize imageProtocol=_imageProtocol;
@property(retain, nonatomic) SFLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) FLAnimatedImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) SFPhotoScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool isLayoutSubViews; // @synthesize isLayoutSubViews=_isLayoutSubViews;
@property(retain, nonatomic) SFPhoto *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelCurrentImageLoad;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)layoutSubviews;
- (void)zoomToRect:(struct CGRect)arg1 animated:(_Bool)arg2;
- (struct CGRect)frameWithWidth:(double)arg1 height:(double)arg2 center:(struct CGPoint)arg3;
- (struct CGPoint)centerOfScrollViewContent:(id)arg1;
- (void)adjustFrame;
- (void)resetFrame;
- (void)loadImageWithPhoto:(id)arg1;
- (void)setupPhoto:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 imageProtocol:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

