//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class NSString;

@interface SFPlaceHolderTextView : UITextView
{
    NSString *_placeholder;
    id _items;
}

@property(retain, nonatomic) id items; // @synthesize items=_items;
@property(nonatomic) __weak NSString *placeholder; // @synthesize placeholder=_placeholder;
- (void).cxx_destruct;
- (void)setFont:(id)arg1;
- (void)dealloc;
- (void)textDidChange;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

