//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AVCaptureMetadataOutputObjectsDelegate-Protocol.h"
#import "SFEnterBarVehicleCodeControllerDelegate-Protocol.h"
#import "SFEnterVehicleCodeControllerDelegate-Protocol.h"
#import "SFNewNavigationControllerDelegate-Protocol.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, NSString, SFDriverRouteModel, UIButton, UIImageView, UILabel, UIView;
@protocol SFQRCodeViewControllerDelegate;

@interface SFQRCodeViewController : UIViewController <AVCaptureMetadataOutputObjectsDelegate, SFEnterVehicleCodeControllerDelegate, SFEnterBarVehicleCodeControllerDelegate, SFNewNavigationControllerDelegate>
{
    UILabel *_lightLabel;
    UILabel *_sendLabel;
    UIButton *_sendBtn;
    _Bool _isCarSign;
    int _qrCodeStyle;
    int _startTaskType;
    SFDriverRouteModel *_taskModel;
    NSString *_vehicleCode;
    NSString *_message;
    NSString *_gpsScopemessage;
    id <SFQRCodeViewControllerDelegate> _delegate;
    CDUnknownBlockType _popBlock;
    UIImageView *_QRImageView;
    UIImageView *_scanImageView;
    UIView *_bottomView;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_input;
    AVCaptureMetadataOutput *_output;
    AVCaptureSession *_session;
}

@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureMetadataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIImageView *scanImageView; // @synthesize scanImageView=_scanImageView;
@property(nonatomic) __weak UIImageView *QRImageView; // @synthesize QRImageView=_QRImageView;
@property(copy, nonatomic) CDUnknownBlockType popBlock; // @synthesize popBlock=_popBlock;
@property(nonatomic) __weak id <SFQRCodeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *gpsScopemessage; // @synthesize gpsScopemessage=_gpsScopemessage;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(retain, nonatomic) SFDriverRouteModel *taskModel; // @synthesize taskModel=_taskModel;
@property(nonatomic) int startTaskType; // @synthesize startTaskType=_startTaskType;
@property(nonatomic) int qrCodeStyle; // @synthesize qrCodeStyle=_qrCodeStyle;
- (void).cxx_destruct;
- (void)fetchVehicleCodeFromServerWithVehicleCheckModel:(id)arg1;
- (void)toastTextIsScan:(_Bool)arg1;
- (_Bool)boolIsCarSign:(id)arg1;
- (_Bool)provingCarkNumber:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)checkCustomVehicleFromServer:(id)arg1;
- (void)checkVehicleFromServer:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)startScan;
- (void)openLighting:(id)arg1;
- (void)sessionStopRunning;
- (void)startContinueQRAnimation;
- (void)startQRAnimation;
- (void)helpAction;
- (void)setupContentView;
- (void)didReceiveMemoryWarning;
- (void)enterBarVehicleCode:(id)arg1;
- (void)enterVehicleNumber:(id)arg1;
- (void)sendBtnAction:(id)arg1;
- (void)navigationWillPop;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

