//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, NSTimer, UILabel;

@interface SFReimbursementView : UIView
{
    NSString *_operTime;
    UILabel *_reimbursementLa;
    NSTimer *_timer;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *reimbursementLa; // @synthesize reimbursementLa=_reimbursementLa;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stopTimer;
- (void)renovateReimbursementView;
- (void)renovateReimbursementViewWithOpertime:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)closeBtnAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

