//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SFRegionModel, UILabel;

@interface SFRegionListCell : UITableViewCell
{
    UILabel *_sequenceLabel;
    UILabel *_regionLabel;
    SFRegionModel *_model;
}

@property(retain, nonatomic) SFRegionModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *regionLabel; // @synthesize regionLabel=_regionLabel;
@property(retain, nonatomic) UILabel *sequenceLabel; // @synthesize sequenceLabel=_sequenceLabel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

