//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage, UIView;

@interface SFScreenShotManager : NSObject
{
    UIImage *_screenShot;
    UIView *_overlay;
    CDUnknownBlockType _feedBackShareAction;
    CDUnknownBlockType _wChatShareAction;
    CDUnknownBlockType _helpBtnAction;
}

@property(copy, nonatomic) CDUnknownBlockType helpBtnAction; // @synthesize helpBtnAction=_helpBtnAction;
@property(copy, nonatomic) CDUnknownBlockType wChatShareAction; // @synthesize wChatShareAction=_wChatShareAction;
@property(copy, nonatomic) CDUnknownBlockType feedBackShareAction; // @synthesize feedBackShareAction=_feedBackShareAction;
@property(retain, nonatomic) UIView *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) UIImage *screenShot; // @synthesize screenShot=_screenShot;
- (void).cxx_destruct;
- (void)dealloc;
- (void)wchatShare:(id)arg1;
- (void)helpBtnAction:(id)arg1;
- (void)feedBackShare:(id)arg1;
- (void)closeAction:(id)arg1;
- (id)imageDataScreenShot;
- (void)getScreenShot:(id)arg1;
- (void)stopListenScreenShot;
- (void)startListenScreenShotWithFeedBackShareAction:(CDUnknownBlockType)arg1 WChatShareAction:(CDUnknownBlockType)arg2 helpBtnAction:(CDUnknownBlockType)arg3;
- (id)init;

@end

