//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView;
@protocol SFSelectBtnViewDelegate;

@interface SFSelectBtnView : UIView
{
    id <SFSelectBtnViewDelegate> _delegate;
    UIButton *_leftBtn;
    UIButton *_rightBtn;
    UIImageView *_leftLineView;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIImageView *leftLineView; // @synthesize leftLineView=_leftLineView;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(nonatomic) __weak id <SFSelectBtnViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)bottomLineAnimationBtnIndex:(int)arg1;
- (void)kMovieMenuBtnClick:(id)arg1;
- (void)buttonAction:(id)arg1;
- (void)setButton:(id)arg1 badgeValue:(id)arg2 isRedBall:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1 letftTitle:(id)arg2 rightTitle:(id)arg3 normalImage:(id)arg4 selectImage:(id)arg5 type:(long long)arg6;

@end

