//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFCityModel, SFProviesModel, UIPickerView, UIToolbar;

@interface SFSelectCityView : UIView <UIPickerViewDelegate, UIPickerViewDataSource>
{
    CDUnknownBlockType _enterBlock;
    UIView *_bgView;
    UIPickerView *_pickView;
    UIToolbar *_myToolBar;
    NSMutableArray *_dataArr;
    long long _indexOfProvice;
    SFProviesModel *_proviesModel;
    SFCityModel *_cityModel;
}

@property(retain, nonatomic) SFCityModel *cityModel; // @synthesize cityModel=_cityModel;
@property(retain, nonatomic) SFProviesModel *proviesModel; // @synthesize proviesModel=_proviesModel;
@property(nonatomic) long long indexOfProvice; // @synthesize indexOfProvice=_indexOfProvice;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) UIToolbar *myToolBar; // @synthesize myToolBar=_myToolBar;
@property(retain, nonatomic) UIPickerView *pickView; // @synthesize pickView=_pickView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType enterBlock; // @synthesize enterBlock=_enterBlock;
- (void).cxx_destruct;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)confirmAction;
- (void)cancleAction;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2 selectBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

