//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol SFSelectAllViewDelegate;

@interface SFSelectAllView : UIView
{
    id <SFSelectAllViewDelegate> _delegate;
    UIButton *_selectBtn;
    UIButton *_deleteBtn;
}

@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(nonatomic) __weak id <SFSelectAllViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)deleteBtnBtnAction:(id)arg1;
- (void)selectBtnAction:(id)arg1;
- (void)setSelecteButtonState:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

