//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFLocationServiceDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSArray, NSString, SFDriverRouteModel, SFPlaceHolderTextView, SFUserLocation, UIButton, UILabel, UIScrollView, UITextField, UIView;
@protocol SFSuspendViewControllerDelegate;

@interface SFSuspendViewController : UIViewController <SFLocationServiceDelegate, UITextFieldDelegate, UITextViewDelegate>
{
    SFDriverRouteModel *_taskModel;
    NSString *_nextDeptCode;
    id <SFSuspendViewControllerDelegate> _delegate;
    UIScrollView *_contentScrollView;
    UIView *_locationView;
    SFPlaceHolderTextView *_locationTextView;
    SFUserLocation *_location;
    UITextField *_destinationCode;
    UITextField *_destinationMiles;
    UITextField *_roadPrice;
    SFPlaceHolderTextView *_suspendTextView;
    UILabel *_maxPlaceholder;
    UIButton *_suspendBtn;
    UIButton *_locationBtn;
    NSArray *_suspendSelectArr;
    long long _suspendSelecIndex;
    struct CGSize _scrollViewContentSize;
}

@property(nonatomic) struct CGSize scrollViewContentSize; // @synthesize scrollViewContentSize=_scrollViewContentSize;
@property(nonatomic) long long suspendSelecIndex; // @synthesize suspendSelecIndex=_suspendSelecIndex;
@property(retain, nonatomic) NSArray *suspendSelectArr; // @synthesize suspendSelectArr=_suspendSelectArr;
@property(retain, nonatomic) UIButton *locationBtn; // @synthesize locationBtn=_locationBtn;
@property(retain, nonatomic) UIButton *suspendBtn; // @synthesize suspendBtn=_suspendBtn;
@property(retain, nonatomic) UILabel *maxPlaceholder; // @synthesize maxPlaceholder=_maxPlaceholder;
@property(retain, nonatomic) SFPlaceHolderTextView *suspendTextView; // @synthesize suspendTextView=_suspendTextView;
@property(retain, nonatomic) UITextField *roadPrice; // @synthesize roadPrice=_roadPrice;
@property(retain, nonatomic) UITextField *destinationMiles; // @synthesize destinationMiles=_destinationMiles;
@property(retain, nonatomic) UITextField *destinationCode; // @synthesize destinationCode=_destinationCode;
@property(retain, nonatomic) SFUserLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) SFPlaceHolderTextView *locationTextView; // @synthesize locationTextView=_locationTextView;
@property(retain, nonatomic) UIView *locationView; // @synthesize locationView=_locationView;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) __weak id <SFSuspendViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *nextDeptCode; // @synthesize nextDeptCode=_nextDeptCode;
@property(retain, nonatomic) SFDriverRouteModel *taskModel; // @synthesize taskModel=_taskModel;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)suspendDriverTaskStop;
- (void)suspendBtnAction:(id)arg1;
- (void)locationBtnAction;
- (void)preventFlicker:(id)arg1;
- (void)suspendSelectBtnAction:(id)arg1;
- (_Bool)boolSuspendReason;
- (void)checkInfo;
- (void)ph_didFailToLocateUserWithError:(id)arg1;
- (void)sf_didUpdateUserLocation:(id)arg1;
- (void)startLocation;
- (void)roadPriceChange:(id)arg1;
- (void)destinationMilesChange:(id)arg1;
- (void)destinationCodeChange:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)tapAction;
- (id)suspendBackWithTitle:(id)arg1 textField:(id)arg2 rightTitle:(id)arg3 ifLine:(_Bool)arg4;
- (void)keyboardWillHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)initViews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

