//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFSwitchElecLockModel : JSONModel
{
    NSString *_operateType;
    NSString *_operateTime;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *operateTime; // @synthesize operateTime=_operateTime;
@property(retain, nonatomic) NSString *operateType; // @synthesize operateType=_operateType;
- (void).cxx_destruct;

@end

