//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SFInforModel, UIButton, UIImageView, UILabel;

@interface SFTaskInfomationCell : UITableViewCell
{
    SFInforModel *_model;
    UIImageView *_bgView;
    UIImageView *_imgView;
    UIImageView *_redView;
    UILabel *_titleLab;
    UILabel *_timeLab;
    UILabel *_infomationLab;
    UIButton *_stateBtn;
}

+ (double)cellHeight;
@property(retain, nonatomic) UIButton *stateBtn; // @synthesize stateBtn=_stateBtn;
@property(retain, nonatomic) UILabel *infomationLab; // @synthesize infomationLab=_infomationLab;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *redView; // @synthesize redView=_redView;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SFInforModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)confingWithInfomationModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

