//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFNewNavigationControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, TPKeyboardAvoidingScrollView, UIButton, UIImage, UIImageView, UILabel, UITextField;
@protocol SFTempDriverEnterInfoViewControllerDelegate;

@interface SFTempDriverEnterInfoViewController : UIViewController <UITextFieldDelegate, SFNewNavigationControllerDelegate>
{
    id <SFTempDriverEnterInfoViewControllerDelegate> _delegate;
    TPKeyboardAvoidingScrollView *_contentScrollView;
    UIImageView *_idCardPhotoView;
    UILabel *_idCardPhotoTipLabel;
    UIImage *_idCardPhoto;
    NSString *_idCardPhotoUploadPath;
    UIImageView *_driverLicensePhotoView;
    UILabel *_driverLicensePhotoTipLabel;
    UIImage *_driverLicensePhoto;
    NSString *_driverLicensePhotoUploadPath;
    UIImageView *_qualificationCertificatePhotoView;
    UILabel *_qualificationCertificatePhotoTipLabel;
    UIImage *_qualificationCertificatePhoto;
    NSString *_qualificationCertificatePhotoUploadPath;
    UIImageView *_healthCertificatePhotoView;
    UILabel *_healthCertificatePhotoTipLabel;
    UIImage *_healthCertificatePhoto;
    NSString *_healthCertificatePhotoUploadPath;
    UITextField *_driverNameFiled;
    UITextField *_idCardFiled;
    UITextField *_vehicleModeFiled;
    UIButton *_submitBut;
}

@property(retain, nonatomic) UIButton *submitBut; // @synthesize submitBut=_submitBut;
@property(retain, nonatomic) UITextField *vehicleModeFiled; // @synthesize vehicleModeFiled=_vehicleModeFiled;
@property(retain, nonatomic) UITextField *idCardFiled; // @synthesize idCardFiled=_idCardFiled;
@property(retain, nonatomic) UITextField *driverNameFiled; // @synthesize driverNameFiled=_driverNameFiled;
@property(retain, nonatomic) NSString *healthCertificatePhotoUploadPath; // @synthesize healthCertificatePhotoUploadPath=_healthCertificatePhotoUploadPath;
@property(retain, nonatomic) UIImage *healthCertificatePhoto; // @synthesize healthCertificatePhoto=_healthCertificatePhoto;
@property(retain, nonatomic) UILabel *healthCertificatePhotoTipLabel; // @synthesize healthCertificatePhotoTipLabel=_healthCertificatePhotoTipLabel;
@property(retain, nonatomic) UIImageView *healthCertificatePhotoView; // @synthesize healthCertificatePhotoView=_healthCertificatePhotoView;
@property(retain, nonatomic) NSString *qualificationCertificatePhotoUploadPath; // @synthesize qualificationCertificatePhotoUploadPath=_qualificationCertificatePhotoUploadPath;
@property(retain, nonatomic) UIImage *qualificationCertificatePhoto; // @synthesize qualificationCertificatePhoto=_qualificationCertificatePhoto;
@property(retain, nonatomic) UILabel *qualificationCertificatePhotoTipLabel; // @synthesize qualificationCertificatePhotoTipLabel=_qualificationCertificatePhotoTipLabel;
@property(retain, nonatomic) UIImageView *qualificationCertificatePhotoView; // @synthesize qualificationCertificatePhotoView=_qualificationCertificatePhotoView;
@property(retain, nonatomic) NSString *driverLicensePhotoUploadPath; // @synthesize driverLicensePhotoUploadPath=_driverLicensePhotoUploadPath;
@property(retain, nonatomic) UIImage *driverLicensePhoto; // @synthesize driverLicensePhoto=_driverLicensePhoto;
@property(retain, nonatomic) UILabel *driverLicensePhotoTipLabel; // @synthesize driverLicensePhotoTipLabel=_driverLicensePhotoTipLabel;
@property(retain, nonatomic) UIImageView *driverLicensePhotoView; // @synthesize driverLicensePhotoView=_driverLicensePhotoView;
@property(retain, nonatomic) NSString *idCardPhotoUploadPath; // @synthesize idCardPhotoUploadPath=_idCardPhotoUploadPath;
@property(retain, nonatomic) UIImage *idCardPhoto; // @synthesize idCardPhoto=_idCardPhoto;
@property(retain, nonatomic) UILabel *idCardPhotoTipLabel; // @synthesize idCardPhotoTipLabel=_idCardPhotoTipLabel;
@property(retain, nonatomic) UIImageView *idCardPhotoView; // @synthesize idCardPhotoView=_idCardPhotoView;
@property(retain, nonatomic) TPKeyboardAvoidingScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) __weak id <SFTempDriverEnterInfoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)validateIDCard;
- (_Bool)validateName;
- (void)submitAction:(id)arg1;
- (void)updateSubmitbutStatus;
- (void)getPhotoWithType:(long long)arg1;
- (void)getHealthCertificatePhoto;
- (void)getQualificationCertificatePhoto;
- (void)getDirverLicensePhoto;
- (void)getIDCardPhoto;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (id)titleLabel:(id)arg1;
- (id)seperateLine;
- (id)titleViewInitWithTitle:(id)arg1 offsetY:(double)arg2;
- (void)submitButInit;
- (void)healthCertificateViewInit;
- (void)qualificationCertificateViewInit;
- (void)driverLicenseViewInit;
- (void)idCardViewInit;
- (void)contentScrollViewInit;
- (void)commonInit;
- (void)viewWillAppear:(_Bool)arg1;
- (void)navigationWillPop;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

