//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFThreeCheckItemsModel : JSONModel
{
    NSString *_checkId;
    NSString *_checkItemId;
    NSString *_itemTitleCode;
    NSString *_itemTitleCodeStr;
    NSString *_itemCode;
    NSString *_itemCodeStr;
    NSString *_remark;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(retain, nonatomic) NSString *itemCodeStr; // @synthesize itemCodeStr=_itemCodeStr;
@property(retain, nonatomic) NSString *itemCode; // @synthesize itemCode=_itemCode;
@property(retain, nonatomic) NSString *itemTitleCodeStr; // @synthesize itemTitleCodeStr=_itemTitleCodeStr;
@property(retain, nonatomic) NSString *itemTitleCode; // @synthesize itemTitleCode=_itemTitleCode;
@property(retain, nonatomic) NSString *checkItemId; // @synthesize checkItemId=_checkItemId;
@property(retain, nonatomic) NSString *checkId; // @synthesize checkId=_checkId;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

