//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UITableView;

@interface SFToCMarketSelectCityVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _proviceSectionOpen;
    _Bool _citySectionOpen;
    CDUnknownBlockType _selectedBlock;
    UITableView *_tableView;
    NSMutableArray *_selectedCityArray;
    NSMutableArray *_proviceArray;
    long long _proviceSelectedIndex;
    NSArray *_cityArray;
    NSString *_selectedCity;
}

@property(nonatomic) _Bool citySectionOpen; // @synthesize citySectionOpen=_citySectionOpen;
@property(nonatomic) _Bool proviceSectionOpen; // @synthesize proviceSectionOpen=_proviceSectionOpen;
@property(copy, nonatomic) NSString *selectedCity; // @synthesize selectedCity=_selectedCity;
@property(retain, nonatomic) NSArray *cityArray; // @synthesize cityArray=_cityArray;
@property(nonatomic) long long proviceSelectedIndex; // @synthesize proviceSelectedIndex=_proviceSelectedIndex;
@property(retain, nonatomic) NSMutableArray *proviceArray; // @synthesize proviceArray=_proviceArray;
@property(retain, nonatomic) NSMutableArray *selectedCityArray; // @synthesize selectedCityArray=_selectedCityArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType selectedBlock; // @synthesize selectedBlock=_selectedBlock;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)cityArrowButAction:(id)arg1;
- (void)proviceArrowButAction:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)queryCity;
- (void)setupUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

