//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSTimer, SFToCOrderInfoListView, SFToCOrderLineListView, SFToCOrderModel, UIButton, UIImageView, UILabel, UIView;
@protocol SFTocHomeTaskListCellDlegate;

@interface SFTocHomeTaskListCell : UITableViewCell
{
    SFToCOrderModel *_model;
    id <SFTocHomeTaskListCellDlegate> _delegate;
    UIView *_bgView;
    UILabel *_taskStatusLab;
    UIImageView *_taskStatusImageV;
    UIImageView *_settleStatusImageV;
    SFToCOrderLineListView *_ordeLlineView;
    SFToCOrderInfoListView *_attributeView;
    UIView *_contentBGView;
    UIView *_actionBGView;
    UILabel *_timerLab;
    UIButton *_phoneBtn;
    UIButton *_cancleBtn;
    UIButton *_startBtn;
    NSTimer *_timer;
}

+ (double)getCellHeight:(id)arg1;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIButton *startBtn; // @synthesize startBtn=_startBtn;
@property(retain, nonatomic) UIButton *cancleBtn; // @synthesize cancleBtn=_cancleBtn;
@property(retain, nonatomic) UIButton *phoneBtn; // @synthesize phoneBtn=_phoneBtn;
@property(retain, nonatomic) UILabel *timerLab; // @synthesize timerLab=_timerLab;
@property(retain, nonatomic) UIView *actionBGView; // @synthesize actionBGView=_actionBGView;
@property(retain, nonatomic) UIView *contentBGView; // @synthesize contentBGView=_contentBGView;
@property(retain, nonatomic) SFToCOrderInfoListView *attributeView; // @synthesize attributeView=_attributeView;
@property(retain, nonatomic) SFToCOrderLineListView *ordeLlineView; // @synthesize ordeLlineView=_ordeLlineView;
@property(retain, nonatomic) UIImageView *settleStatusImageV; // @synthesize settleStatusImageV=_settleStatusImageV;
@property(retain, nonatomic) UIImageView *taskStatusImageV; // @synthesize taskStatusImageV=_taskStatusImageV;
@property(retain, nonatomic) UILabel *taskStatusLab; // @synthesize taskStatusLab=_taskStatusLab;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak id <SFTocHomeTaskListCellDlegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SFToCOrderModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)showTaskStatus:(long long)arg1;
- (void)startBtnAction:(id)arg1;
- (void)cancleBtnAction:(id)arg1;
- (void)callPhone;
- (void)orderAvaliableTime;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

