//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;

@interface SFToCTodayNewArrivalHeaderItem : UIView
{
    _Bool _isSelected;
    NSString *_title;
    NSString *_desc;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    long long _index;
}

@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 index:(long long)arg2 total:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1 index:(long long)arg2 total:(long long)arg3;

@end

