//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIColor, UIFont, UIImage, UIImageView, UILabel;

@interface SFToCImageAlertView : UIView
{
    NSString *_title;
    UIColor *_titleColor;
    UIFont *_titleFont;
    NSString *_message;
    UIColor *_messageColor;
    UIFont *_messageFont;
    NSString *_leftButTitle;
    UIColor *_leftButTitleColor;
    UIFont *_leftButTitleFont;
    UIColor *_leftButBgColor;
    NSString *_rightButTitle;
    UIColor *_rightButTitleColor;
    UIFont *_rightButTitleFont;
    UIColor *_rightButBgColor;
    NSString *_confirmButTitle;
    UIColor *_confirmButTitleColor;
    UIFont *_confirmButTitleFont;
    UIColor *_confirmButBgColor;
    UIImage *_topImg;
    CDUnknownBlockType _block;
    UIView *_bgView;
    UIView *_topView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_leftBut;
    UIButton *_rightBut;
    UIButton *_confirmBut;
    UIImageView *_topImageView;
    UIButton *_cancelBtn;
}

@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIImageView *topImageView; // @synthesize topImageView=_topImageView;
@property(retain, nonatomic) UIButton *confirmBut; // @synthesize confirmBut=_confirmBut;
@property(retain, nonatomic) UIButton *rightBut; // @synthesize rightBut=_rightBut;
@property(retain, nonatomic) UIButton *leftBut; // @synthesize leftBut=_leftBut;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) UIImage *topImg; // @synthesize topImg=_topImg;
@property(retain, nonatomic) UIColor *confirmButBgColor; // @synthesize confirmButBgColor=_confirmButBgColor;
@property(retain, nonatomic) UIFont *confirmButTitleFont; // @synthesize confirmButTitleFont=_confirmButTitleFont;
@property(retain, nonatomic) UIColor *confirmButTitleColor; // @synthesize confirmButTitleColor=_confirmButTitleColor;
@property(retain, nonatomic) NSString *confirmButTitle; // @synthesize confirmButTitle=_confirmButTitle;
@property(retain, nonatomic) UIColor *rightButBgColor; // @synthesize rightButBgColor=_rightButBgColor;
@property(retain, nonatomic) UIFont *rightButTitleFont; // @synthesize rightButTitleFont=_rightButTitleFont;
@property(retain, nonatomic) UIColor *rightButTitleColor; // @synthesize rightButTitleColor=_rightButTitleColor;
@property(retain, nonatomic) NSString *rightButTitle; // @synthesize rightButTitle=_rightButTitle;
@property(retain, nonatomic) UIColor *leftButBgColor; // @synthesize leftButBgColor=_leftButBgColor;
@property(retain, nonatomic) UIFont *leftButTitleFont; // @synthesize leftButTitleFont=_leftButTitleFont;
@property(retain, nonatomic) UIColor *leftButTitleColor; // @synthesize leftButTitleColor=_leftButTitleColor;
@property(retain, nonatomic) NSString *leftButTitle; // @synthesize leftButTitle=_leftButTitle;
@property(retain, nonatomic) UIFont *messageFont; // @synthesize messageFont=_messageFont;
@property(retain, nonatomic) UIColor *messageColor; // @synthesize messageColor=_messageColor;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)close;
- (id)appRootViewController;
- (void)show;
- (void)tapAction:(id)arg1;
- (void)cancelBtnClick:(id)arg1;
- (void)buttonClick:(id)arg1;
- (void)update;
- (void)setNeedsLayout;
- (void)setupUI;
- (id)init;
- (id)initWithTitle:(id)arg1 message:(id)arg2 confirmButTitle:(id)arg3;
- (id)initWithTopImage:(id)arg1 title:(id)arg2 message:(id)arg3 leftButTitle:(id)arg4 rightButTitle:(id)arg5;
- (id)initWithTopImage:(id)arg1 messge:(id)arg2 leftButTitle:(id)arg3 rightButTitle:(id)arg4;
- (id)initWithTopImage:(id)arg1 title:(id)arg2 leftButTitle:(id)arg3 rightButTitle:(id)arg4;

@end

