//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SFToCQueryUserStatus : NSObject
{
    int _mark;
}

@property(nonatomic) int mark; // @synthesize mark=_mark;
- (void)queryUserStatusAndVehicleInfo:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)queryUserStatusSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;

@end

