//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFToCAccountBalanceVM, UIButton, UILabel, UITableView, UIView;
@protocol SFToCBondAccountVCDelegate;

@interface SFToCBondAccountVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    _Bool _isSelectAll;
    id <SFToCBondAccountVCDelegate> _delegate;
    UITableView *_tableView;
    UIView *_tableHeaderView;
    UIButton *_refundBtn;
    UIView *_bottomView;
    UIButton *_selectAllBtn;
    UILabel *_selectAllLabel;
    UILabel *_totalLabel;
    NSString *_accountId;
    NSMutableArray *_dataArr;
    SFToCAccountBalanceVM *_accountBalanceVM;
    long long _page;
    NSMutableArray *_cellArray;
}

@property(nonatomic) _Bool isSelectAll; // @synthesize isSelectAll=_isSelectAll;
@property(retain, nonatomic) NSMutableArray *cellArray; // @synthesize cellArray=_cellArray;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) SFToCAccountBalanceVM *accountBalanceVM; // @synthesize accountBalanceVM=_accountBalanceVM;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(copy, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) UILabel *totalLabel; // @synthesize totalLabel=_totalLabel;
@property(retain, nonatomic) UILabel *selectAllLabel; // @synthesize selectAllLabel=_selectAllLabel;
@property(retain, nonatomic) UIButton *selectAllBtn; // @synthesize selectAllBtn=_selectAllBtn;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *refundBtn; // @synthesize refundBtn=_refundBtn;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <SFToCBondAccountVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)refundAction:(id)arg1;
- (void)clickAction:(id)arg1;
- (void)renovateUIByArray:(id)arg1;
- (void)findDepositPaymentOrderList:(CDUnknownBlockType)arg1;
- (void)accountBalancePullDown:(CDUnknownBlockType)arg1;
- (void)loadMoreRefresh;
- (void)pullDownRefresh;
- (long long)canSelectedNum;
- (void)updateBottomViewStatus;
- (void)initSelectAllView;
- (void)initTableViewHeaderView;
- (void)viewDidLayoutSubviews;
- (void)beginRefreshing;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

