//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "SFToCTodayNewArrivalHeaderViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, SFImgTitleView, SFToCCityModel, SFToCTodayNewArrivalHeaderView, SFToCTodayNewArrivalVM, UITableView, UIView;

@interface SFToCTodayNewArrivalVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, SFToCTodayNewArrivalHeaderViewDelegate>
{
    _Bool _isChange;
    _Bool _isTabClick;
    SFToCCityModel *_cityModel;
    SFImgTitleView *_rightBarButtonItem;
    SFToCTodayNewArrivalHeaderView *_headerView;
    UITableView *_table;
    SFToCTodayNewArrivalVM *_todayNewArrivalVM;
    NSMutableDictionary *_param;
    NSMutableArray *_vehicleDtos;
    unsigned long long _status;
    UIView *_tableViewHeaderView;
    long long _index;
}

@property(nonatomic) _Bool isTabClick; // @synthesize isTabClick=_isTabClick;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) UIView *tableViewHeaderView; // @synthesize tableViewHeaderView=_tableViewHeaderView;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSMutableArray *vehicleDtos; // @synthesize vehicleDtos=_vehicleDtos;
@property(retain, nonatomic) NSMutableDictionary *param; // @synthesize param=_param;
@property(nonatomic) _Bool isChange; // @synthesize isChange=_isChange;
@property(retain, nonatomic) SFToCTodayNewArrivalVM *todayNewArrivalVM; // @synthesize todayNewArrivalVM=_todayNewArrivalVM;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) SFToCTodayNewArrivalHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) SFImgTitleView *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(retain, nonatomic) SFToCCityModel *cityModel; // @synthesize cityModel=_cityModel;
- (void).cxx_destruct;
- (void)todayNewArrivalTabbarClick:(long long)arg1 status:(unsigned long long)arg2;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (void)emptyDataSet:(id)arg1 didTapView:(id)arg2;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (id)getTomorrowTime:(id)arg1;
- (id)getTomorrowTime_18PM;
- (id)getTomorrowTime_10AM;
- (id)getTodayTime_18PM;
- (id)getTodayTime_10AM;
- (id)getTodayTimeHHmmss;
- (id)getTodayTime;
- (void)goMarket;
- (void)beginRefresh;
- (void)bidButActionWithModel:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)pushSource;
- (void)addLoadMoreRefreshToScrollView:(id)arg1;
- (void)loadMoreRefresh;
- (void)groundTodayNewListWithResponseArray:(id)arg1;
- (void)groundTodayNewBiddingTabQueryWithSuccess:(_Bool)arg1;
- (void)todayNewArrivalData;
- (void)pullDownRefresh;
- (void)cityChoiceClick;
- (void)initCityChoiceItem;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

