//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "SFBidDetailFeelCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, NSTimer, SFImgTitleView, SFToCMarketBidDetailVM, SFToCMarketBidNoticeVM, TPKeyboardAvoidingTableView, UIButton, UILabel, UIView;

@interface SFToCMarketBidDetailVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, SFBidDetailFeelCellDelegate>
{
    NSTimer *_timer;
    NSTimer *_noticeTimer;
    _Bool _packageShowMore;
    _Bool _isChangeRemindType;
    long long _biddingId;
    CDUnknownBlockType _remindChangeBlock;
    NSString *_pushSource;
    unsigned long long _type;
    NSString *_distance;
    UIView *_topView;
    SFImgTitleView *_topTipView;
    TPKeyboardAvoidingTableView *_table;
    SFToCMarketBidDetailVM *_bidDetailVM;
    SFToCMarketBidNoticeVM *_bidNoticeVM;
    UIView *_bottomView;
    UILabel *_bidDesLabel;
    UIButton *_orderBidBut;
    UIButton *_bargaBut;
    UIButton *_bidNoticeBut;
    NSString *_vehicleCode;
}

@property(copy, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(nonatomic) _Bool isChangeRemindType; // @synthesize isChangeRemindType=_isChangeRemindType;
@property(nonatomic) _Bool packageShowMore; // @synthesize packageShowMore=_packageShowMore;
@property(retain, nonatomic) UIButton *bidNoticeBut; // @synthesize bidNoticeBut=_bidNoticeBut;
@property(retain, nonatomic) UIButton *bargaBut; // @synthesize bargaBut=_bargaBut;
@property(retain, nonatomic) UIButton *orderBidBut; // @synthesize orderBidBut=_orderBidBut;
@property(retain, nonatomic) UILabel *bidDesLabel; // @synthesize bidDesLabel=_bidDesLabel;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) SFToCMarketBidNoticeVM *bidNoticeVM; // @synthesize bidNoticeVM=_bidNoticeVM;
@property(retain, nonatomic) SFToCMarketBidDetailVM *bidDetailVM; // @synthesize bidDetailVM=_bidDetailVM;
@property(retain, nonatomic) TPKeyboardAvoidingTableView *table; // @synthesize table=_table;
@property(retain, nonatomic) SFImgTitleView *topTipView; // @synthesize topTipView=_topTipView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(copy, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *pushSource; // @synthesize pushSource=_pushSource;
@property(copy, nonatomic) CDUnknownBlockType remindChangeBlock; // @synthesize remindChangeBlock=_remindChangeBlock;
@property(nonatomic) long long biddingId; // @synthesize biddingId=_biddingId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)trackEventWithEventID:(id)arg1 isSuccess:(_Bool)arg2;
- (void)gatherGroundDriverPlusTradeDetail;
- (void)bidNoticeAction:(id)arg1;
- (void)getContactInfo:(id)arg1;
- (void)bargaFeedBack:(id)arg1;
- (void)protocalAction;
- (void)bidReq;
- (void)showBidConfirmAlert;
- (void)bid:(id)arg1;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)feelListViewPriceDescription;
- (void)pushLinesOverlayViewController:(id)arg1;
- (void)pushLinesOverlay:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)bidNoticeAvalibelTime;
- (void)bidAvaliableTime;
- (void)refreshView;
- (void)pullDownRefresh;
- (void)backDidClicked;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

