//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray, NSString;
@protocol SFToCAccountFlowWaterModel><Optional;

@interface SFToCAccountFlowWaterInfoModel : JSONModel
{
    long long _accountId;
    long long _accountType;
    NSString *_availableBalance;
    NSString *_freezingBalance;
    NSString *_expectedThawingTime;
    NSString *_status;
    NSMutableArray<SFToCAccountFlowWaterModel><Optional> *_queryAccountFlowWater;
    NSMutableArray<SFToCAccountFlowWaterModel><Optional> *_accountFreezingFlowWaters;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSMutableArray<SFToCAccountFlowWaterModel><Optional> *accountFreezingFlowWaters; // @synthesize accountFreezingFlowWaters=_accountFreezingFlowWaters;
@property(retain, nonatomic) NSMutableArray<SFToCAccountFlowWaterModel><Optional> *queryAccountFlowWater; // @synthesize queryAccountFlowWater=_queryAccountFlowWater;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *expectedThawingTime; // @synthesize expectedThawingTime=_expectedThawingTime;
@property(retain, nonatomic) NSString *freezingBalance; // @synthesize freezingBalance=_freezingBalance;
@property(retain, nonatomic) NSString *availableBalance; // @synthesize availableBalance=_availableBalance;
@property(nonatomic) long long accountType; // @synthesize accountType=_accountType;
@property(nonatomic) long long accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;

@end

