//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, SFToCCityModel, UIButton, UITableView;

@interface SFToCMarketCityFilter : UIView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _proviceSectionOpen;
    _Bool _citySectionOpen;
    _Bool _isInitByToCMarketVC;
    CDUnknownBlockType _cityFilterBlock;
    UITableView *_table;
    UIButton *_confirmBut;
    NSMutableArray *_selectedCityArray;
    NSArray *_historyCityArray;
    NSMutableArray *_proviceArray;
    long long _proviceSelectedIndex;
    NSArray *_cityArray;
    long long _cityFilterType;
    SFToCCityModel *_locationCity;
}

@property(nonatomic) _Bool isInitByToCMarketVC; // @synthesize isInitByToCMarketVC=_isInitByToCMarketVC;
@property(retain, nonatomic) SFToCCityModel *locationCity; // @synthesize locationCity=_locationCity;
@property(nonatomic) long long cityFilterType; // @synthesize cityFilterType=_cityFilterType;
@property(nonatomic) _Bool citySectionOpen; // @synthesize citySectionOpen=_citySectionOpen;
@property(nonatomic) _Bool proviceSectionOpen; // @synthesize proviceSectionOpen=_proviceSectionOpen;
@property(retain, nonatomic) NSArray *cityArray; // @synthesize cityArray=_cityArray;
@property(nonatomic) long long proviceSelectedIndex; // @synthesize proviceSelectedIndex=_proviceSelectedIndex;
@property(retain, nonatomic) NSMutableArray *proviceArray; // @synthesize proviceArray=_proviceArray;
@property(retain, nonatomic) NSArray *historyCityArray; // @synthesize historyCityArray=_historyCityArray;
@property(retain, nonatomic) NSMutableArray *selectedCityArray; // @synthesize selectedCityArray=_selectedCityArray;
@property(retain, nonatomic) UIButton *confirmBut; // @synthesize confirmBut=_confirmBut;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(copy, nonatomic) CDUnknownBlockType cityFilterBlock; // @synthesize cityFilterBlock=_cityFilterBlock;
- (void).cxx_destruct;
- (void)dealloc;
- (void)reset;
- (void)queryCity;
- (void)hidden;
- (id)appRootViewController;
- (void)showHistorySelectedCity:(id)arg1 locationCity:(id)arg2;
- (id)getSelectedCityArray;
- (void)saveSelectedAll:(id)arg1 cityArray:(id)arg2 proviceArray:(id)arg3;
- (void)confirmAction:(id)arg1;
- (void)cityArrowButAction:(id)arg1;
- (void)proviceArrowButAction:(id)arg1;
- (void)delAllSelectedCity:(id)arg1;
- (void)delSelectedCityModel:(id)arg1;
- (void)addSelectedCityModel:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)layoutSubviews;
- (void)setupUI;
- (void)relocation:(id)arg1;
- (id)initByToCMarketBidVCWithCityFilyerType:(long long)arg1;
- (id)initWithCityFilyerType:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

