//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFCalendarPickerControllerDelegate-Protocol.h"
#import "SFNoDataViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, SFCalendarPickerController, SFNoDataView, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface SFToCTaskVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, SFCalendarPickerControllerDelegate, SFNoDataViewDelegate>
{
    UIImageView *_beforeImageView;
    UIImageView *_afterImageView;
    _Bool _isCurrent;
    _Bool _isFirstLoad;
    UIView *_contentView;
    UIButton *_beforeDayBtn;
    UILabel *_beforeBadge;
    UIButton *_selectDayBtn;
    UILabel *_selectLabel;
    UILabel *_selectBadge;
    UIImageView *_selectImageView;
    UIButton *_afterDayBtn;
    UILabel *_afterBadge;
    UITableView *_taskTableView;
    NSMutableArray *_taskArray;
    NSDictionary *_taskCountDict;
    NSString *_startDate;
    NSString *_endDate;
    NSString *_currentDateString;
    long long _page;
    SFCalendarPickerController *_calendarPickerVC;
    SFNoDataView *_noDataView;
}

@property(nonatomic) _Bool isFirstLoad; // @synthesize isFirstLoad=_isFirstLoad;
@property(retain, nonatomic) SFNoDataView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) SFCalendarPickerController *calendarPickerVC; // @synthesize calendarPickerVC=_calendarPickerVC;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *currentDateString; // @synthesize currentDateString=_currentDateString;
@property(copy, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(copy, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSDictionary *taskCountDict; // @synthesize taskCountDict=_taskCountDict;
@property(retain, nonatomic) NSMutableArray *taskArray; // @synthesize taskArray=_taskArray;
@property(retain, nonatomic) UITableView *taskTableView; // @synthesize taskTableView=_taskTableView;
@property(retain, nonatomic) UILabel *afterBadge; // @synthesize afterBadge=_afterBadge;
@property(retain, nonatomic) UIButton *afterDayBtn; // @synthesize afterDayBtn=_afterDayBtn;
@property(retain, nonatomic) UIImageView *selectImageView; // @synthesize selectImageView=_selectImageView;
@property(retain, nonatomic) UILabel *selectBadge; // @synthesize selectBadge=_selectBadge;
@property(retain, nonatomic) UILabel *selectLabel; // @synthesize selectLabel=_selectLabel;
@property(retain, nonatomic) UIButton *selectDayBtn; // @synthesize selectDayBtn=_selectDayBtn;
@property(retain, nonatomic) UILabel *beforeBadge; // @synthesize beforeBadge=_beforeBadge;
@property(retain, nonatomic) UIButton *beforeDayBtn; // @synthesize beforeDayBtn=_beforeDayBtn;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)historyList:(id)arg1;
- (void)checkPasswordExpiredDict:(id)arg1;
- (void)requestModifyPassword;
- (void)removeViewControllerFromContent:(id)arg1;
- (void)addViewControllerToContent:(id)arg1;
- (void)setSelectLabelText;
- (void)afterDayBtnAction:(id)arg1;
- (void)didSelectYear:(id)arg1 month:(id)arg2 day:(id)arg3;
- (void)renovatebeforeBtnAndAfterDayBtn;
- (void)selectDayBtnAction:(id)arg1;
- (void)beforeDayBtnAction:(id)arg1;
- (void)renovateTaskDataFromServer;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)setTaskDetailVCWithTaskId:(id)arg1 deptCode:(id)arg2 requireId:(id)arg3 fieldBak03:(long long)arg4;
- (void)renovateTaskCount;
- (void)renovateDataFromServer;
- (void)renovateMyTableView;
- (void)fetchUserDataFromServer;
- (void)fetchUserCountFromServer;
- (void)fetchExecutingDataFromServer:(_Bool)arg1;
- (void)fetchUserDataFromInfinite;
- (void)fetchUserDataFromPullDown;
- (void)fetchUserDataFromPull;
- (void)addRefreshToTableView;
- (void)initViews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

