//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFToCCargoRecordVM, SFToCMarketBidVM, UITableView;

@interface SFToCCargoFeedBackVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    UITableView *_table;
    NSMutableArray *_dataArray;
    SFToCMarketBidVM *_marketVM;
    SFToCCargoRecordVM *_cargoRecordVM;
    NSString *_vehicleCode;
    NSString *_vehicleLen;
    NSString *_lineCode;
    NSString *_startCityCode;
    NSString *_startProviceCode;
    NSString *_destCityCode;
    NSString *_destProviceCode;
}

@property(retain, nonatomic) NSString *destProviceCode; // @synthesize destProviceCode=_destProviceCode;
@property(retain, nonatomic) NSString *destCityCode; // @synthesize destCityCode=_destCityCode;
@property(retain, nonatomic) NSString *startProviceCode; // @synthesize startProviceCode=_startProviceCode;
@property(retain, nonatomic) NSString *startCityCode; // @synthesize startCityCode=_startCityCode;
@property(retain, nonatomic) NSString *lineCode; // @synthesize lineCode=_lineCode;
@property(retain, nonatomic) NSString *vehicleLen; // @synthesize vehicleLen=_vehicleLen;
@property(retain, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(retain, nonatomic) SFToCCargoRecordVM *cargoRecordVM; // @synthesize cargoRecordVM=_cargoRecordVM;
@property(retain, nonatomic) SFToCMarketBidVM *marketVM; // @synthesize marketVM=_marketVM;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)bidButActionWithModel:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)loadMoreRefresh;
- (void)pullDownRefresh;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

