//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

@class SFToCMarketBidVC, SFToCMarketOrderLineVC, UISegmentedControl;

@interface SFToCMarketVC : SFToCBaseVC
{
    long long _selectedSegmentIndex;
    UISegmentedControl *_segMentCtr;
    SFToCMarketOrderLineVC *_orderLineVC;
    SFToCMarketBidVC *_bidVC;
}

@property(retain, nonatomic) SFToCMarketBidVC *bidVC; // @synthesize bidVC=_bidVC;
@property(retain, nonatomic) SFToCMarketOrderLineVC *orderLineVC; // @synthesize orderLineVC=_orderLineVC;
@property(retain, nonatomic) UISegmentedControl *segMentCtr; // @synthesize segMentCtr=_segMentCtr;
@property(nonatomic) long long selectedSegmentIndex; // @synthesize selectedSegmentIndex=_selectedSegmentIndex;
- (void).cxx_destruct;
- (void)cargoRecord:(id)arg1;
- (void)segMentCtrChange:(id)arg1;
- (void)SFToCMarketBidVCAffirmBidArt;
- (void)segChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

