//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SFToCBidRequiredInfoModel, UIImageView, UILabel;

@interface SFToCAddVehicleHeaderView : UIView
{
    SFToCBidRequiredInfoModel *_model;
    UIView *_bgView;
    UILabel *_startPointLabel;
    UILabel *_startTimeLabel;
    UILabel *_lineDistanceLabel;
    UIImageView *_lineImageView;
    UILabel *_destPointLabel;
    UILabel *_destTimeLabel;
}

@property(retain, nonatomic) UILabel *destTimeLabel; // @synthesize destTimeLabel=_destTimeLabel;
@property(retain, nonatomic) UILabel *destPointLabel; // @synthesize destPointLabel=_destPointLabel;
@property(retain, nonatomic) UIImageView *lineImageView; // @synthesize lineImageView=_lineImageView;
@property(retain, nonatomic) UILabel *lineDistanceLabel; // @synthesize lineDistanceLabel=_lineDistanceLabel;
@property(retain, nonatomic) UILabel *startTimeLabel; // @synthesize startTimeLabel=_startTimeLabel;
@property(retain, nonatomic) UILabel *startPointLabel; // @synthesize startPointLabel=_startPointLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SFToCBidRequiredInfoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

