//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, SFToCCityModel;

@interface SFToCMarketBidVM : NSObject
{
    int _driverAuthStatus;
    int _vehicleAuthStatus;
    SFToCCityModel *_locationCity;
    NSMutableDictionary *_distanceMdict;
    NSArray *_vehicleAuthInfo;
    NSMutableArray *_dataArray;
    NSMutableArray *_responseArray;
}

@property(retain, nonatomic) NSMutableArray *responseArray; // @synthesize responseArray=_responseArray;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSArray *vehicleAuthInfo; // @synthesize vehicleAuthInfo=_vehicleAuthInfo;
@property(nonatomic) int vehicleAuthStatus; // @synthesize vehicleAuthStatus=_vehicleAuthStatus;
@property(nonatomic) int driverAuthStatus; // @synthesize driverAuthStatus=_driverAuthStatus;
@property(retain, nonatomic) NSMutableDictionary *distanceMdict; // @synthesize distanceMdict=_distanceMdict;
@property(retain, nonatomic) SFToCCityModel *locationCity; // @synthesize locationCity=_locationCity;
- (void).cxx_destruct;
- (_Bool)isAuthUser;
- (void)queryUserAuthStatus;
- (id)getHistoryCityWithType:(long long)arg1;
- (void)saveHistoryCity:(id)arg1 withType:(long long)arg2;
- (id)getDataArray;
- (void)requestDateWithParam:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestUnloginDateSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)init;

@end

