//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFNewNavigationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface SFToCEmptySourceListVC : SFToCBaseVC <UITableViewDataSource, UITableViewDelegate, SFNewNavigationControllerDelegate>
{
    NSString *_idleStartTime;
    NSString *_idleEndTime;
    NSString *_from;
    NSString *_to;
    long long _type;
    long long _idleDay;
    UITableView *_tableView;
    NSMutableArray *_dataArr;
    long long _refreshType;
    UIView *_tableHeaderView;
}

@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(nonatomic) long long refreshType; // @synthesize refreshType=_refreshType;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long idleDay; // @synthesize idleDay=_idleDay;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *to; // @synthesize to=_to;
@property(copy, nonatomic) NSString *from; // @synthesize from=_from;
@property(copy, nonatomic) NSString *idleEndTime; // @synthesize idleEndTime=_idleEndTime;
@property(copy, nonatomic) NSString *idleStartTime; // @synthesize idleStartTime=_idleStartTime;
- (void).cxx_destruct;
- (void)gatherList:(id)arg1 pageIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)reloadTableView;
- (void)gatherGroundTbpIdleOrderList:(_Bool)arg1;
- (void)requestDateWithParam;
- (void)pullDownRefresh;
- (void)initUI;
- (void)navigationWillPop;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

