//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;
@protocol SFToCNoLoginHeaderViewDelegate;

@interface SFToCNoLoginHeaderView : UIView
{
    UIImageView *_bgImagView;
    NSString *_userName;
    id <SFToCNoLoginHeaderViewDelegate> _delegate;
    UILabel *_nameLab;
    UIImageView *_icon;
}

@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(nonatomic) __weak id <SFToCNoLoginHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) UIImageView *bgImagView; // @synthesize bgImagView=_bgImagView;
- (void).cxx_destruct;
- (void)refreshLoginStatus;
- (void)loginAction;
- (id)initWithFrame:(struct CGRect)arg1;

@end

