//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SFToCCityModel, SFToCLocationService, SFToCMarketCityFilter, SFToCMarketFilterView, SFToCMarketNearbyModel, SFToCMarketVehicleLineFilter, SFToCTransactionForecastVM, UITableView;

@interface SFToCTransactionForecastVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    UITableView *_table;
    SFToCTransactionForecastVM *_transactionForecastVM;
    SFToCMarketFilterView *_filterView;
    unsigned long long _filterType;
    SFToCMarketCityFilter *_filterStartCityView;
    SFToCMarketCityFilter *_filterDesCityView;
    SFToCMarketVehicleLineFilter *_filterVehicleLineView;
    NSString *_vehicleCode;
    NSString *_vehicleLen;
    NSString *_lineCode;
    NSString *_startCityCode;
    NSString *_startProviceCode;
    NSString *_destCityCode;
    NSString *_destProviceCode;
    NSString *_orderType;
    NSString *_startDate;
    SFToCMarketNearbyModel *_nearbyModel;
    SFToCCityModel *_locationCity;
    SFToCLocationService *_locationService;
}

@property(retain, nonatomic) SFToCLocationService *locationService; // @synthesize locationService=_locationService;
@property(retain, nonatomic) SFToCCityModel *locationCity; // @synthesize locationCity=_locationCity;
@property(retain, nonatomic) SFToCMarketNearbyModel *nearbyModel; // @synthesize nearbyModel=_nearbyModel;
@property(retain, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSString *orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *destProviceCode; // @synthesize destProviceCode=_destProviceCode;
@property(retain, nonatomic) NSString *destCityCode; // @synthesize destCityCode=_destCityCode;
@property(retain, nonatomic) NSString *startProviceCode; // @synthesize startProviceCode=_startProviceCode;
@property(retain, nonatomic) NSString *startCityCode; // @synthesize startCityCode=_startCityCode;
@property(retain, nonatomic) NSString *lineCode; // @synthesize lineCode=_lineCode;
@property(retain, nonatomic) NSString *vehicleLen; // @synthesize vehicleLen=_vehicleLen;
@property(retain, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(retain, nonatomic) SFToCMarketVehicleLineFilter *filterVehicleLineView; // @synthesize filterVehicleLineView=_filterVehicleLineView;
@property(retain, nonatomic) SFToCMarketCityFilter *filterDesCityView; // @synthesize filterDesCityView=_filterDesCityView;
@property(retain, nonatomic) SFToCMarketCityFilter *filterStartCityView; // @synthesize filterStartCityView=_filterStartCityView;
@property(nonatomic) unsigned long long filterType; // @synthesize filterType=_filterType;
@property(retain, nonatomic) SFToCMarketFilterView *filterView; // @synthesize filterView=_filterView;
@property(retain, nonatomic) SFToCTransactionForecastVM *transactionForecastVM; // @synthesize transactionForecastVM=_transactionForecastVM;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
- (void).cxx_destruct;
- (void)dealloc;
- (void)gatherList:(id)arg1 pageIndex:(long long)arg2;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)cancelRemindWithModel:(id)arg1;
- (void)remindMeWithModel:(id)arg1;
- (void)bidButActionWithModel:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)gatherGroundTbpTradeForenoticeListWithDataArr:(id)arg1;
- (void)loadMoreRefresh;
- (void)pullDownRefresh;
- (void)relocation:(id)arg1;
- (void)showFilterTypeView;
- (void)closeFilterTypeView;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

