//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, UIView;

@interface SFToCMarketDelFilterCell : UITableViewCell
{
    CDUnknownBlockType _delFilterBlock;
    NSArray *_selectedCityArray;
    UIView *_bgView;
}

+ (double)getCellHeightWithSelectedCityArray:(id)arg1;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) NSArray *selectedCityArray; // @synthesize selectedCityArray=_selectedCityArray;
@property(copy, nonatomic) CDUnknownBlockType delFilterBlock; // @synthesize delFilterBlock=_delFilterBlock;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)delAction:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

