//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SFToCBidRemarkModel, UIButton, UILabel;

@interface SFToCBidRemarkView : UIView
{
    SFToCBidRemarkModel *_remarkModel;
    UILabel *_attributeLabel;
    UIButton *_gpsBtn;
    UILabel *_remarkLabel;
    UILabel *_demandLabel;
}

@property(retain, nonatomic) UILabel *demandLabel; // @synthesize demandLabel=_demandLabel;
@property(retain, nonatomic) UILabel *remarkLabel; // @synthesize remarkLabel=_remarkLabel;
@property(retain, nonatomic) UIButton *gpsBtn; // @synthesize gpsBtn=_gpsBtn;
@property(retain, nonatomic) UILabel *attributeLabel; // @synthesize attributeLabel=_attributeLabel;
@property(retain, nonatomic) SFToCBidRemarkModel *remarkModel; // @synthesize remarkModel=_remarkModel;
- (void).cxx_destruct;
- (void)gpsBtnAction;
- (void)layoutSubviews;
- (void)setupUI;
- (id)init;

@end

