//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFToCAccountInfoModel : JSONModel
{
    long long _accountId;
    long long _accountType;
    NSString *_availableBalance;
    NSString *_freezingBalance;
    long long _status;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *freezingBalance; // @synthesize freezingBalance=_freezingBalance;
@property(retain, nonatomic) NSString *availableBalance; // @synthesize availableBalance=_availableBalance;
@property(nonatomic) long long accountType; // @synthesize accountType=_accountType;
@property(nonatomic) long long accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;

@end

