//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SFToCDriverInfo, UIImageView, UILabel;
@protocol SFToCDriverVerifiedHeaderDelegate;

@interface SFToCDriverVerifiedHeader : UIView
{
    SFToCDriverInfo *_driverModel;
    id <SFToCDriverVerifiedHeaderDelegate> _delegate;
    UILabel *_driverNameLab;
    UILabel *_driverIDCardLab;
    UILabel *_idCardAndLicenceStatusLab;
    UIImageView *_statusImageV;
    UILabel *_employmentStatusLab;
}

@property(retain, nonatomic) UILabel *employmentStatusLab; // @synthesize employmentStatusLab=_employmentStatusLab;
@property(retain, nonatomic) UIImageView *statusImageV; // @synthesize statusImageV=_statusImageV;
@property(retain, nonatomic) UILabel *idCardAndLicenceStatusLab; // @synthesize idCardAndLicenceStatusLab=_idCardAndLicenceStatusLab;
@property(retain, nonatomic) UILabel *driverIDCardLab; // @synthesize driverIDCardLab=_driverIDCardLab;
@property(retain, nonatomic) UILabel *driverNameLab; // @synthesize driverNameLab=_driverNameLab;
@property(nonatomic) __weak id <SFToCDriverVerifiedHeaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SFToCDriverInfo *driverModel; // @synthesize driverModel=_driverModel;
- (void).cxx_destruct;
- (void)queryEmploymentInfo;
- (void)queryDriverInfo;
- (void)initUI;
- (id)init;

@end

