//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSNumber, NSString, UILabel, UITextField;
@protocol SFToCWithdrawCellDelegate;

@interface SFToCWithdrawCell : UITableViewCell <UITextFieldDelegate>
{
    _Bool _isHaveDian;
    id <SFToCWithdrawCellDelegate> _delegate;
    UITextField *_textField;
    NSString *_cardNum;
    UILabel *_titleLabel;
    NSNumber *_limitWithdraw;
}

+ (double)cellHeight;
@property(nonatomic) _Bool isHaveDian; // @synthesize isHaveDian=_isHaveDian;
@property(retain, nonatomic) NSNumber *limitWithdraw; // @synthesize limitWithdraw=_limitWithdraw;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *cardNum; // @synthesize cardNum=_cardNum;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) __weak id <SFToCWithdrawCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)formatterBankCardNum:(id)arg1;
- (void)textFieldChange:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)initWithDataArr:(id)arg1 indexPath:(id)arg2;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

