//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFTrackTabBarVC.h"

#import "SFAbnormalHandelVCDelegate-Protocol.h"
#import "SFToCTabBarDelegate-Protocol.h"

@class NSString, SFHomepageVC, SFInforModel, SFScreenShotManager, SFToCMarketVC, SFToCMineVC, SFToCOrderSegmentVC, SFToCTabBar;

@interface SFToCTabBarController : SFTrackTabBarVC <SFAbnormalHandelVCDelegate, SFToCTabBarDelegate>
{
    SFHomepageVC *_homepageVC;
    SFToCMarketVC *_marketVC;
    SFToCMineVC *_mineVC;
    SFToCOrderSegmentVC *_orderVC;
    SFScreenShotManager *_screenShotManager;
    SFToCTabBar *_toCTabBar;
    SFInforModel *_oldModel;
}

@property(retain, nonatomic) SFInforModel *oldModel; // @synthesize oldModel=_oldModel;
@property(retain, nonatomic) SFToCTabBar *toCTabBar; // @synthesize toCTabBar=_toCTabBar;
@property(retain, nonatomic) SFScreenShotManager *screenShotManager; // @synthesize screenShotManager=_screenShotManager;
@property(retain, nonatomic) SFToCOrderSegmentVC *orderVC; // @synthesize orderVC=_orderVC;
@property(retain, nonatomic) SFToCMineVC *mineVC; // @synthesize mineVC=_mineVC;
@property(retain, nonatomic) SFToCMarketVC *marketVC; // @synthesize marketVC=_marketVC;
@property(retain, nonatomic) SFHomepageVC *homepageVC; // @synthesize homepageVC=_homepageVC;
- (void).cxx_destruct;
- (void)pushTaskDetailDict:(id)arg1;
- (void)refreshMessage:(id)arg1;
- (void)clean;
- (void)addButtonClick:(id)arg1;
- (void)removeFloatingSubView;
- (void)addScreenShotShare;
- (void)unFinisDetailReload;
- (void)showPermitAlertViewMessage:(id)arg1;
- (void)showNotificationInfo:(id)arg1;
- (void)clickMessage:(id)arg1;
- (void)tabbarJumpToOrderLinePage:(id)arg1;
- (void)tabBarJumpToPersonalProfile:(id)arg1;
- (void)tabBarJumpToMyWallet:(id)arg1;
- (void)tabBarJumpToTaskDetail:(id)arg1;
- (void)tabBarJumpToOrderPage:(id)arg1;
- (void)tabBarJumpToMarketPage:(id)arg1;
- (void)tabBarJumpToHomePage:(id)arg1;
- (void)resetHomePageLoad;
- (void)addchildWithChildViewController:(id)arg1 title:(id)arg2 image:(id)arg3 selectedImage:(id)arg4;
- (void)addChildViewController;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

