//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFToCPermitmodel : JSONModel
{
    NSString *_itemname;
    NSString *_itemcode;
    NSString *_remark;
    NSString *_placeholder;
    long long _inputType;
    long long _cellType;
    long long _isRequired;
    long long _keyboardType;
    long long _isAllowModify;
    long long _length;
    double _cellHeight;
    NSString *_typeCode;
    NSString *_idDriverId;
    NSString *_idCard;
    NSString *_idName;
    NSString *_idPositiveImgUrl;
    NSString *_idSideImgUrl;
    NSString *_leftTitle;
    NSString *_rightTitle;
    long long _imageNum;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(nonatomic) long long imageNum; // @synthesize imageNum=_imageNum;
@property(copy, nonatomic) NSString *rightTitle; // @synthesize rightTitle=_rightTitle;
@property(copy, nonatomic) NSString *leftTitle; // @synthesize leftTitle=_leftTitle;
@property(copy, nonatomic) NSString *idSideImgUrl; // @synthesize idSideImgUrl=_idSideImgUrl;
@property(copy, nonatomic) NSString *idPositiveImgUrl; // @synthesize idPositiveImgUrl=_idPositiveImgUrl;
@property(copy, nonatomic) NSString *idName; // @synthesize idName=_idName;
@property(copy, nonatomic) NSString *idCard; // @synthesize idCard=_idCard;
@property(copy, nonatomic) NSString *idDriverId; // @synthesize idDriverId=_idDriverId;
@property(copy, nonatomic) NSString *typeCode; // @synthesize typeCode=_typeCode;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(nonatomic) long long length; // @synthesize length=_length;
@property(nonatomic) long long isAllowModify; // @synthesize isAllowModify=_isAllowModify;
@property(nonatomic) long long keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) long long isRequired; // @synthesize isRequired=_isRequired;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) long long inputType; // @synthesize inputType=_inputType;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(copy, nonatomic) NSString *itemcode; // @synthesize itemcode=_itemcode;
@property(copy, nonatomic) NSString *itemname; // @synthesize itemname=_itemname;
- (void).cxx_destruct;

@end

