//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface SFToCHeadView : UIView
{
    UIImageView *_bgView;
    UILabel *_titleLab;
    UILabel *_timeLab;
    UIImageView *_imagView;
    UILabel *_messageLab;
    UILabel *_remarkLab;
}

@property(retain, nonatomic) UILabel *remarkLab; // @synthesize remarkLab=_remarkLab;
@property(retain, nonatomic) UILabel *messageLab; // @synthesize messageLab=_messageLab;
@property(retain, nonatomic) UIImageView *imagView; // @synthesize imagView=_imagView;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 message:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 dataModel:(id)arg2 permitType:(unsigned long long)arg3;

@end

