//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SFToCPermitData;

@interface SFToCPermitmVM : NSObject
{
    SFToCPermitData *_dataModel;
}

@property(copy, nonatomic) SFToCPermitData *dataModel; // @synthesize dataModel=_dataModel;
- (void).cxx_destruct;
- (void)queryDriverOrVehicleType:(long long)arg1 iD:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)saveDriverOrVehicleParam:(id)arg1 type:(unsigned long long)arg2 status:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)ocrIdentifyParam:(id)arg1 type:(unsigned long long)arg2 status:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;

@end

