//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SFTocCalendarViewCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, SFDatePickerModel, UICollectionView, UILabel;
@protocol SFTocCalendarViewDelegate;

@interface SFTocCalendarView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, SFTocCalendarViewCellDelegate>
{
    UILabel *_monthLabel;
    UILabel *_yearLabel;
    _Bool _isFrist;
    id <SFTocCalendarViewDelegate> _delegate;
    UICollectionView *_myCollectionView;
    NSMutableArray *_yearArray;
    NSMutableArray *_monthArray;
    NSMutableDictionary *_orderDict;
    SFDatePickerModel *_currentDateModel;
    SFDatePickerModel *_maxDateModel;
    SFDatePickerModel *_minDateModel;
    long long _minDateYear;
    long long _maxDateYear;
}

@property(nonatomic) _Bool isFrist; // @synthesize isFrist=_isFrist;
@property(nonatomic) long long maxDateYear; // @synthesize maxDateYear=_maxDateYear;
@property(nonatomic) long long minDateYear; // @synthesize minDateYear=_minDateYear;
@property(retain, nonatomic) SFDatePickerModel *minDateModel; // @synthesize minDateModel=_minDateModel;
@property(retain, nonatomic) SFDatePickerModel *maxDateModel; // @synthesize maxDateModel=_maxDateModel;
@property(retain, nonatomic) SFDatePickerModel *currentDateModel; // @synthesize currentDateModel=_currentDateModel;
@property(retain, nonatomic) NSMutableDictionary *orderDict; // @synthesize orderDict=_orderDict;
@property(retain, nonatomic) NSMutableArray *monthArray; // @synthesize monthArray=_monthArray;
@property(retain, nonatomic) NSMutableArray *yearArray; // @synthesize yearArray=_yearArray;
@property(retain, nonatomic) UICollectionView *myCollectionView; // @synthesize myCollectionView=_myCollectionView;
@property(nonatomic) __weak id <SFTocCalendarViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)ishave:(id)arg1;
- (void)addBtnAction:(id)arg1;
- (void)didSelectTocCalendarModel:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)dateFromString:(id)arg1 withFormat:(id)arg2;
- (long long)getWeekDayWithYear:(id)arg1 month:(id)arg2 day:(id)arg3;
- (id)getDateStringWithTime:(id)arg1 formatStr:(id)arg2;
- (double)getDateWithDateStr:(id)arg1 formatStr:(id)arg2;
- (id)setdayArrayWithDays:(long long)arg1 fristWeekDay:(long long)arg2 lastWeekDay:(long long)arg3 year:(long long)arg4 month:(long long)arg5;
- (void)setMinLimit:(id)arg1;
- (void)setMaxLimit:(id)arg1;
- (void)collectionviewLayoutView;
- (void)layoutSubviews;
- (void)refreshCalendarWithOrderDict:(id)arg1;
- (void)initViews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

