//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, SFToCOrderAbnormalView, SFToCOrderInfoListView, SFToCOrderLineListView, SFToCOrderModel, UIImageView, UILabel, UIView;

@interface SFToCOrderCompletedCell : UITableViewCell
{
    SFToCOrderModel *_model;
    CDUnknownBlockType _block;
    UIView *_bgView;
    UIImageView *_settleIcon;
    UIView *_withdrawTimeView;
    UILabel *_withdrawTimeLa;
    SFToCOrderLineListView *_lineView;
    SFToCOrderInfoListView *_attributeView;
    NSArray *_orderAttributeArray;
    SFToCOrderAbnormalView *_orderAbnormalView;
}

+ (double)getCellHeight:(id)arg1;
@property(retain, nonatomic) SFToCOrderAbnormalView *orderAbnormalView; // @synthesize orderAbnormalView=_orderAbnormalView;
@property(retain, nonatomic) NSArray *orderAttributeArray; // @synthesize orderAttributeArray=_orderAttributeArray;
@property(retain, nonatomic) SFToCOrderInfoListView *attributeView; // @synthesize attributeView=_attributeView;
@property(retain, nonatomic) SFToCOrderLineListView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *withdrawTimeLa; // @synthesize withdrawTimeLa=_withdrawTimeLa;
@property(retain, nonatomic) UIView *withdrawTimeView; // @synthesize withdrawTimeView=_withdrawTimeView;
@property(retain, nonatomic) UIImageView *settleIcon; // @synthesize settleIcon=_settleIcon;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) SFToCOrderModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutView;
- (void)orderAbnormalAction;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

