//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFToCDepositManageModel, SFToCPayMentMethodCell, UIButton, UIImageView, UILabel, UITableView;

@interface SFToCBondAlertView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    SFToCPayMentMethodCell *_choiceCell;
    CDUnknownBlockType _block;
    SFToCDepositManageModel *_model;
    UIView *_bgView;
    UIView *_headerView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UITableView *_table;
    NSMutableArray *_paymentArray;
    UIButton *_paymentBtn;
    UIButton *_cancelBut;
    long long _orderId;
}

@property(nonatomic) long long orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) UIButton *cancelBut; // @synthesize cancelBut=_cancelBut;
@property(retain, nonatomic) UIButton *paymentBtn; // @synthesize paymentBtn=_paymentBtn;
@property(retain, nonatomic) NSMutableArray *paymentArray; // @synthesize paymentArray=_paymentArray;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SFToCDepositManageModel *model; // @synthesize model=_model;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (id)appRootViewController;
- (void)show;
- (void)hidden;
- (void)cancelAction;
- (id)getPayMethod:(id)arg1;
- (void)WXApi:(id)arg1;
- (void)wechatPay;
- (void)yuePay;
- (void)paymentAction;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)dealloc;
- (void)setupUI;
- (void)cancelPaymentOrder:(CDUnknownBlockType)arg1;
- (void)wxOtherError;
- (void)wxFailureError;
- (void)wxSuccess;
- (void)wxCancelError;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

