//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFLocationServiceDelegate-Protocol.h"
#import "SFToCEmptyPickListCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface SFToCEmptyPickListVC : SFToCBaseVC <UITableViewDataSource, UITableViewDelegate, SFToCEmptyPickListCellDelegate, SFLocationServiceDelegate>
{
    UITableView *_bgTableView;
    NSMutableArray *_dataArr;
    UIView *_tableFooterView;
}

@property(retain, nonatomic) UIView *tableFooterView; // @synthesize tableFooterView=_tableFooterView;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) UITableView *bgTableView; // @synthesize bgTableView=_bgTableView;
- (void).cxx_destruct;
- (void)gatherGroundTbpIdleItem;
- (void)queryPick:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)gatherGroundTbpIdleAdd;
- (void)addEmptyPick;
- (void)sf_didUpdateUserLocation:(id)arg1;
- (void)getListDataWithCityCode:(id)arg1;
- (void)getLocationCityCodeWithCityName:(id)arg1;
- (void)getLocation;
- (void)pullDownRefresh;
- (void)initUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

