//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFToCAccountFlowWaterInfoModel, UILabel, UITableView, UIView;
@protocol SFToCFreezingAmountVCDelegate;

@interface SFToCFreezingAmountVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    id <SFToCFreezingAmountVCDelegate> _delegate;
    UITableView *_tableView;
    UIView *_tableViewHeaderView;
    UIView *_tableViewHeaderBackView;
    UILabel *_tableViewHeaderLabel;
    long long _page;
    SFToCAccountFlowWaterInfoModel *_accountFlowWaterInfoModel;
    NSMutableArray *_dataArr;
}

@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) SFToCAccountFlowWaterInfoModel *accountFlowWaterInfoModel; // @synthesize accountFlowWaterInfoModel=_accountFlowWaterInfoModel;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) UILabel *tableViewHeaderLabel; // @synthesize tableViewHeaderLabel=_tableViewHeaderLabel;
@property(retain, nonatomic) UIView *tableViewHeaderBackView; // @synthesize tableViewHeaderBackView=_tableViewHeaderBackView;
@property(retain, nonatomic) UIView *tableViewHeaderView; // @synthesize tableViewHeaderView=_tableViewHeaderView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <SFToCFreezingAmountVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)renovateUIByArray:(id)arg1;
- (void)loadMoreRefresh;
- (void)pullDownRefresh;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

