//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

@class NSString, UIButton, UILabel, UIView;
@protocol SFToCExactRecommendVCDelegate;

@interface SFToCExactRecommendVC : SFToCBaseVC
{
    id <SFToCExactRecommendVCDelegate> _delegate;
    CDUnknownBlockType _onBlock;
    UIButton *_mactchBtn;
    UIView *_placeView;
    UILabel *_startLab;
    UILabel *_destLab;
    NSString *_startProvinceCode;
    NSString *_startCityCode;
    NSString *_desProvinceCode;
    NSString *_desCityCode;
}

@property(copy, nonatomic) NSString *desCityCode; // @synthesize desCityCode=_desCityCode;
@property(copy, nonatomic) NSString *desProvinceCode; // @synthesize desProvinceCode=_desProvinceCode;
@property(copy, nonatomic) NSString *startCityCode; // @synthesize startCityCode=_startCityCode;
@property(copy, nonatomic) NSString *startProvinceCode; // @synthesize startProvinceCode=_startProvinceCode;
@property(retain, nonatomic) UILabel *destLab; // @synthesize destLab=_destLab;
@property(retain, nonatomic) UILabel *startLab; // @synthesize startLab=_startLab;
@property(retain, nonatomic) UIView *placeView; // @synthesize placeView=_placeView;
@property(retain, nonatomic) UIButton *mactchBtn; // @synthesize mactchBtn=_mactchBtn;
@property(copy, nonatomic) CDUnknownBlockType onBlock; // @synthesize onBlock=_onBlock;
@property(nonatomic) __weak id <SFToCExactRecommendVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)refreshButtonStatus;
- (void)desLabelTap;
- (void)startLabelTap;
- (void)startRecommandClick:(id)arg1;
- (void)saveSubscriptionLineToServer;
- (void)createUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

