//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SFToCMarketBidAlert : UIView
{
    CDUnknownBlockType _onBlock;
}

+ (void)showWithBtnTitle:(id)arg1 imageName:(id)arg2 andBlock:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType onBlock; // @synthesize onBlock=_onBlock;
- (void).cxx_destruct;
- (id)appRootViewController;
- (void)close;
- (void)btnClick;
- (id)initWithBtnTitle:(id)arg1 imageName:(id)arg2 andBlock:(CDUnknownBlockType)arg3;

@end

