//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray;
@protocol SFToCLineModel><Optional;

@interface SFToCBidGroupLineInfo : JSONModel
{
    long long _biddingId;
    long long _totalLineSize;
    long long _tradeLineSize;
    NSMutableArray<SFToCLineModel><Optional> *_tradedLineInfo;
    NSMutableArray<SFToCLineModel><Optional> *_tradingLineInfo;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSMutableArray<SFToCLineModel><Optional> *tradingLineInfo; // @synthesize tradingLineInfo=_tradingLineInfo;
@property(retain, nonatomic) NSMutableArray<SFToCLineModel><Optional> *tradedLineInfo; // @synthesize tradedLineInfo=_tradedLineInfo;
@property(nonatomic) long long tradeLineSize; // @synthesize tradeLineSize=_tradeLineSize;
@property(nonatomic) long long totalLineSize; // @synthesize totalLineSize=_totalLineSize;
@property(nonatomic) long long biddingId; // @synthesize biddingId=_biddingId;
- (void).cxx_destruct;

@end

