//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFToCAccountFlowWaterModel : JSONModel
{
    NSString *_id;
    NSString *_accountId;
    NSString *_billDetailId;
    NSString *_tradeSerialNumber;
    NSString *_tradeSource;
    NSString *_tradeDate;
    NSString *_tradeFlowNumber;
    NSString *_tradeType;
    NSString *_tradeExplain;
    NSString *_operateType;
    NSString *_operateAmount;
    NSString *_freezingOperateType;
    NSString *_freezingOperateAmount;
    NSString *_historyBalance;
    NSString *_availableBalance;
    NSString *_totalBalance;
    NSString *_freezingBalance;
    NSString *_remark;
    NSString *_createTime;
    NSString *_createUser;
    NSString *_modifyTm;
    NSString *_modifyUser;
    NSString *_errorMsg;
    NSString *_amountProcessed;
    NSString *_destName;
    NSString *_srcName;
    NSString *_freezingOperateAmountStr;
    NSString *_operateAmountStr;
    NSString *_title;
    NSString *_expectedThawingTime;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *expectedThawingTime; // @synthesize expectedThawingTime=_expectedThawingTime;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *operateAmountStr; // @synthesize operateAmountStr=_operateAmountStr;
@property(retain, nonatomic) NSString *freezingOperateAmountStr; // @synthesize freezingOperateAmountStr=_freezingOperateAmountStr;
@property(retain, nonatomic) NSString *srcName; // @synthesize srcName=_srcName;
@property(retain, nonatomic) NSString *destName; // @synthesize destName=_destName;
@property(retain, nonatomic) NSString *amountProcessed; // @synthesize amountProcessed=_amountProcessed;
@property(retain, nonatomic) NSString *errorMsg; // @synthesize errorMsg=_errorMsg;
@property(retain, nonatomic) NSString *modifyUser; // @synthesize modifyUser=_modifyUser;
@property(retain, nonatomic) NSString *modifyTm; // @synthesize modifyTm=_modifyTm;
@property(retain, nonatomic) NSString *createUser; // @synthesize createUser=_createUser;
@property(retain, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(retain, nonatomic) NSString *freezingBalance; // @synthesize freezingBalance=_freezingBalance;
@property(retain, nonatomic) NSString *totalBalance; // @synthesize totalBalance=_totalBalance;
@property(retain, nonatomic) NSString *availableBalance; // @synthesize availableBalance=_availableBalance;
@property(retain, nonatomic) NSString *historyBalance; // @synthesize historyBalance=_historyBalance;
@property(retain, nonatomic) NSString *freezingOperateAmount; // @synthesize freezingOperateAmount=_freezingOperateAmount;
@property(retain, nonatomic) NSString *freezingOperateType; // @synthesize freezingOperateType=_freezingOperateType;
@property(retain, nonatomic) NSString *operateAmount; // @synthesize operateAmount=_operateAmount;
@property(retain, nonatomic) NSString *operateType; // @synthesize operateType=_operateType;
@property(retain, nonatomic) NSString *tradeExplain; // @synthesize tradeExplain=_tradeExplain;
@property(retain, nonatomic) NSString *tradeType; // @synthesize tradeType=_tradeType;
@property(retain, nonatomic) NSString *tradeFlowNumber; // @synthesize tradeFlowNumber=_tradeFlowNumber;
@property(retain, nonatomic) NSString *tradeDate; // @synthesize tradeDate=_tradeDate;
@property(retain, nonatomic) NSString *tradeSource; // @synthesize tradeSource=_tradeSource;
@property(retain, nonatomic) NSString *tradeSerialNumber; // @synthesize tradeSerialNumber=_tradeSerialNumber;
@property(retain, nonatomic) NSString *billDetailId; // @synthesize billDetailId=_billDetailId;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

