//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray, NSString;
@protocol SFToCLineModel><Optional;

@interface SFToCCargoRecordModel : JSONModel
{
    NSString *_biddingId;
    NSString *_biddingType;
    NSString *_price;
    NSString *_biddingEndTm;
    NSString *_orderType;
    NSString *_planGainPrice;
    NSString *_packStartTm;
    NSString *_packEndTm;
    NSMutableArray<SFToCLineModel><Optional> *_lineInfo;
    NSString *_totalKm;
    NSString *_feeDto;
    NSString *_totalPrice;
    NSString *_isStop;
    NSString *_orderId;
    NSString *_priceStr;
    NSString *_planGainPriceStr;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSString *planGainPriceStr; // @synthesize planGainPriceStr=_planGainPriceStr;
@property(retain, nonatomic) NSString *priceStr; // @synthesize priceStr=_priceStr;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSString *isStop; // @synthesize isStop=_isStop;
@property(retain, nonatomic) NSString *totalPrice; // @synthesize totalPrice=_totalPrice;
@property(retain, nonatomic) NSString *feeDto; // @synthesize feeDto=_feeDto;
@property(retain, nonatomic) NSString *totalKm; // @synthesize totalKm=_totalKm;
@property(retain, nonatomic) NSMutableArray<SFToCLineModel><Optional> *lineInfo; // @synthesize lineInfo=_lineInfo;
@property(retain, nonatomic) NSString *packEndTm; // @synthesize packEndTm=_packEndTm;
@property(retain, nonatomic) NSString *packStartTm; // @synthesize packStartTm=_packStartTm;
@property(retain, nonatomic) NSString *planGainPrice; // @synthesize planGainPrice=_planGainPrice;
@property(retain, nonatomic) NSString *orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *biddingEndTm; // @synthesize biddingEndTm=_biddingEndTm;
@property(retain, nonatomic) NSString *price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *biddingType; // @synthesize biddingType=_biddingType;
@property(retain, nonatomic) NSString *biddingId; // @synthesize biddingId=_biddingId;
- (void).cxx_destruct;

@end

