//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFToCDriverInfo : JSONModel
{
    _Bool _practCertDtEmptyFlag;
    NSString *_birthday;
    NSString *_modifyTm;
    NSString *_modifier;
    NSString *_hkMobilephone;
    NSString *_idCardOppositePath;
    NSString *_driverStatus;
    NSString *_emerContactPhone;
    NSString *_createTm;
    NSString *_driverLicenseRecord;
    NSString *_practCertLicenseDt;
    NSString *_mobilephone;
    NSString *_driverLicense;
    NSString *_idCardFrontName;
    NSString *_healthCertEndDt;
    NSString *_idCardOppositeName;
    NSString *_creator;
    NSString *_driverLicenseName;
    NSString *_bizArea;
    NSString *_licenseEndDt;
    NSString *_sex;
    NSString *_userName;
    NSString *_firstLicenseDt;
    NSString *_userId;
    NSString *_healthCertBeginDt;
    NSString *_idCardFrontPath;
    NSString *_driverId;
    NSString *_practCertEndDt;
    NSString *_hasHealthCert;
    NSString *_driverLicensePath;
    NSString *_name;
    NSString *_idCardNum;
    NSString *_practCertType;
    NSString *_drivingType;
    NSString *_drivePractCertNum;
    NSString *_emerContact;
    NSString *_practCertStatus;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(nonatomic) _Bool practCertDtEmptyFlag; // @synthesize practCertDtEmptyFlag=_practCertDtEmptyFlag;
@property(copy, nonatomic) NSString *practCertStatus; // @synthesize practCertStatus=_practCertStatus;
@property(copy, nonatomic) NSString *emerContact; // @synthesize emerContact=_emerContact;
@property(copy, nonatomic) NSString *drivePractCertNum; // @synthesize drivePractCertNum=_drivePractCertNum;
@property(copy, nonatomic) NSString *drivingType; // @synthesize drivingType=_drivingType;
@property(copy, nonatomic) NSString *practCertType; // @synthesize practCertType=_practCertType;
@property(copy, nonatomic) NSString *idCardNum; // @synthesize idCardNum=_idCardNum;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *driverLicensePath; // @synthesize driverLicensePath=_driverLicensePath;
@property(copy, nonatomic) NSString *hasHealthCert; // @synthesize hasHealthCert=_hasHealthCert;
@property(copy, nonatomic) NSString *practCertEndDt; // @synthesize practCertEndDt=_practCertEndDt;
@property(copy, nonatomic) NSString *driverId; // @synthesize driverId=_driverId;
@property(copy, nonatomic) NSString *idCardFrontPath; // @synthesize idCardFrontPath=_idCardFrontPath;
@property(copy, nonatomic) NSString *healthCertBeginDt; // @synthesize healthCertBeginDt=_healthCertBeginDt;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *firstLicenseDt; // @synthesize firstLicenseDt=_firstLicenseDt;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *sex; // @synthesize sex=_sex;
@property(copy, nonatomic) NSString *licenseEndDt; // @synthesize licenseEndDt=_licenseEndDt;
@property(copy, nonatomic) NSString *bizArea; // @synthesize bizArea=_bizArea;
@property(copy, nonatomic) NSString *driverLicenseName; // @synthesize driverLicenseName=_driverLicenseName;
@property(copy, nonatomic) NSString *creator; // @synthesize creator=_creator;
@property(copy, nonatomic) NSString *idCardOppositeName; // @synthesize idCardOppositeName=_idCardOppositeName;
@property(copy, nonatomic) NSString *healthCertEndDt; // @synthesize healthCertEndDt=_healthCertEndDt;
@property(copy, nonatomic) NSString *idCardFrontName; // @synthesize idCardFrontName=_idCardFrontName;
@property(copy, nonatomic) NSString *driverLicense; // @synthesize driverLicense=_driverLicense;
@property(copy, nonatomic) NSString *mobilephone; // @synthesize mobilephone=_mobilephone;
@property(copy, nonatomic) NSString *practCertLicenseDt; // @synthesize practCertLicenseDt=_practCertLicenseDt;
@property(copy, nonatomic) NSString *driverLicenseRecord; // @synthesize driverLicenseRecord=_driverLicenseRecord;
@property(copy, nonatomic) NSString *createTm; // @synthesize createTm=_createTm;
@property(copy, nonatomic) NSString *emerContactPhone; // @synthesize emerContactPhone=_emerContactPhone;
@property(copy, nonatomic) NSString *driverStatus; // @synthesize driverStatus=_driverStatus;
@property(copy, nonatomic) NSString *idCardOppositePath; // @synthesize idCardOppositePath=_idCardOppositePath;
@property(copy, nonatomic) NSString *hkMobilephone; // @synthesize hkMobilephone=_hkMobilephone;
@property(copy, nonatomic) NSString *modifier; // @synthesize modifier=_modifier;
@property(copy, nonatomic) NSString *modifyTm; // @synthesize modifyTm=_modifyTm;
@property(copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
- (void).cxx_destruct;

@end

