//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

@class NSMutableArray, NSString, UIButton, UIScrollView, UIView;

@interface SFToCSelectCarStyleVC : SFToCBaseVC
{
    NSString *_vehicleLength;
    NSString *_vehicleType;
    CDUnknownBlockType _block;
    UIScrollView *_bgScrollView;
    UIButton *_confirmBtn;
    NSMutableArray *_carShapes;
    long long _selectCarShapeIndex;
    NSMutableArray *_carLengths;
    long long _selectCarLengthIndex;
    NSMutableArray *_typeMapLens;
    UIView *_carShapeView;
    UIView *_carLengthView;
    UIView *_carRuleView;
}

@property(retain, nonatomic) UIView *carRuleView; // @synthesize carRuleView=_carRuleView;
@property(retain, nonatomic) UIView *carLengthView; // @synthesize carLengthView=_carLengthView;
@property(retain, nonatomic) UIView *carShapeView; // @synthesize carShapeView=_carShapeView;
@property(retain, nonatomic) NSMutableArray *typeMapLens; // @synthesize typeMapLens=_typeMapLens;
@property(nonatomic) long long selectCarLengthIndex; // @synthesize selectCarLengthIndex=_selectCarLengthIndex;
@property(retain, nonatomic) NSMutableArray *carLengths; // @synthesize carLengths=_carLengths;
@property(nonatomic) long long selectCarShapeIndex; // @synthesize selectCarShapeIndex=_selectCarShapeIndex;
@property(retain, nonatomic) NSMutableArray *carShapes; // @synthesize carShapes=_carShapes;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UIScrollView *bgScrollView; // @synthesize bgScrollView=_bgScrollView;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(copy, nonatomic) NSString *vehicleType; // @synthesize vehicleType=_vehicleType;
@property(copy, nonatomic) NSString *vehicleLength; // @synthesize vehicleLength=_vehicleLength;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)getCoustomBtnWith:(id)arg1;
- (id)getCoustomLab:(id)arg1;
- (id)getBGViewWithItmeHorizontalGap:(double)arg1 verticalGap:(double)arg2 andData:(id)arg3 tag:(long long)arg4 kindTitle:(id)arg5;
- (void)setConfirmBtnStatus;
- (void)getBtnStyle:(id)arg1 tag:(long long)arg2 index:(long long)arg3;
- (void)setSelectOrDeselctBntStyele:(id)arg1;
- (void)btnClick:(id)arg1;
- (void)confirBtnAction;
- (void)loadData;
- (void)reloadCarLengthsView;
- (void)addCarRuleViewUI;
- (void)addCarLengthsUI;
- (void)addCarShapesUI;
- (void)setupUI;
- (void)viewDidLoad;

@end

