//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UITableView;

@interface SFToCPassPointListView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UIView *_bgView;
    UITableView *_table;
    UIButton *_cancelBut;
    NSArray *_orderLinePassList;
    double _height;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(retain, nonatomic) NSArray *orderLinePassList; // @synthesize orderLinePassList=_orderLinePassList;
@property(retain, nonatomic) UIButton *cancelBut; // @synthesize cancelBut=_cancelBut;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)appRootViewController;
- (void)show;
- (void)hidden;
- (void)cancelAction;
- (void)setupUI;
- (id)initWithOrderLinePasslist:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

