//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface SFToCProviceModel : NSObject
{
    NSString *_provinceName;
    NSString *_provinceCode;
    NSMutableArray *_cityArrM;
}

@property(retain, nonatomic) NSMutableArray *cityArrM; // @synthesize cityArrM=_cityArrM;
@property(retain, nonatomic) NSString *provinceCode; // @synthesize provinceCode=_provinceCode;
@property(retain, nonatomic) NSString *provinceName; // @synthesize provinceName=_provinceName;
- (void).cxx_destruct;
- (id)init;

@end

