//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "SFBidDetailFeelCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, NSTimer, SFImgTitleView, SFToCMarketBidNoticeVM, SFToCMarketGroupDetailVM, TPKeyboardAvoidingTableView, UIButton, UIView;

@interface SFToCMarketGroupDeatilVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, SFBidDetailFeelCellDelegate>
{
    NSTimer *_timer;
    NSTimer *_noticeTimer;
    _Bool _isChangeRemindType;
    _Bool _packageShowMore;
    long long _biddingId;
    unsigned long long _type;
    CDUnknownBlockType _remindChangeBlock;
    NSString *_pushSource;
    TPKeyboardAvoidingTableView *_table;
    UIView *_topView;
    SFImgTitleView *_topTipView;
    UIView *_bottomView;
    UIButton *_joinBut;
    SFToCMarketGroupDetailVM *_detailVM;
    SFToCMarketBidNoticeVM *_bidNoticeVM;
    UIButton *_bidNoticeBut;
}

@property(nonatomic) _Bool packageShowMore; // @synthesize packageShowMore=_packageShowMore;
@property(nonatomic) _Bool isChangeRemindType; // @synthesize isChangeRemindType=_isChangeRemindType;
@property(retain, nonatomic) UIButton *bidNoticeBut; // @synthesize bidNoticeBut=_bidNoticeBut;
@property(retain, nonatomic) SFToCMarketBidNoticeVM *bidNoticeVM; // @synthesize bidNoticeVM=_bidNoticeVM;
@property(retain, nonatomic) SFToCMarketGroupDetailVM *detailVM; // @synthesize detailVM=_detailVM;
@property(retain, nonatomic) UIButton *joinBut; // @synthesize joinBut=_joinBut;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) SFImgTitleView *topTipView; // @synthesize topTipView=_topTipView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) TPKeyboardAvoidingTableView *table; // @synthesize table=_table;
@property(copy, nonatomic) NSString *pushSource; // @synthesize pushSource=_pushSource;
@property(copy, nonatomic) CDUnknownBlockType remindChangeBlock; // @synthesize remindChangeBlock=_remindChangeBlock;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long biddingId; // @synthesize biddingId=_biddingId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)gatherGroundBidGroupShare;
- (void)gatherGroundBidGroupDetail;
- (void)shareAction;
- (void)joinAction;
- (void)getContactInfo:(id)arg1;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)feelListViewPriceDescription;
- (void)pushLinesOverlayViewController:(id)arg1;
- (void)pushLinesOverlay:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)pullDownRefresh;
- (void)bidNoticeAvalibelTime;
- (void)bidAvaliableTime;
- (void)refreshView;
- (void)bidNoticeAction:(id)arg1;
- (void)showGroupRule;
- (void)showAdPic;
- (void)backDidClicked;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

