//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFToCBidConfirmInfoChangeVehicleCellDelegate-Protocol.h"
#import "SFToCBidConfirmInfoHeaderCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, SFToCBidLineArrangeModel, SFToCBidModel, UIButton, UITableView;

@interface SFToCBidConfirmInfoVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, SFToCBidConfirmInfoHeaderCellDelegate, SFToCBidConfirmInfoChangeVehicleCellDelegate>
{
    SFToCBidLineArrangeModel *_lineArrangeModel;
    NSMutableArray *_lineArray;
    SFToCBidModel *_bidModel;
    NSString *_settlementDate;
    long long _biddingId;
    long long _vehicleCount;
    unsigned long long _type;
    NSString *_settleType;
    NSString *_settleDays;
    UITableView *_table;
    NSMutableArray *_dataSourceArray;
    UIButton *_confirmBut;
    SFToCBidLineArrangeModel *_operateModel;
    NSArray *_lineInfoArray;
    NSString *_priceStr;
}

@property(retain, nonatomic) NSString *priceStr; // @synthesize priceStr=_priceStr;
@property(retain, nonatomic) NSArray *lineInfoArray; // @synthesize lineInfoArray=_lineInfoArray;
@property(retain, nonatomic) SFToCBidLineArrangeModel *operateModel; // @synthesize operateModel=_operateModel;
@property(retain, nonatomic) UIButton *confirmBut; // @synthesize confirmBut=_confirmBut;
@property(retain, nonatomic) NSMutableArray *dataSourceArray; // @synthesize dataSourceArray=_dataSourceArray;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) NSString *settleDays; // @synthesize settleDays=_settleDays;
@property(retain, nonatomic) NSString *settleType; // @synthesize settleType=_settleType;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long vehicleCount; // @synthesize vehicleCount=_vehicleCount;
@property(nonatomic) long long biddingId; // @synthesize biddingId=_biddingId;
@property(copy, nonatomic) NSString *settlementDate; // @synthesize settlementDate=_settlementDate;
@property(retain, nonatomic) SFToCBidModel *bidModel; // @synthesize bidModel=_bidModel;
@property(retain, nonatomic) NSMutableArray *lineArray; // @synthesize lineArray=_lineArray;
@property(retain, nonatomic) SFToCBidLineArrangeModel *lineArrangeModel; // @synthesize lineArrangeModel=_lineArrangeModel;
- (void).cxx_destruct;
- (void)unbindVehicle:(id)arg1;
- (void)addOrChangeVehicle:(id)arg1;
- (void)defaultChargeback;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)changeLineArrayWithVehicle:(id)arg1;
- (void)changeVehicleAction;
- (void)changeConfirmButStatus;
- (void)recoverAction;
- (void)trackEventWithEventID:(id)arg1 isSuccess:(_Bool)arg2;
- (void)bidRequest;
- (void)groupRobBid;
- (void)multiCarRobBid;
- (void)showGroupConfirmAlert;
- (void)confirmAction:(id)arg1;
- (void)backDidClicked;
- (void)initializesDisplayMessage;
- (void)setupLeftBarButtonItem;
- (void)updateTotalPrice;
- (void)getDataSourceWithLineArray:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

