//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface SFTocHomeServiceCell : UITableViewCell
{
    UIView *_backView;
    UILabel *_titleLa;
    UILabel *_beIncomeLaTitle;
    UILabel *_beIncomeLa;
    UILabel *_proIncomeLa;
    UILabel *_oilCostLa;
    UILabel *_roadCostLa;
    UILabel *_neutralDaysLa;
    UILabel *_vehicleCostLa;
}

- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)refreshHomeServiceWithOrderFeeStatModel:(id)arg1 year:(long long)arg2 month:(long long)arg3;
- (id)getLabelWithTextFont:(id)arg1 textColor:(id)arg2 text:(id)arg3;
- (void)stepUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;

@end

