//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SFImgTitleView, SFToCBidModel, TPKeyboardAvoidingTableView, UIButton, UIView;

@interface SFToCMarketBidFeelFeedBackVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    _Bool _packageShowMore;
    _Bool _isChangeRemindType;
    long long _biddingId;
    NSString *_pushSource;
    NSString *_distance;
    UIView *_topView;
    SFImgTitleView *_topTipView;
    TPKeyboardAvoidingTableView *_table;
    UIView *_bottomView;
    UIButton *_bargaBut;
    SFToCBidModel *_model;
    NSMutableArray *_carriageArray;
    NSMutableArray *_serviceArray;
    NSMutableArray *_profileArray;
    NSMutableArray *_sumArray;
    NSMutableArray *_settleArray;
}

@property(retain, nonatomic) NSMutableArray *settleArray; // @synthesize settleArray=_settleArray;
@property(retain, nonatomic) NSMutableArray *sumArray; // @synthesize sumArray=_sumArray;
@property(retain, nonatomic) NSMutableArray *profileArray; // @synthesize profileArray=_profileArray;
@property(retain, nonatomic) NSMutableArray *serviceArray; // @synthesize serviceArray=_serviceArray;
@property(retain, nonatomic) NSMutableArray *carriageArray; // @synthesize carriageArray=_carriageArray;
@property(retain, nonatomic) SFToCBidModel *model; // @synthesize model=_model;
@property(nonatomic) _Bool isChangeRemindType; // @synthesize isChangeRemindType=_isChangeRemindType;
@property(nonatomic) _Bool packageShowMore; // @synthesize packageShowMore=_packageShowMore;
@property(retain, nonatomic) UIButton *bargaBut; // @synthesize bargaBut=_bargaBut;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) TPKeyboardAvoidingTableView *table; // @synthesize table=_table;
@property(retain, nonatomic) SFImgTitleView *topTipView; // @synthesize topTipView=_topTipView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(copy, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString *pushSource; // @synthesize pushSource=_pushSource;
@property(nonatomic) long long biddingId; // @synthesize biddingId=_biddingId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)getContactInfo:(id)arg1;
- (void)requestBidDeatil;
- (void)gatherBargaDataWithEventID:(id)arg1;
- (void)trackEventWithEventID:(id)arg1 isSuccess:(_Bool)arg2;
- (void)gatherGroundDriverPlusTradeDetail;
- (void)feelBarga:(id)arg1;
- (void)protocalAction;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)pushLinesOverlayViewController:(id)arg1;
- (void)pushLinesOverlay:(id)arg1;
- (void)refreshView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

