//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFToCAvailableAmountVCDelegate-Protocol.h"
#import "SFToCBondAccountVCDelegate-Protocol.h"
#import "SFToCFreezingAmountVCDelegate-Protocol.h"
#import "SFToCWalletMenuViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, SFToCAccountInfoModel, SFToCAccountWalletInfoVM, SFToCAvailableAmountVC, SFToCFreezingAmountVC, SFToCWalletMenuView, UIScrollView;

@interface SFToCMyWalletVC : SFToCBaseVC <UIScrollViewDelegate, SFToCWalletMenuViewDelegate, SFToCAvailableAmountVCDelegate, SFToCBondAccountVCDelegate, SFToCFreezingAmountVCDelegate>
{
    unsigned long long _selectedIndex;
    SFToCWalletMenuView *_clickBar;
    UIScrollView *_containerScrollerView;
    SFToCAvailableAmountVC *_availableAmountVC;
    SFToCFreezingAmountVC *_freezingAmountVC;
    SFToCAvailableAmountVC *_bondAccountVC;
    SFToCAccountWalletInfoVM *_accountWalletInfoVM;
    SFToCAccountInfoModel *_availableAmountModel;
    SFToCAccountInfoModel *_bondAccountModel;
}

@property(retain, nonatomic) SFToCAccountInfoModel *bondAccountModel; // @synthesize bondAccountModel=_bondAccountModel;
@property(retain, nonatomic) SFToCAccountInfoModel *availableAmountModel; // @synthesize availableAmountModel=_availableAmountModel;
@property(retain, nonatomic) SFToCAccountWalletInfoVM *accountWalletInfoVM; // @synthesize accountWalletInfoVM=_accountWalletInfoVM;
@property(retain, nonatomic) SFToCAvailableAmountVC *bondAccountVC; // @synthesize bondAccountVC=_bondAccountVC;
@property(retain, nonatomic) SFToCFreezingAmountVC *freezingAmountVC; // @synthesize freezingAmountVC=_freezingAmountVC;
@property(retain, nonatomic) SFToCAvailableAmountVC *availableAmountVC; // @synthesize availableAmountVC=_availableAmountVC;
@property(retain, nonatomic) UIScrollView *containerScrollerView; // @synthesize containerScrollerView=_containerScrollerView;
@property(retain, nonatomic) SFToCWalletMenuView *clickBar; // @synthesize clickBar=_clickBar;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)changeMenuVC:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)refreshAllAccount;
- (void)updateAvailableAmountModel:(id)arg1;
- (void)updateAvailableAmountModel:(id)arg1 type:(unsigned long long)arg2;
- (void)addChildControllers;
- (void)initScrollViewContainer;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

