//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray, NSString, SFLinePointModel, SFLinePointView, SFToCBidRequiredInfoModel, UIButton, UILabel, UIView;
@protocol SFToCBidConfirmInfoChangeVehicleCellDelegate;

@interface SFToCBidConfirmInfoChangeVehicleCell : UITableViewCell
{
    SFToCBidRequiredInfoModel *_model;
    unsigned long long _type;
    NSString *_vehicleNum;
    NSString *_errorMessage;
    id <SFToCBidConfirmInfoChangeVehicleCellDelegate> _delegate;
    UIView *_bgView;
    SFLinePointView *_lineView;
    UILabel *_vehicleNumLabel;
    UIButton *_untyingBtn;
    UIButton *_changeBtn;
    UIButton *_addVehicleBtn;
    SFLinePointModel *_startPointModel;
    SFLinePointModel *_destPointModel;
    NSMutableArray *_linePointArray;
}

@property(retain, nonatomic) NSMutableArray *linePointArray; // @synthesize linePointArray=_linePointArray;
@property(retain, nonatomic) SFLinePointModel *destPointModel; // @synthesize destPointModel=_destPointModel;
@property(retain, nonatomic) SFLinePointModel *startPointModel; // @synthesize startPointModel=_startPointModel;
@property(retain, nonatomic) UIButton *addVehicleBtn; // @synthesize addVehicleBtn=_addVehicleBtn;
@property(retain, nonatomic) UIButton *changeBtn; // @synthesize changeBtn=_changeBtn;
@property(retain, nonatomic) UIButton *untyingBtn; // @synthesize untyingBtn=_untyingBtn;
@property(retain, nonatomic) UILabel *vehicleNumLabel; // @synthesize vehicleNumLabel=_vehicleNumLabel;
@property(retain, nonatomic) SFLinePointView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak id <SFToCBidConfirmInfoChangeVehicleCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSString *vehicleNum; // @synthesize vehicleNum=_vehicleNum;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) SFToCBidRequiredInfoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)addVehicleAction;
- (void)changeAction;
- (void)untyingAction;
- (void)setttingViewAtuoLayout;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

