//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIImageView, UILabel;

@interface SFToCMarketBidSuccView : UIView
{
    CDUnknownBlockType _continueFindBidBlock;
    CDUnknownBlockType _checkOrderDetailBlock;
    NSString *_successMsg;
    UIImageView *_bidSuccImgV;
    UILabel *_succMsgLabel;
    UIView *_bgView;
    UIButton *_continueBut;
    UIButton *_checkMoreBut;
}

@property(retain, nonatomic) UIButton *checkMoreBut; // @synthesize checkMoreBut=_checkMoreBut;
@property(retain, nonatomic) UIButton *continueBut; // @synthesize continueBut=_continueBut;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UILabel *succMsgLabel; // @synthesize succMsgLabel=_succMsgLabel;
@property(retain, nonatomic) UIImageView *bidSuccImgV; // @synthesize bidSuccImgV=_bidSuccImgV;
@property(retain, nonatomic) NSString *successMsg; // @synthesize successMsg=_successMsg;
@property(copy, nonatomic) CDUnknownBlockType checkOrderDetailBlock; // @synthesize checkOrderDetailBlock=_checkOrderDetailBlock;
@property(copy, nonatomic) CDUnknownBlockType continueFindBidBlock; // @synthesize continueFindBidBlock=_continueFindBidBlock;
- (void).cxx_destruct;
- (void)checkMoreAction:(id)arg1;
- (void)continueBidAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

