//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface SFToCCarInfo : JSONModel
{
    _Bool _loadMassEmptyFlag;
    _Bool _rtmcDtEmptyFlag;
    NSString *_dlOwner;
    NSString *_reason;
    NSString *_vehicleIdentificationCode;
    NSString *_modifyTm;
    NSString *_loadMass;
    NSString *_modifier;
    NSString *_innerLength;
    NSString *_vehicleBrand;
    NSString *_dlInsuSecondName;
    NSString *_vehicleTon;
    NSString *_createTm;
    NSString *_vehicleAgeEndDt;
    NSString *_vehicleId;
    NSString *_verifyLoadQuality;
    NSString *_vehicleType;
    NSString *_dlInsuName;
    NSString *_creator;
    NSString *_innerHeight;
    NSString *_effectLoadCapacity;
    NSString *_vehicleOrigin;
    NSString *_vehicleCode;
    NSString *_userId;
    NSString *_vehicleCodeColor;
    NSString *_dlExpireDt;
    NSString *_innerWidth;
    NSString *_dlRegDt;
    NSString *_dlInsuPath;
    NSString *_vehicleLength;
    NSString *_lastUpdateId;
    NSString *_fuelType;
    NSString *_dlInsuSecondPath;
    NSString *_licenseStatus;
    NSString *_district;
    NSString *_lastUpdateStatus;
    NSString *_vehicleStatus;
    NSString *_vehicleTypeName;
    NSString *_rtmcStatus;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(nonatomic) _Bool rtmcDtEmptyFlag; // @synthesize rtmcDtEmptyFlag=_rtmcDtEmptyFlag;
@property(nonatomic) _Bool loadMassEmptyFlag; // @synthesize loadMassEmptyFlag=_loadMassEmptyFlag;
@property(copy, nonatomic) NSString *rtmcStatus; // @synthesize rtmcStatus=_rtmcStatus;
@property(copy, nonatomic) NSString *vehicleTypeName; // @synthesize vehicleTypeName=_vehicleTypeName;
@property(copy, nonatomic) NSString *vehicleStatus; // @synthesize vehicleStatus=_vehicleStatus;
@property(copy, nonatomic) NSString *lastUpdateStatus; // @synthesize lastUpdateStatus=_lastUpdateStatus;
@property(copy, nonatomic) NSString *district; // @synthesize district=_district;
@property(copy, nonatomic) NSString *licenseStatus; // @synthesize licenseStatus=_licenseStatus;
@property(copy, nonatomic) NSString *dlInsuSecondPath; // @synthesize dlInsuSecondPath=_dlInsuSecondPath;
@property(copy, nonatomic) NSString *fuelType; // @synthesize fuelType=_fuelType;
@property(copy, nonatomic) NSString *lastUpdateId; // @synthesize lastUpdateId=_lastUpdateId;
@property(copy, nonatomic) NSString *vehicleLength; // @synthesize vehicleLength=_vehicleLength;
@property(copy, nonatomic) NSString *dlInsuPath; // @synthesize dlInsuPath=_dlInsuPath;
@property(copy, nonatomic) NSString *dlRegDt; // @synthesize dlRegDt=_dlRegDt;
@property(copy, nonatomic) NSString *innerWidth; // @synthesize innerWidth=_innerWidth;
@property(copy, nonatomic) NSString *dlExpireDt; // @synthesize dlExpireDt=_dlExpireDt;
@property(copy, nonatomic) NSString *vehicleCodeColor; // @synthesize vehicleCodeColor=_vehicleCodeColor;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(copy, nonatomic) NSString *vehicleOrigin; // @synthesize vehicleOrigin=_vehicleOrigin;
@property(copy, nonatomic) NSString *effectLoadCapacity; // @synthesize effectLoadCapacity=_effectLoadCapacity;
@property(copy, nonatomic) NSString *innerHeight; // @synthesize innerHeight=_innerHeight;
@property(copy, nonatomic) NSString *creator; // @synthesize creator=_creator;
@property(copy, nonatomic) NSString *dlInsuName; // @synthesize dlInsuName=_dlInsuName;
@property(copy, nonatomic) NSString *vehicleType; // @synthesize vehicleType=_vehicleType;
@property(copy, nonatomic) NSString *verifyLoadQuality; // @synthesize verifyLoadQuality=_verifyLoadQuality;
@property(copy, nonatomic) NSString *vehicleId; // @synthesize vehicleId=_vehicleId;
@property(copy, nonatomic) NSString *vehicleAgeEndDt; // @synthesize vehicleAgeEndDt=_vehicleAgeEndDt;
@property(copy, nonatomic) NSString *createTm; // @synthesize createTm=_createTm;
@property(copy, nonatomic) NSString *vehicleTon; // @synthesize vehicleTon=_vehicleTon;
@property(copy, nonatomic) NSString *dlInsuSecondName; // @synthesize dlInsuSecondName=_dlInsuSecondName;
@property(copy, nonatomic) NSString *vehicleBrand; // @synthesize vehicleBrand=_vehicleBrand;
@property(copy, nonatomic) NSString *innerLength; // @synthesize innerLength=_innerLength;
@property(copy, nonatomic) NSString *modifier; // @synthesize modifier=_modifier;
@property(copy, nonatomic) NSString *loadMass; // @synthesize loadMass=_loadMass;
@property(copy, nonatomic) NSString *modifyTm; // @synthesize modifyTm=_modifyTm;
@property(copy, nonatomic) NSString *vehicleIdentificationCode; // @synthesize vehicleIdentificationCode=_vehicleIdentificationCode;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(copy, nonatomic) NSString *dlOwner; // @synthesize dlOwner=_dlOwner;
- (void).cxx_destruct;

@end

