//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UILabel;

@interface SFToCMarketVehicleLineTypeView : UIView
{
    _Bool _hasLocation;
    CDUnknownBlockType _block;
    CDUnknownBlockType _nearbyRelocationBlock;
    NSMutableArray *_selectedArray;
    NSArray *_dataArray;
    unsigned long long _type;
    UILabel *_titleLabel;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool hasLocation; // @synthesize hasLocation=_hasLocation;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSMutableArray *selectedArray; // @synthesize selectedArray=_selectedArray;
@property(copy, nonatomic) CDUnknownBlockType nearbyRelocationBlock; // @synthesize nearbyRelocationBlock=_nearbyRelocationBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (double)getViewHeight;
- (void)defaultValue;
- (void)btnClick:(id)arg1;
- (id)getCoustomBtnWith:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithVehicleLineType:(unsigned long long)arg1;

@end

