//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray, NSString;
@protocol SFToCPermitmodel;

@interface SFToCPermitGroup : JSONModel
{
    NSString *_itemname;
    NSString *_itemcode;
    long long _permitType;
    NSMutableArray<SFToCPermitmodel> *_items;
}

+ (_Bool)propertyIsOptional:(id)arg1;
@property(retain, nonatomic) NSMutableArray<SFToCPermitmodel> *items; // @synthesize items=_items;
@property(nonatomic) long long permitType; // @synthesize permitType=_permitType;
@property(copy, nonatomic) NSString *itemcode; // @synthesize itemcode=_itemcode;
@property(copy, nonatomic) NSString *itemname; // @synthesize itemname=_itemname;
- (void).cxx_destruct;

@end

