//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "SFToCMarketRecommendDelegate-Protocol.h"

@class NSString, SFToCBidModel, SFToCMarketRecommendView;

@interface SFToCMarketBidRecommendVC : SFToCBaseVC <SFToCMarketRecommendDelegate>
{
    unsigned long long _recommendType;
    SFToCBidModel *_model;
    long long _orderId;
    long long _biddingLineId;
    NSString *_bidFailMsg;
    NSString *_successMsg;
    SFToCMarketRecommendView *_recommendV;
}

@property(retain, nonatomic) SFToCMarketRecommendView *recommendV; // @synthesize recommendV=_recommendV;
@property(retain, nonatomic) NSString *successMsg; // @synthesize successMsg=_successMsg;
@property(retain, nonatomic) NSString *bidFailMsg; // @synthesize bidFailMsg=_bidFailMsg;
@property(nonatomic) long long biddingLineId; // @synthesize biddingLineId=_biddingLineId;
@property(nonatomic) long long orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) SFToCBidModel *model; // @synthesize model=_model;
@property(nonatomic) unsigned long long recommendType; // @synthesize recommendType=_recommendType;
- (void).cxx_destruct;
- (void)queryData;
- (void)backDidClicked;
- (void)continueBidPrice;
- (void)checkBidDeatil:(id)arg1;
- (void)toOrderLinePage;
- (void)checkOrderDetail;
- (void)continueFindBid;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

