//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol SFToCLoginSwitchViewDelegate;

@interface SFToCLoginSwitchView : UIView
{
    id <SFToCLoginSwitchViewDelegate> _delegate;
    UIButton *_internalButton;
    UIButton *_externalButton;
    UIView *_line;
    UIView *_line1;
    UIView *_line2;
    UIButton *_selectedBtn;
}

@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(retain, nonatomic) UIView *line2; // @synthesize line2=_line2;
@property(retain, nonatomic) UIView *line1; // @synthesize line1=_line1;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIButton *externalButton; // @synthesize externalButton=_externalButton;
@property(retain, nonatomic) UIButton *internalButton; // @synthesize internalButton=_internalButton;
@property(nonatomic) __weak id <SFToCLoginSwitchViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateUIWith:(long long)arg1;
- (void)switchAction:(id)arg1;
- (void)initUI;
- (id)init;

@end

