//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SFToCBaseVC.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "SFToCMarketRecommendDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SFToCBidModel, SFToCLocationService, SFToCMarketBidDetailVM, SFToCMarketBidVM, SFToCMarketCityFilter, SFToCMarketFilterView, SFToCMarketNearbyModel, SFToCMarketQuickFilter, SFToCMarketRecommendView, SFToCMarketTimeFilterView, SFToCMarketVehicleLineFilter, UITableView;

@interface SFToCMarketBidVC : SFToCBaseVC <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, SFToCMarketRecommendDelegate>
{
    SFToCMarketFilterView *_filterView;
    unsigned long long _filterType;
    SFToCMarketQuickFilter *_qucikFilterView;
    UITableView *_table;
    SFToCMarketRecommendView *_recommendView;
    SFToCMarketCityFilter *_filterStartCityView;
    SFToCMarketCityFilter *_filterDesCityView;
    SFToCLocationService *_locationService;
    SFToCMarketVehicleLineFilter *_filterVehicleLineView;
    NSString *_vehicleCode;
    NSString *_vehicleLen;
    NSString *_lineCode;
    NSString *_startCityCode;
    NSString *_startProviceCode;
    NSString *_destCityCode;
    NSString *_destProviceCode;
    NSString *_orderType;
    NSString *_startDate;
    NSString *_orderBy;
    NSString *_myVehicle;
    NSString *_groupCode;
    SFToCMarketNearbyModel *_nearbyModel;
    SFToCMarketTimeFilterView *_filterTimerView;
    SFToCMarketBidVM *_marketVM;
    SFToCBidModel *_bidModel;
    SFToCMarketBidDetailVM *_bidDetailVM;
}

@property(retain, nonatomic) SFToCMarketBidDetailVM *bidDetailVM; // @synthesize bidDetailVM=_bidDetailVM;
@property(retain, nonatomic) SFToCBidModel *bidModel; // @synthesize bidModel=_bidModel;
@property(retain, nonatomic) SFToCMarketBidVM *marketVM; // @synthesize marketVM=_marketVM;
@property(retain, nonatomic) SFToCMarketTimeFilterView *filterTimerView; // @synthesize filterTimerView=_filterTimerView;
@property(retain, nonatomic) SFToCMarketNearbyModel *nearbyModel; // @synthesize nearbyModel=_nearbyModel;
@property(retain, nonatomic) NSString *groupCode; // @synthesize groupCode=_groupCode;
@property(retain, nonatomic) NSString *myVehicle; // @synthesize myVehicle=_myVehicle;
@property(retain, nonatomic) NSString *orderBy; // @synthesize orderBy=_orderBy;
@property(retain, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSString *orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *destProviceCode; // @synthesize destProviceCode=_destProviceCode;
@property(retain, nonatomic) NSString *destCityCode; // @synthesize destCityCode=_destCityCode;
@property(retain, nonatomic) NSString *startProviceCode; // @synthesize startProviceCode=_startProviceCode;
@property(retain, nonatomic) NSString *startCityCode; // @synthesize startCityCode=_startCityCode;
@property(retain, nonatomic) NSString *lineCode; // @synthesize lineCode=_lineCode;
@property(retain, nonatomic) NSString *vehicleLen; // @synthesize vehicleLen=_vehicleLen;
@property(retain, nonatomic) NSString *vehicleCode; // @synthesize vehicleCode=_vehicleCode;
@property(retain, nonatomic) SFToCMarketVehicleLineFilter *filterVehicleLineView; // @synthesize filterVehicleLineView=_filterVehicleLineView;
@property(retain, nonatomic) SFToCLocationService *locationService; // @synthesize locationService=_locationService;
@property(retain, nonatomic) SFToCMarketCityFilter *filterDesCityView; // @synthesize filterDesCityView=_filterDesCityView;
@property(retain, nonatomic) SFToCMarketCityFilter *filterStartCityView; // @synthesize filterStartCityView=_filterStartCityView;
@property(retain, nonatomic) SFToCMarketRecommendView *recommendView; // @synthesize recommendView=_recommendView;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) SFToCMarketQuickFilter *qucikFilterView; // @synthesize qucikFilterView=_qucikFilterView;
@property(nonatomic) unsigned long long filterType; // @synthesize filterType=_filterType;
@property(retain, nonatomic) SFToCMarketFilterView *filterView; // @synthesize filterView=_filterView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)showPermitAlertViewMessage:(id)arg1;
- (void)bidButActionWithModel:(id)arg1;
- (void)checkBidDeatil:(id)arg1;
- (void)trackEventWithEventID:(id)arg1 isSuccess:(_Bool)arg2;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)gatherQuickTbpDataWithButtonEvent:(id)arg1;
- (void)gatherGroundTbpDataWithEvenID:(id)arg1;
- (void)gatherGroundTbpMarketList:(id)arg1 pageIndex:(long long)arg2;
- (void)refreshRecommendUI;
- (void)loadMoreRefresh;
- (void)pullDownRefresh;
- (void)requestLocationCityDate;
- (void)refreshList;
- (void)viewDidLayoutSubviews;
- (void)reLayoutSubViews;
- (void)resetFilterView;
- (void)showFilterTypeView;
- (void)closeFilterTypeView;
- (void)getDefaultFilterValue;
- (void)affirmBidArt;
- (void)relocation:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)initial;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

