//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SGSHTTP/SGSHttpRequest.h>

@class NSString;

@interface SGSUploadRecordRequest : SGSHttpRequest
{
    NSString *_recordPath;
    NSString *_fileId;
    NSString *_serverPath;
}

@property(copy, nonatomic) NSString *serverPath; // @synthesize serverPath=_serverPath;
@property(copy, nonatomic) NSString *fileId; // @synthesize fileId=_fileId;
@property(copy, nonatomic) NSString *recordPath; // @synthesize recordPath=_recordPath;
- (void).cxx_destruct;
- (id)getNowDateTimeStr;
- (id)getNowtimeStr;
- (id)customUrlRequest;

@end

