//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;
@protocol TaskDetaiHeadlViewDelegate;

@interface TaskDetaiHeadlView : UIView
{
    id <TaskDetaiHeadlViewDelegate> _delegate;
    UIImageView *_bgView;
    UIImageView *_imgView;
    UILabel *_titleLab;
    UIButton *_newsBtn;
    UIButton *_rightBtn;
    UIButton *_leftBtn;
}

@property(retain, nonatomic) UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIButton *newsBtn; // @synthesize newsBtn=_newsBtn;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak id <TaskDetaiHeadlViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateTaskDetaiHeadlViewState:(long long)arg1;
- (void)leftBtnAction:(id)arg1;
- (void)rightBtnAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 showOrder:(_Bool)arg2;

@end

