//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (mta_auto_page_swizzling)
+ (void)mta_alltrack_swizzleMethods:(Class)arg1 originalSelector:(SEL)arg2 swizzledSelector:(SEL)arg3;
+ (void)mta_alltrack_hook;
- (id)mta_alltrack_page_title;
- (void)mta_auto_page_hook_viewWillDisappear:(_Bool)arg1;
- (void)mta_auto_page_hook_viewDidAppear:(_Bool)arg1;
@end

